### ISSUE TITLE
Cannot create working shortcut for selecting any tool widget

### ISSUE THREAD

**Issue by e-d-n-a** [pyzo/pyzo#1059]
I want to select active tools via shortcuts and added them via "Shortcut mappings/tools" menu.

I originally tried setting them to various F-keys, but also tried "Ctrl+Fx" or even a simple "Ctrl+H". 
I deleted all other shortcuts using F-keys above F3 (so there are no duplicates).

No matter which shortcut I try for any tool selecting action, the action is NOT getting fired, but an error appears in the pyzo startup console on every shortcut press:
```QAction::event: Ambiguous shortcut overload: [...]```
With `[...]` being the name of some shortcut pressed for tool selection (e.g. 'F5', 'Ctrl+F5' or 'Ctrl+H' etc).

I'm not sure how to interpret this error, but it seems to hint to a bug while handling shortcuts for these kinds of actions.
I only found this so far:
https://forum.qt.io/topic/99653/ambiguous-shortcut-overload

**Quote from the answer:**
```3. The first things that comes to my mind would to check what you do with all your actions. For example, are they set on several widgets ? Are they re-used ?```

**Maybe it has to do with the fact, that these actions are present in 2 different menus (menu bar, context menu of tools)!?**
![grafik](https://github.com/user-attachments/assets/1f1493ab-15e8-4015-bab9-89270ad29d02)
![grafik](https://github.com/user-attachments/assets/ae186b17-fe12-40e1-8d5a-b16ed9674381)

Has somebody tried and succeeded in using shortcuts for tool selecting actions on any platform or can reproduce this issue?

### Environment:
Windows-x64
Python 3.9.17-x64
PySide2 5.15.2.1
pyzo 4.16.0

**Comment by e-d-n-a** [comment]
I just succeeded in adding working shortcuts, by commenting out the extra addition of actions to the main window:
[see method 'setShortcut' of KeyMapper-class in core/menu.py {v4.16.0}](https://github.com/pyzo/pyzo/blob/bb046232e27ec538405d5a576a53ae25823db5d8/pyzo/core/menu.py#L239)

This line stems from the 7yo issue #470 and is probably obsolete now!?

**Comment by bdieterm** [comment]
@e-d-n-a
Awesome! Thanks for tracking this error down and proposing the solution.

I tested this on Linux with Qt5 and Qt6 wrappers, and I can reproduce the errors you have seen and I can also confirm that your fix works.

Would you like to create a Pull Request to remove that line(s)? You can do that by editing that source file in the web browser.
Feel free to ask if you are unsure or need help. Otherwise we could also create the PR.

**Comment by e-d-n-a** [comment]
Done. See PR #1061 .
