### ISSUE TITLE
Pyzo crashing on Ubuntu - Wayland protocol error

### ISSUE THREAD

**Issue by iamthebull** [pyzo/pyzo#1068]
I am using Pyzo on Ubuntu 24.04.1 LTS and I also had the same problem on Ubuntu 22.04.3 LTS.

```
Version info
Pyzo version: 4.16.0 (source)
Platform: linux
Python version: 3.12.3
Qt version: 6.7.1
PyQt6 version: 6.7.1
```

This happens both when I'm typing in the editor and in the shell. I was just writing a simple for loop:
`for i in range(...`
and as soon as I type the '(' Pyzo crashes and reports:
`The Wayland connection experienced a fatal error: Protocol error`
if instead I start typing `for i in ran` and then use `Tab` to auto complete `range` then it does not crash.

**Comment by iamthebull** [comment]
It also does the same with PySide6
```
Version info
Pyzo version: 4.16.0 (source)
Platform: linux
Python version: 3.12.3
Qt version: 6.7.2
PySide6 version: 6.7.2
```

**Comment by bdieterm** [comment]
Hi @iamthebull!
Thanks for reporting this problem. I can reproduce it now and I am working on fixing it.
Meanwhile you could use the PyQt5 or PySide2 wrappers, for example:
`$ sudo apt-get install python3-pyqt5`
and then
`$ QT_API=pyqt5 python3 /path/to/pyzo-main/pyzolauncher.py`
With Qt5 instead of Qt6 the darkmode does not work properly, but everything else should work fine.

**Comment by iamthebull** [comment]
I installed PyQt5 in a venv
```
$ python3 -m venv pyqt5env
$ cd pyqt5env/bin/
$ ./pip install PyQt5
```
Then I tried to launch Pyzo using the following but it did not work:
```
$ pyqt5env/bin/python3 pyzo-main/pyzolauncher.py 
Started our command server
Loaded theme 'Default'
Loaded theme 'Solarized_Light'
Loaded theme 'Solarized_Dark'
Loaded theme 'default_dark'
Loaded theme 'Scintilla'
Loaded theme 'Dark'
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, vnc, webgl, xcb.

Fatal Python error: Aborted

Thread 0x0000770a836006c0 (most recent call first):
  File "/usr/lib/python3.12/socket.py", line 295 in accept
  File "/mydocs/freecad/pyzo-main/pyzo/yoton/clientserver.py", line 154 in run
  File "/usr/lib/python3.12/threading.py", line 1073 in _bootstrap_inner
  File "/usr/lib/python3.12/threading.py", line 1030 in _bootstrap

Thread 0x0000770a8ca006c0 (most recent call first):
  File "/usr/lib/python3.12/threading.py", line 355 in wait
  File "/mydocs/freecad/pyzo-main/pyzo/yoton/events.py", line 318 in _mainloop
  File "/mydocs/freecad/pyzo-main/pyzo/yoton/events.py", line 303 in run
  File "/usr/lib/python3.12/threading.py", line 1073 in _bootstrap_inner
  File "/usr/lib/python3.12/threading.py", line 1030 in _bootstrap

Current thread 0x0000770a8d7a2080 (most recent call first):
  File "/mydocs/freecad/pyzo-main/pyzo/_start.py", line 241 in start
  File "/mydocs/freecad/pyzo-main/pyzo/__init__.py", line 56 in start
  File "/mydocs/freecad/pyzo-main/pyzolauncher.py", line 54 in <module>

Extension modules: PyQt5.QtCore, PyQt5.QtGui, PyQt5.QtWidgets (total: 3)
Aborted (core dumped)
```
Did I do something wrong here?

**Comment by bdieterm** [comment]
@iamthebull:
I just commited a fix for the problem you reported and a similar problem.

Can you please fetch the[ newest Pyzo source code](https://github.com/pyzo/pyzo/archive/refs/heads/main.zip) and run Pyzo (e.g. via pyzolauncher.py).

Does this solve the problem?

Regarding the problem with running Pyzo from source with Qt5:
>Then I tried to launch Pyzo using the following but it did not work:
>$ pyqt5env/bin/python3 pyzo-main/pyzolauncher.py 
>$ qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

This looks like a missing package. After executing
`$ sudo apt-get install libxcb-cursor0`
that problem should also be solved.

**Comment by iamthebull** [comment]
> Does this solve the problem?

Yes the new source code is working now. Much appreciated.

> This looks like a missing package. After executing
> $ sudo apt-get install libxcb-cursor0
> that problem should also be solved.

This on the other hand did not work.

**Comment by bdieterm** [comment]
My bad. Actually you need another library:
`$ sudo apt-get install libxcb-xinerama0`

When there are problems with Qt libraries in Linux, I usually set the `QT_DEBUG_PLUGINS` variable to find more about the problem. For your example, this would be:
`$ QT_DEBUG_PLUGINS=1 pyqt5env/bin/python3 pyzo-main/pyzolauncher.py`
and then one of the many output lines is
`(libxcb-xinerama.so.0: cannot open shared object file: No such file or directory)`

**Comment by iamthebull** [comment]
> $ sudo apt-get install libxcb-xinerama0

Yes, this worked. Thanks.

> When there are problems with Qt libraries in Linux, I usually set the QT_DEBUG_PLUGINS variable to find more about the problem. For your example, this would be:

Thanks for the tip. I'll try that next time.
