### ISSUE TITLE
Tooltips unreadable

### ISSUE THREAD

**Issue by Ramseslegrand** [pyzo/pyzo#1074]
![test_pyexiv2 py (-media-jean-DATA-Developpement-PythonIDLE-IPTC-test_pyexiv2 py) - Interactive Editor for Python_002](https://github.com/user-attachments/assets/fc82ed24-fe57-4103-af83-93ff3e286e9d)
As you can see, it's not possible to read the tab tooltip. The same for all the others. Maybe the color of the fonts ?
I use this Linux system:
  Kernel: 5.15.0-122-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 6.0.4
    tk: GTK 3.24.33 wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia
    base: Ubuntu 22.04 jammy

**Comment by bdieterm** [comment]
I am trying to reproduce the problem, but so far I wasn't able to. I already tested this on Ubuntu 22.04 with x11 and with Wayland. Next I will try Mint 21.3 in a virtual machine.

Which Pyzo version are you using? The v4.16.0 release or the current source code from the main branch?
How do you start Pyzo, e.g. from source (for the different possibilities see https://github.com/pyzo/pyzo#installation).
Can you open the "About" dialog in Pyzo (via the "Help" menu) and post the version info, e.g.:
```
Version info
Pyzo version: 4.16.0 (binary)
Platform: linux
Python version: 3.9.19
Qt version: 5.15.2
PyQt5 version: 5.15.10
```
Do calltips work, e.g. when entering `dir(`?
If you run Pyzo from source, does the problem also occur with other Qt wrappers?

**Comment by bdieterm** [comment]
Just tested this on Mint 21.3 and I can reproduce the problem by running the main branch from source with the system's python interpreter and Qt wrappers from `sudo apt-get install python3-pyqt5`.

I will have a look at this problem.

**Comment by bdieterm** [comment]
Already found the cause of the problem:
The "Qt5 Configuration Tool" (started via `qt5ct` in a terminal) seems to mess up the Qt style sheets.
After changing the default settings "style: gtk2" in the "Appearance" tab to "Fusion" the tooltips look normal.

@Ramseslegrand: Does this solve your problem?

**Comment by Ramseslegrand** [comment]
style qt5ct-style works to.
It does not solve the problem, but it's OK to work.
Many thanks

**Comment by bdieterm** [comment]
There is also an alternative solution:

I just tested running Pyzo in Mint 21.3 with a different Python Interpreter:
Python 3.12 from https://github.com/indygreg/python-build-standalone
With that Python interpreter and a Qt 5/6 wrapper, the tooltips were displayed correctly in Pyzo, no matter which style was set in the "Qt5 Configuration Tool".
