### ISSUE TITLE
Cannot install pyzo 4.17.0 on Windows

### ISSUE THREAD

**Issue by YoannUniKS** [pyzo/pyzo#1095]
Hi,

I want to update pyzo to the latest version. After downloading the installer from the website, I cannot open it. Windows 10 throws a pop-up saying that this app cannot be installed on this PC and that I should contact the software provider. There is no way around, I cannot go further.

Thanks for the feedback!

**Comment by YoannUniKS** [comment]
Ok I found the issue. The problem was that I am downloading the installer with firefox, which says that there is a virus in the file. The download was not complete until I clicked confirm download until the end in firefox. No it works. Not really reassuring however, both firefox and windows throw virus alerts...

**Comment by bdieterm** [comment]
> Not really reassuring however, both firefox and windows throw virus alerts...

The false positives are a known problem, see issue #800 for details.

If it makes you feel better you also have the options to
* [run Pyzo from source](https://github.com/pyzo/pyzo#running-pyzo-from-source)
* [run Pyzo as a Python module from pypi.org](https://github.com/pyzo/pyzo#running-pyzo-as-a-module)
* or to [build your own Pyzo executable](https://github.com/pyzo/pyzo#building-your-own-binary-executable-of-pyzo)

All three options are actually quite easy to do yourself. I will happily support you if you need help.
