### ISSUE TITLE
Isn't the shortcut to execute the selection incorrect ?

### ISSUE THREAD

**Issue by Baptiste612** [pyzo/pyzo#1096]
Isn't the shortcut to execute the selection F9 instead of Alt+Return (which doesn't work)?
![image](https://github.com/user-attachments/assets/8cb3c37f-25c3-4476-acb4-d5c5a27c4c3d)

**Comment by bdieterm** [comment]
Please be so kind to translate the title to english.

**Comment by bdieterm** [comment]
Both is correct. You can assign two different shortcuts to every menu entry. See "Shortcut mappings" dialog (via "Settings -> Edit key mappings" in the menu) -- there are the columns "Shortcut 1" and "Shortcut 2".
For example, to execute a file, you can either press Ctrl+E or F5.

**Comment by bdieterm** [comment]
I am wondering though, why Alt+Return is not working for you.
Make sure you really use the return key. The enter key is a different one (see [here](https://upload.wikimedia.org/wikipedia/commons/c/c1/ISO_British_QWERTY_%28Windows%29_Enter_Return.svg)).
Does it work when you re-assign the Alt+Return shortcut in the shortcut mappings dialog?

**Comment by Baptiste612** [comment]
Okay, thanks a lot for your help

**Comment by bdieterm** [comment]
You are welcome.
