### ISSUE TITLE
Inconsistent appearance of the scrollbar in the source structure

### ISSUE THREAD

**Issue by commongeek** [pyzo/pyzo#1110]
Scrollbar looks different than in other panels. It doesn't matter which Qt theme I use. I am on Windows.

![Screenshot from 2024-12-20 13-36-19](https://github.com/user-attachments/assets/47631f37-b095-475d-bc01-4459cac02fd8)

**Comment by bdieterm** [comment]
Fixed. Thanks for reporting the bug.
