### ISSUE TITLE
Embed IPython shell?

### ISSUE THREAD

**Issue by almarklein** [pyzo/pyzo#136]
Originally reported by: **Anonymous**

---

_Imported from [iep.googlecode.com issue #136](https://code.google.com/p/iep/issues/detail?id=136), reported by klo...@gmail.com_

I know this may be senseless, but as I see there is GUI invent loop in Shell configuration, I thought to ask.

One of my main concerns while using IPython Qt console, is lacks of some UI element that will help me reuse code snippets. It maybe just the way I use it, as I often use separate editor to keep track of various snippets either from previous or current session.
I hope I can embed my know environment (IPython Qt console) as ipe shell and extend my workspace the right way.

I tried to set Qt console, but ipe shell configuration does not accept command arguments as I see. Then I just configured ipe shell to IPython terminal and surprise - I see some kind of IPython clone :) I guess it's better then plain interpreter but is it not possible to embed real IPython Qt console in ipe?

Thanks :)

---
- Bitbucket: https://bitbucket.org/iep-project/iep/issue/136

**Comment by hudcap** [comment]
It is somewhat implied from the above discussion that it's possible to run an IPython QtConsole in pyzo.
Is this correct? Or was the intention for the IPython regular console (that I currently use -- thank you 👍)?
If yes, how can it be done?
Thanks!

**Comment by almarklein** [comment]
Not the QtConsole, but the regular one. It can be activated in the shell configuration. Note though that it uses Pyzo's autocompletion, not IPython's, and has a few other limitations.
