### ISSUE TITLE
Find in files tool

### ISSUE THREAD

**Issue by almarklein** [pyzo/pyzo#2]
Originally reported by: **Almar Klein (Bitbucket: [almarklein](http://bitbucket.org/almarklein), GitHub: [almarklein](http://github.com/almarklein))**

---

_Imported from [iep.googlecode.com issue #2](https://code.google.com/p/iep/issues/detail?id=2), reported by almar.klein@gmail.com_

A tool to search for text in all the files in a directory. Maybe combine with a tool that simply lists files. Shouldn't be too hard.

---
- Bitbucket: https://bitbucket.org/iep-project/iep/issue/2

**Comment by clavay** [comment]
Hello,

I don't find the way to search for text in all the files of a directory (recursively).
Is it possible ?

Thank you.

**Comment by almarklein** [comment]
It's in the file browser tool.

<img width="336" alt="image" src="https://user-images.githubusercontent.com/3015475/230337083-2b1c19dc-6b1a-40c9-9621-db187887e7b3.png">
