### ISSUE TITLE
Auto-save of source code

### ISSUE THREAD

**Issue by almarklein** [pyzo/pyzo#204]
Originally reported by: **Anonymous**

---

_Imported from [iep.googlecode.com issue #204](https://code.google.com/p/iep/issues/detail?id=204), reported by jonathan...@gmail.com_

What steps will reproduce the problem?
1. add or edit some source code
2. have iep crash
3. restart iep, notice that your work has disappeared
4. tears

What is the expected output? What do you see instead?

I expect to see the source code that I was previously editing (or a very recent snapshot thereof).

Crashes are inevitable, esp. in GUI apps with their many components. That is why almost all take considerable care to provide auto-save functions--some only periodically, but increasingly, complete to the latest keystroke.

What version of the product are you using? On what operating system?

3.2 beta for Mac OS X 10.7.5

Please provide any additional information below.

iep looks very nicely done. Don't let avoidable user frustration drive them away.

I wasn't upset when a beta version crashed. But the moment it didn't remember what
I had been doing when I restarted it, I knew that I would have been upset if it had
happened during real work. 

---
- Bitbucket: https://bitbucket.org/iep-project/iep/issue/204

**Comment by almarklein** [comment]
Supersceded by #364

**Comment by ewen-lbh** [comment]
#364 is closed because of this issue, and #204 is closed because it's superseded by #364.

We got circular dependencies in github issues now?
