### ISSUE TITLE
Persistent command history

### ISSUE THREAD

**Issue by almarklein** [pyzo/pyzo#248]
Originally reported by: **Anonymous**

---

The command history should be preserved between the IEP/shell restarts. This can be 

(a) fully implemented on the IEP side, e.g., IEP would take care of storing (and loading) the history data somewhere or

(b) IEP can only provide API to read and restore the history and the user would need to take care of saving/loading it somewhere, e.g., with the help of custom .pystartup script and os.atexit.

See also this [discussion](https://groups.google.com/forum/#!topic/iep_/AhevQUhhdAU).

---
- Bitbucket: https://bitbucket.org/iep-project/iep/issue/248

**Comment by almarklein** [comment]
Ping this.

**Comment by Diti24** [comment]
I saw this issue is set to minor, I think that from a usability point of view solving this would bring a lot of benefits, unfortunately this issue is really annoying. So may be could be reconsidered.
Thanks,
Deitrich

**Comment by almarklein** [comment]
I've actually written this issue down on a personal todo list, so its priority is certainly more than "minor" :)  now to find some time to do it ...

**Comment by almarklein** [comment]
This shouldnt have closed with that PR, but with commit https://github.com/pyzo/pyzo/commit/aa9699ee23d5c7fe8141e643fd843a498ccf5c13

Anyway, its there!
