### ISSUE TITLE
Linting with pep8

### ISSUE THREAD

**Issue by almarklein** [pyzo/pyzo#362]
Originally reported by: **Eric Tingey (Bitbucket: [ebtingey](http://bitbucket.org/ebtingey), GitHub: [ebtingey](http://github.com/ebtingey))**

---

I was wondering if there was any linting feature in IEP.  If not, is that something that could be added to use pep8.

---
- Bitbucket: https://bitbucket.org/iep-project/iep/issue/362

**Comment by almarklein** [comment]
Dupe of #246

**Comment by Diti24** [comment]
Hi I see that both 246 and 362 are closed...
is PEP8 suggestion already implemented?

With the latest improvements of 4.4.0 if we would (for my point of view) 
1) also the pep8 suggestion, first
2) add block selection/editing, second

PYZO would become the PERFECT editor for python scientific development!!!

As an experienced Matlab user, and a tester of other python IDE's like Spyder, Pydev... I can state that PYZO is the best entry and replacement for Matlab. 

Considering the fantastic postmortem debugger and flexibility of Python
PYZO + Python (anaconda) has definitely overcome Matlab!!!

**Comment by Diti24** [comment]
... sorry...
https://github.com/pyzo/pyzo/issues/246 is open...
... ok the other considerations are still valid :-)
