### ISSUE TITLE
Not Responding When Closing

### ISSUE THREAD

**Issue by almarklein** [pyzo/pyzo#373]
Originally reported by: **Eric Tingey (Bitbucket: [ebtingey](http://bitbucket.org/ebtingey), GitHub: [ebtingey](http://github.com/ebtingey))**

---

Just about every time I try to close IEP, it freezes and says that the program is not responding.  I just have to force close it each time it happens.  Thankfully I don't lose anything that has been saved and when I open it again it seems to be working fine.  I just wanted to bring this issue up to see if there was a way to fix it.  Would it be that something is running in the background that I'm not aware of which does not let it close?

---
- Bitbucket: https://bitbucket.org/iep-project/iep/issue/373

**Comment by almarklein** [comment]
I think I did not see this again. Likely related to Qt and/or freezing. Though it could come back in another form.

**Comment by Zarainia** [comment]
I've been having this problem lately. Did you ever find out what causes it?

**Comment by almarklein** [comment]
No, sorry, I have never been able to reproduce it.
