### ISSUE TITLE
Merging Pyzo and IEP

### ISSUE THREAD

**Issue by almarklein** [pyzo/pyzo#379]
The plan is to smash together the IEP and Pyzo projects. Because Pyzo has become too much a burden to maintain. We want a leaner "product" with shorter release cycles.

* Pyzo is the new name (because the name "IEP" sucks).
* It's an editor, which helps the user install a miniconda env.
* The logo is ... probably that of IEP (3 colored rectangles)

The plan:

* [x] transfer the IEP repo to GitHub (incl. issues)
* [ ] update issue labels
* [ ] update wiki
* [x] clean up references to Pyzo in the codebase
* [x] convert references to "IEP" to "Pyzo"
* [x] transfer functionality of pyzolib to this project (so we can ditch pyzolib)
* [x] update shell widget when no interpreter present: help install miniconda
* [x] probably make a web page with clear instructions on how to get started (install pyzo, install miniconda)
* [x] revise "hey, lets install a Python env" dialog
* [x] see if we can discover miniconda root dirs.
* [ ] make use of `flexx.util.config` for configuration, and store *state* seperately (with what format?)
* [x] get rid of IEP guide -> make docs instead
* [x] IPython is not default shell

**Comment by Spaak** [comment]
The way I understood Pyzo, is that it is a fully-fledged Python distribution, including packages like Numpy and Scipy etc. For quickly getting started with interactive data analysis (a la Matlab) this is very nice, but more advanced users will want to install their own environment.

Could you elaborate a bit on how you see this working when merging Pyzo and IEP? When a user installs the new Pyzo, does he/she get IEP only, and then when they answer "yes" to the question of whether to install an environment, they get all the packages?

**Comment by almarklein** [comment]
Pyzo is still meant to be a way "For quickly getting started with interactive data analysis".

Basically, what we'll be calling Pyzo will be the IDE only. The user needs to install the environment separately. To make this as easy as possible, there is a quickstart page on the website (in place of a download page), and the shell widget will show a brief explanation plus a link to the quickstart when there is no interpreter found. The dialog to install-miniconda-plus-sci-packages that we recently added is removed.

Some motivations:
* This makes it more clear to the user what he/she is using, and how additional packages can be installed.
* The dialog that we recently added makes installing miniconda very easy, but I had a use-case where it failed for some reason, so I pointed the user to download miniconda, which worked fine, but completely negates the idea of the dialog.
* This makes maintenance easier. I can now focus my precious time on the IDE, and let the conda team deal with the environment.

**Comment by satishgoda** [comment]
Really nice decision. I am giving a presentation on Pyzo today to my team today afternoon.

**Comment by ghisvail** [comment]
> transfer functionality of pyzolib to this project (so we can ditch pyzolib)

@almarklein how high is this in the priority list for the next releases ? I am really interested in having this solved so I can drop `pyzolib` from the Debian archive and just have `pyzo` + transitional `iep` proxy package.

**Comment by almarklein** [comment]
I can make it a higher priority: I made #416 to make this more visible.

**Comment by ghisvail** [comment]
Thanks, that would be awesome @almarklein

**Comment by almarklein** [comment]
> transfer functionality of pyzolib to this project (so we can ditch pyzolib)

@ghisvail done

**Comment by ghisvail** [comment]
@almarklein :+1:

Waiting for the next tagged release to update the packaging and remove `pyzolib` from the archive.

Thanks.

**Comment by almarklein** [comment]
Closing this, as this is is about done. The remaining tasks are not critical. I don't think I'll do the config thing unless we find a real need for it.

**Comment by ghisvail** [comment]
:+1:
