### ISSUE TITLE
Ability to set shell configuration with relative path

### ISSUE THREAD

**Issue by nicolaje** [pyzo/pyzo#382]
I am using Pyzo for teaching purpose, and I am still interested in the editor + miniconda environment tightly set up.

Is there a way somehow to point Pyzo to a miniconda folder with a relative path from the Pyzo executable so I can distribute an archive containing Pyzo + a miniconda installation ready to use by students?

(By the way, I can't find the page where I downloaded Pyzo 4 a few weeks ago?)

**Comment by almarklein** [comment]
I understand your use-case, and I am sure there are others. One thing that comes to mind is to make Pyzo search for interpreters also in certain relaive paths (in addition to the standard locations). That way, if Pyzo is packed together with a miniconda installation, it should just work.

**Comment by nicolaje** [comment]
Great, I have found this setup (install-less python environment + IDE) is optimal for teaching.

It would be great that if a miniconda environment is present in the root folder, it is set as the default environment, to avoid manually set-up in such situation.

btw, kudo for moving Pyzo to Github!

**Comment by almarklein** [comment]
How do you intend to use this? You prepare a zipped directory containing miniconda+IDE, and then you copy to multiple machines. Do you view a copy as an installation, or do you want to be able to move things around? If the former, its ok for the IDE to simply set the path to the interpreter. In the latter case it would need to be smarter.

**Comment by nicolaje** [comment]
I prepare a zipped directory containing miniconda+IDE and copy it to multiple machines.

It works as a workspace for students, workspace that they might move around, move to an other machine (the miniconda exe+IDE are always side-to-side), hence the need for relative path.

**Comment by almarklein** [comment]
What is the use-case exactly? Why not let the students download Pyzo. And miniconda they could either download or use a version that you provide. Trying to understand the needs.

**Comment by nicolaje** [comment]
Most of the time I ship the miniconda install with additional tools/libraries that I built separately (OpenCV, MORSE robot simulator, robotics middlewares).

They can download and setup Pyzo themselves, it's just let's smooth.

I like to think of the zip file I provide as a self-contained application specific environment that can be carried on a USB key for example.

**Comment by almarklein** [comment]
Why not let users install miniconda and then have them do `conda install -c yourchannel openc, robot_sim, robot_middleware`?

In my experience, users of Pyzo previously were not always aware that they were using a conda environment. By having students install Pyzo and miniconda themselves, and perhaps have them conda-install a few packages, they know what they are using, and they know how they can get additional packages when they need them. Plus it saves you the time of preparing the zipped dir ;)

(On OSX you might want to have them install anaconda, because it has a graphical installer)

BTW: you may like that others are building opencv too: https://anaconda.org/menpo

**Comment by nicolaje** [comment]
"In my experience, users of Pyzo previously were not always aware that they were using a conda environment. "

Indeed, at the beginning I didn't see that myself ;)

I am not familiar with shipping my own conda packages, that could be a solution but from my experience command line + network in a university context often needs to configure a proxy (again, really no big deal, but irrelevant if you are teaching computer vision/robotics etc...).

For me the strength of Pyzo is more that it can be a "matlab looking" environment for Python that doesn't require installation.
In fact, if you google Pyzo+french keywords, you'll see many results because in France Python+Numpy is now being taught in "Preparatory schools". And what make Pyzo successful for them is not as much that it is a nice Python IDE than a ready-to-play Python scientific environment that can be used from any folder/USB stick/.... with any OS without admin privileges. This is a very unique feature in the scientific Python world (I think).
If you want to show people how easy it is do do matrix multiplication in Python/Numpy, but first they need to export http_proxy=... && conda instal X && set the path to the Python environment that won't work because they downloaded it in a network folder (happens everytime) etc... you maybe just lost some people that were interested in matrix multiplication but unfamiliar with other CS concepts.

I understand it is a mess to maintain the miniconda distribution+Pyzo yourself.
On the other hand, having Pyzo look for a conda install next to the executable + making it its default python environment so that other people can ship both in a Zip file is a simpler way to keep this "zero installation/configuration approach" if needed :)

**Comment by almarklein** [comment]
Ok, I will have a look at making Pyzo look for a conda env relative to the executable, and allow interpreter paths to be relative. I think that should do the trick.

I do not plan on building miniconda + pyzo distributables myself, but if someone wants to take up that task, I am happy to link to it from the Pyzo website.

**Comment by nicolaje** [comment]
Perfect, thanks!

**Comment by almarklein** [comment]
Implemented in https://github.com/pyzo/pyzo/commit/a64e8b7d9ae88f98f9fda5294262297ac8a84c19

**Comment by almarklein** [comment]
Also cc @rreilink

**Comment by almarklein** [comment]
@nicolaje BTW: there is also a settings folder in the binary version of Pyzo, which you can "enable" so that config gets stored there instead of in the machines appdata dir.
