### ISSUE TITLE
How to build pyzo from source ?

### ISSUE THREAD

**Issue by ysalmon** [pyzo/pyzo#386]
Hello,
I just downloaded the source for Pyzo. I cannot find how to build it, ie. how to produce the same binaries as the ones provided on the pyzo website.
There is a makefile for the documentation but I cannot find one for the program itself.

**Comment by almarklein** [comment]
Why would you want that? Note that Pyzo is pure Python, so you can just install and run it (as long as you have pyqt installed). Alternatively, you can use the precompiled binaries.

In case you really want to build the binaries yourself, you need cx_freeze and run the freeze script (I think it depends on PySide though).

**Comment by ysalmon** [comment]
Thanks, running Pyzo directly from source would be as convenient, but it depends on some pyzolib which seems to be missing from the repo and is also not referenced as a dependency. What is it ?

**Comment by almarklein** [comment]
you can just pip install that. Over time I plan on including that functionality in th pyzo package, so that dependency can be scrapped.

**Comment by ysalmon** [comment]
Thanks !
