### ISSUE TITLE
TypeError when closing the file browser

### ISSUE THREAD

**Issue by cottsay** [pyzo/pyzo#393]
There is a `TypeError` which has been popping up on Fedora machines for some time now [1].

It looks like an event object is getting passed into the timeout variable when the destroyed signal is triggered [2]. This leads to a type error when join(timeout) tries to interpret the event object as a numeric value [3].

The cause of the error is fairly straightforward, but I'm not sure exactly how you want it solved. Creating a wrapper function to connect to the signal which doesn't take an argument and calls the stop() method directly would probably do the trick.

Thanks,

--scott

[1] https://retrace.fedoraproject.org/faf/reports/538983/
[2] https://github.com/pyzo/pyzo/blob/master/pyzo/tools/pyzoFileBrowser/browser.py#L37
[3] https://github.com/pyzo/pyzo/blob/master/pyzo/tools/pyzoFileBrowser/proxies.py#L292

**Comment by almarklein** [comment]
Thanks for the report! I fixed it by making `timeout` a keyword-only argument.
