### ISSUE TITLE
wmclass not set

### ISSUE THREAD

**Issue by hmaarrfk** [pyzo/pyzo#396]
Hi,

wmclass isn't that. That makes it impossible to allow the desktop environments to follow the application.

I don't know how to fix this. But maybe you do?

Currently it is left blank.

Mark

**Comment by almarklein** [comment]
I'm not Linux expert, but from what I can find it should be a string that is unique to Pyzo, such that all Pyzo-windows are grouped in the task bar.

**Comment by hmaarrfk** [comment]
I think I was able to find something on stack exchange about it. I'll try
to experiment with it later today.

On Sun, May 8, 2016, 06:00 Almar Klein <notifications@github.com> wrote:

> I'm not Linux expert, but from what I can find it should be a string that
> is unique to Pyzo, such that all Pyzo-windows are grouped in the task bar.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pyzo/pyzo/issues/396#issuecomment-217716954>
>
-- 

Mark Harfouche

**Comment by hmaarrfk** [comment]
So I think I figured it out.

The name of the application is set by argv.

In the line 238, when you first initiate MyApp, apprently QApplication expects sys.argv.

It then picks the name of the app by choosing argv[0], or by the parameter '-name' 'app name'.

Instead of having an empty list as the argument of MyApp, []
You can either call MyApp(sys.argv) or MyApp('pyzo')


This seems to fix the issue for normal users, but if you call the program with sudo, it behaves strangely. I suspect it has something to do with some strange Qt permission.
It seems to be the same issue as what is reported here:
https://bugs.archlinux.org/task/42030?project=5

**Comment by hmaarrfk** [comment]
Maybe @ghisvail has an idea?
