### ISSUE TITLE
Can not run pip from inside Pyzo

### ISSUE THREAD

**Issue by DiegoQueiroz** [pyzo/pyzo#400]
The problem is described into https://github.com/pypa/pip/issues/3771

I think this is not an issue of Pyzo itself, but it affects it, so I am reporting here too.

**Comment by DiegoQueiroz** [comment]
Actually, I was wrong. This appear to be a problem with Pyzo/IEP implementation.

It appear to not be implementing `file.isatty()` method, and it is required for a class pretending to be a file.

**Comment by almarklein** [comment]
Thanks for the report. You are correct. Pip since some time assumes a more "real" stdout than Pyzo provides. It has already been [fixed](https://github.com/pyzo/pyzo/commit/b809cb04bed962bc511a95e6713b0f8806d0f772) though. Maybe its time for a new relase soon.

**Comment by DiegoQueiroz** [comment]
Great! :)
