### ISSUE TITLE
Some UI texts still need translation

### ISSUE THREAD

**Issue by yltang52** [pyzo/pyzo#402]
The following quoted texts have not been translated. Any plan to do it?

1. File -> Open
    The title of the dialog box: "Select one or more files to open"
   
2. File -> Save/Save as/Save all
    The title of the dialog box: "Select the file to save to"

3. Edit -> Go to line
    The text in the dialog box: "Go to line"

4. Settings -> Edit syntax styles ...
    All texts in the dialog box

5. Settings -> Advanced settings
    All texts in the dialog box
    
6. Shell -> Create new Python environment...
    All texts in the dialog box

7. Shell
    Last menu item: "Create shell 1: (Python)"

8. Execute -> Run file as script
    Texts in the dialog box: "Can only run scripts that are in the file system"

9. Execute -> Run main file as script
    Texts in the dialog box: "Could not run main file (as script): The is no main file selected"
    (EDIT: "The" may be a typo of "There")

10. Tools
    7 menu items:
    "File browser"
    "History viewer"
    "Interactive help"
    "Logger"
    "Source structure"
    "Web browser"
    "Workspace"

11. Help
    Third menu item
    "Pyzo wizard", "Get started quickly"

**Comment by almarklein** [comment]
What language?

**Comment by yltang52** [comment]
zh_TW

------
yltang52@gmail.com
2016年6月5日 上午4:27於 "Almar Klein" <notifications@github.com>寫道：

**Comment by almarklein** [comment]
ping @pyzo/translators

**Comment by yltang52** [comment]
So, we are not going to deal with this for now, right?

**Comment by hseara** [comment]
Hi Almar,
if you provide me with instructions how to do the translations I can do
them.
In the past you use to send us a file.
Thanks,
Hector

On 27 June 2016 at 16:00, yltang <notifications@github.com> wrote:

> So, we are not going to deal with this for now, right?
>
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pyzo/pyzo/issues/402#issuecomment-228753768>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AB7Gd6wfdn2AqB6fxzXFT5oFwGCaMiGoks5qP9drgaJpZM4ItLi5>
> .
>



-- 
Hector Martínez-Seara Monné
mail: hseara@gmail.com
Tel: +420775096757
Tel: +358442709253

**Comment by almarklein** [comment]
Oh, I assumed that these were done in #401, are they not?

**Comment by almarklein** [comment]
@hector the preferred workflow is to use pull requests https://github.com/pyzo/pyzo/wiki/Translations.

**Comment by almarklein** [comment]
I meant @hseara, sorry @hector

**Comment by yltang52** [comment]
I have no idea how to do it. Do I actually have to search for those untranslated texts in the code and add <message> items in the .tr file?

**Comment by almarklein** [comment]
Ah, you meant these items are not "translatable"? As in, not listed in the .tr file? In that case the source code needs to be changed to make use of the `translate()` function. The tool that generates/updates the .tr file examines the source code for occurrences of `translate()`.

**Comment by yltang52** [comment]
Yes, they are not in the `.tr` file.

**Comment by almarklein** [comment]
Right, I am aware that there are quite a few untranstlatable strings, but I did not know there were untranslatable menu items. Easiest would be to wrap these strings in a `translate()` function and make a PR. Then I can update the .tr file, so the that the translators can add the translations.

**Comment by yltang52** [comment]
I have never done this before, but I would give it a try. This is what I am going to do:

For example, mark the "Select one or more files to open" string:

1. Search for the string: line 1075 of `pyzo/core/editorTabs.py`
    `msg = "Select one or more files to open"`

2. Wrap it by function `translate()`: 
    `msg = translate("Select one or more files to open")`

Is that correct?

BTW, what is PR and how to make a PR?

**Comment by almarklein** [comment]
That is almost correct, the translate function needs two argument, where the first is the "context", as e.g. [here](https://github.com/pyzo/pyzo/blob/ff36f6452a82da7e280f3f38530d3a3fc273a160/pyzo/tools/pyzoFileBrowser/importwizard.py#L68). In the case you mentioned it would be e.g. `msg = translate("editor", Select one or more files to open")`.

A PR is a pull request. A guide is e.g. [here](https://yangsu.github.io/pull-request-tutorial/). The process in short:

* You fork the Pyzo repo so you have your own version in `https://github.com/yltang52/pyzo`. 
* You clone your forked repo to your local machine.
* Make changes
* Commit changes (preferably in a separate branch, but does not need to be per see)
* Push changes to your forked repo.
* Click on the "create pull request" button on GitHub. 
* Others (and I) can then verify the changes, requesting more changes if needed.
* When all is ok, I press the "merge" button and your code is in the Pyzo codebase.

**Comment by almarklein** [comment]
BTW: occasional and straightforward changes can even be done directly by clicking edit in the code on `http://github.com/pyzo/pyzo`.

**Comment by yltang52** [comment]
Got it.
