### ISSUE TITLE
Native virtualenv support for shell configurations

### ISSUE THREAD

**Issue by jpauwels** [pyzo/pyzo#403]
It would be nice if Pyzo would support virtualenv. I can recreate some functionality by using the Python binary inside the virtualenv and modifying the pythonpath, but it would be better if the corresponding activate script was sourced.

**Comment by almarklein** [comment]
I don't have a lot of experience using virtual env. If you have a good idea how this can be made to work, I'd welcome a pull request :)

**Comment by Sekuraz** [comment]
The activate script only sets environment variables, but i have no idea how to pass them to the shell process in pyzo.

**Comment by almarklein** [comment]
Each shell config has a field for environment variables. E.g. in the logger shell you can type `pyzo.config.shellConfigs2[0].environ`. The corresponding code for the shell config dialog is [here](https://github.com/pyzo/pyzo/blob/master/pyzo/core/shellInfoDialog.py#L442-L466); it's a newline-separated list of assignments.

**Comment by lcerman** [comment]
I just started using virtualenv and hit the similar problem. To my understanding, the virtualenv `activate` script just sets:

```bash
VIRTUAL_ENV="/path/to/venv"
export VIRTUAL_ENV

PATH="$VIRTUAL_ENV/bin:$PATH"
export PATH
```

(in fact it does more fancy stuff to unset those variables when deactivating the env, which is not important here). Bottomline: I don't know what the VIRTUAL_ENV does a if it is really necessary... does anyone know if we need it?

So to mimic the same in Pyzo, all is needed is to set PATH to contain venv's bin directory. This can be done by filling the *environ* field of Shell config dialog. Then the *exe* filed in the shell config can be then just `python` and it will exec the correct python from within the virtual env.

@jpauwels entering directly the full path of the python  binary from withing the venv directly into the *exe* field without setting the PATH is cumbersome. E.g., if some of your libraries inside the venv launches another python script using `/usr/bin/env python`, which is more or less the normal way to do it, then it will actually launch the global python not the one in the venv.

@almarklein to allow extending the PATH variable from withing the *environ* field, I created #469, so one can fill in:

```
PATH=/path/to/venv/bin:$PATH
```

If other agree this is the correct solution for using virtualenv from within Pyzo I would be for noting this in the official documentation so it is easier do discover it for s user without the deeper knowledge of virtualenv internals.

**Comment by lcerman** [comment]
Sill some troubles there, need to do more testing, sorry. Let you know if I found a solution.

**Comment by lcerman** [comment]
OK everything is fine, it just showed that the `VIRTUAL_ENV` must be set too to have a proper virtualenv behavior. In my case not having it set broke the vext.pyqt4 package.

**Comment by almarklein** [comment]
I agree that it makes sense to make this the recommended way to do virtual envs in Pyzo. I will add a note in the docs / website.

**Comment by almarklein** [comment]
Added note in FAQ on website.

**Comment by lcerman** [comment]
Nice. I would also recommend setting VIRTUAL_ENV in the FAQ:

```
VIRTUAL_ENV=/path/to/venv
```

Had some trouble not doing so as noted above.

**Comment by almarklein** [comment]
ah, I'll add it right now

**Comment by HROMANO** [comment]
The FAQ should mention a difference between windows and linux configuration:

```
VIRTUAL_ENV="C:\path\to\venv"
PATH="C:\path\to\venv\Scripts";$PATH 
```

The important point is the ";" as path separator for windows instead of ":". Something I forgot during last reinstall and gave me headaches.
