### ISSUE TITLE
Opening non-.py Files through the File Browser

### ISSUE THREAD

**Issue by fangerya** [pyzo/pyzo#404]
When I open up a .pdf-file in the file browser, pyzo tries to display it and shows me some cryptic characters instead of opening the file through the standard pdf reader, as would be expected.

**Comment by almarklein** [comment]
Well, Pyzo assumes that you want to open the file in Pyzo if you click it. E.g. a .txt file would open in Pyzo, and not in notepad/gedit/etc. To open with the OS prefered program, use the right mouse button and select "open outside Pyzo".

Possibly, Pyzo could be smarter and open files it sure knows are not binary outside of Pyzo. Though it would not be trivial, e.g. some pdf formats can be pretty well read with a text editor.

**Comment by fangerya** [comment]
I see your point but in fact Pyzo opens a terminal window when selecting "open outside Pyzo" for said PDF.

**Comment by almarklein** [comment]
Oh. That would probably be a bug. What OS are you on?

**Comment by fangerya** [comment]
Windows 10.

**Comment by almarklein** [comment]
Haha, I was expecting an esoteric flavor of Linux :)

I think I know what's wrong though. Is there a space in the name of the document?

**Comment by fangerya** [comment]
Indeed! It's not in the filename itself but in the path (i.e. the folder name contains a space). Thank you!

**Comment by almarklein** [comment]
Thanks for reporting. It should now be fixed.
