### ISSUE TITLE
Pyzo UI has random stripes

### ISSUE THREAD

**Issue by yltang52** [pyzo/pyzo#413]
Ubuntu 16.04 LTS, Pyzo 4.2.1 (Binary)

There are many random stripes on Pyzo's UI: menu, pull-down menu, file browsers, etc. The attached is the file browser:

![2016-07-22 22-22-52](https://cloud.githubusercontent.com/assets/6300280/17060207/7c93206e-505b-11e6-9803-344193f3812e.png)

**Comment by almarklein** [comment]
I am pretty sure this is a duplicate of #414
