### ISSUE TITLE
Ugly GUI font after upgrading from 4.1.1 to 4.2.1

### ISSUE THREAD

**Issue by lcerman** [pyzo/pyzo#414]
I have just upgraded Pyzo from version 4.1.1 to 4.2.1 and I have several GUI issues:

1. [major] The GUI font (menus, filebrowser, tab-titles, etc...) is fat and blurry the font in editor and shell is OK. Previous version has fonts thin and crispy. See the screenshot bellow of the new (top) and the previous (bottom) version running side by side. I would prefer rollback to previous version fonts rendering.

2. [major] Tooltip on editor tabs has not rendered text, I see only the empty balloon. (also visible in the screenshot.

3. [minor] Theme color changed from brown-gray into neutral gray. This is not a big issue though its kind of surprise.

Forgot to mention I am on Ubuntu 14.04 64-bit...

![pyzo](https://cloud.githubusercontent.com/assets/20700132/17207679/ef2ddcf0-54b5-11e6-8928-4d5f07a68fd9.png)

**Comment by almarklein** [comment]
Yeah, there is an issue with the fonts with the Linux binaries. My advice is to `conda install pyqt`, `pip install pyzolib pyzo` and then run `python -m pyzo`.

**Comment by almarklein** [comment]
(until this is resolved)

**Comment by lcerman** [comment]
How long you expect it takes that to be resolved? I prefer to wait for the official binaries...

By the way, is that `conda install pyqt` necessary if we already have PyQt4 installed in our systems? (we install it for our project from the Ubuntu repositories using `sudo apt-get install python3-pyqt4` and I don't won't to mess something by installing other version using conda, and also we don't use conda, just pip3 for things that are not in Ubuntu repos...)

**Comment by almarklein** [comment]
Right, if you're using system python, by all means uses `python3-pyqt4`. Pyzo only depends on pyqt4 and pyzolib (and the latter dependency will be removed soon).

**Comment by almarklein** [comment]
I tried several VM's including
* Ubuntu 16.04: yes. fat fonts, and takes ages to start (as #423 reports)
* Mint Cinnamon 17.1: all seems fine
* Kubuntu 14.04: font looks slim, but very bit weird, not in line with the rest.

**Comment by almarklein** [comment]
Building Qt on one machine and deploying on another while have things look good is very much non-trivial.

I added a note to the website on how to run Pyzo the Linux way. Let's hope things work better with an update to Qt. If not, that'll be the best solution.

**Comment by lcerman** [comment]
Dear Almar, the "Linux way" guide does not work for me. First, I get some weird error `Could not install pyzo.appdata.xml` during install:

```
$ sudo pip3 install pyzo --upgrade
Downloading/unpacking pyzo
  Downloading pyzo-4.2.1.zip (1.7MB): 1.7MB downloaded
  Running setup.py (path:/tmp/pip_build_root/pyzo/setup.py) egg_info for package pyzo
    
Installing collected packages: pyzo
  Running setup.py install for pyzo
    
    Installing pyzo script to /usr/local/bin
    Could not install pyzo.appdata.xml: [Errno 2] No such file or directory: '/tmp/pip_build_root/pyzo/pyzo.appdata.xml'
Successfully installed pyzo
Cleaning up...
```

However, it claimed successful installation, so I tried to run it. Got another error:

```
$ pyzo
Traceback (most recent call last):
  File "/usr/local/bin/pyzo", line 9, in <module>
    load_entry_point('pyzo==4.2.1', 'console_scripts', 'pyzo')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/pyzo/__init__.py", line 57, in <module>
    import pyzolib
ImportError: No module named 'pyzolib'
```

**Comment by umbe1987** [comment]
sudo pip3 install pyzolib pyzo

**Comment by lcerman** [comment]
OK, that helped to start pyzo, the fonts look more normal (however, different than with previous pyzo version), in addition menu has moved from the Pyzo window to the Ubuntu system menu bar at the top of the screen, which is maybe not an error, but more "Unitity conforming" behaviour... I just need to get used to it...

But the first error remained `Could not install pyzo.appdata.xml: [Errno 2] No such file or directory: '/tmp/pip_build_root/pyzo/pyzo.appdata.xml'`, is there some file missing in the pyzo package?

**Comment by almarklein** [comment]
Yeah, running Pyzo in this way should make everything look more native, which is generally considered "better" :)

Not sure about that error related to `pyzo.appdata.xml`. The file exists and is mentioned in the `MANIFEST.in`. And I verified that its present in the source dist ...

**Comment by almarklein** [comment]
Releasing new binaries today or tomorrow. It fixes this issue and several others. Switching to PyQt5 was not what fixed it, but I looked into it and now ship a `fonts.conf` that is used. It probably means that the font is not exactly native, but at least it should look ok.

**Comment by lcerman** [comment]
Thanks a lot for your care, I will test it and let you know.

Currently I am using pip3 distribution as you suggested abowe and I am quite happy with that. Will that be also updated, so that I can uninstall the pyzolib?

**Comment by almarklein** [comment]
Yes, I also uploaded to `pypi`.

**Comment by lcerman** [comment]
Dear Almar, I have done some tests, the pip3 distribution works well (have uninstalled pyzolib in advance), fonts look good.

The binary distribution still has problems with fonts. Another problem appeared when I tried the binary distribution on our server, which I access through ssh:

```
$ ./pyzo
Started our command server
process 21008: D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open "/etc/machine-id": No such file or directory
See the manual page for dbus-uuidgen to correct this issue.
  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)
```

Intalling usin `pip3 install pyzo --upgrade --user` worked smooth and the problem with D-Bus dissapeared. So its releated to that binary package not to the Pyzo itself.

I am quite happy with the pip installation and do not need the binary package, it is easier to just upgrade over pip instead of downloading tar file, unpacking, updating path... However, if you like me to perform some further testing let me know.

**Comment by almarklein** [comment]
@Icerman thanks for the report. I hope this is a problem specific to your kind of server :)  As long as this appears to be the case, I would not waste too much time on it. 

Building binaries that work everywhere is hard :(

**Comment by lcerman** [comment]
> @Icerman thanks for the report. I hope this is a problem specific to your kind of server :) As long as this appears to be the case, I would not waste too much time on it. 

It's ordinary Ubuntu 14.04, same environment as we use on our personal computers, just run virtualized on a powerful machine, which is accessed remotely... Bus as I said, I like the pip distribution, so personally I do not require the binary package...

**Comment by almarklein** [comment]
mmm, might be related to not having a real screen that breaks Qt or something.
