### ISSUE TITLE
Stepping in debugger scrolls code view after each step

### ISSUE THREAD

**Issue by lcerman** [pyzo/pyzo#415]
Stepping in the debugger scrolls the code view (centers the current code line) after each step even in cases when the current line remain in the view after performing the step. Scrolling the view with each step is distracting it should scroll (center the view) only when the step leads out of the view / into another file (or at most when its getting close to the end of the view, so there remains some context in the view).

**Comment by almarklein** [comment]
The corresponding code is here: https://github.com/pyzo/pyzo/blob/master/pyzo/codeeditor/base.py#L645-L665

It should probably be possible to rewrite this to see whether the line is currently visible.

**Comment by lcerman** [comment]
Almar, thanks for the hint and the quick reaction. I have changed the last line of the function `gotoBlock` from

```python
        self.centerCursor()
```
to 

```python
        margin = self.height() * 0.2    # 20% margin on both sides of the window
        cursorRect = self.cursorRect(cursor)
        if cursorRect.top() < margin or cursorRect.bottom() + margin > self.height():
            self.centerCursor()
```

It works smoothly, so hope there is not some unexpected issue with that. Please, consider integrating this into the official release so I do not need to maintain this patch while upgrading to future releases. The constant 0.2 could be user-configurable, by setting it to any value above 0.5 one would get the original behaviour, i.e., centering upon every move.

**Comment by almarklein** [comment]
Great! I am sure interested in integrating this. The fastest way for that to happen is if you could make a pull request. Otherwise I can do it later, when I find time to do some Pyzo work.

**Comment by lcerman** [comment]
Almar, I have done the pull request (hope did it right, was doing it for first time on GitHub), its here: https://github.com/pyzo/pyzo/pull/417
