### ISSUE TITLE
Compatibility with PyQt5

### ISSUE THREAD

**Issue by ghisvail** [pyzo/pyzo#421]
The Python ecosystem is slowly but surely transitioning to Qt5. Are there any plans to make `pyzo` compatible with PyQt5 (and perhaps PySide2 later) in the future? Perhaps using a [shim layer](https://github.com/spyder-ide/qtpy) like the spyder guys did?

**Comment by Nodd** [comment]
For reference, git-cola used qtpy for the transition, here is the relevant issue if you're interested in the discussion: https://github.com/git-cola/git-cola/issues/232
(disclaimer: I'm a qtpy/spyder dev).

**Comment by almarklein** [comment]
I think that makes sense. Now to find the time to do it :)

**Comment by ghisvail** [comment]
How much do you reckon this would require?

**Comment by almarklein** [comment]
I find it hard to guess. I recon that it won't be too much, since Pyzo uses the new-style PyQt already. Though I don't know what problems will come up. Possibly using qtpy might help.

**Comment by ghisvail** [comment]
Is `pyzo.util.qt` the only place to modify to make `pyzo` support `qtpy` or `pyqt5` ?

**Comment by almarklein** [comment]
yes, all code in Pyzo eventually loads it from that module.

**Comment by almarklein** [comment]
About done, except testing on PySide / PyQt5: #433

**Comment by ghisvail** [comment]
Do you want me to try it out with PyQt5? SincePyQt5 is packaged as a wheel on PyPI, it should be quite straightforward.

Overall, what's left to be done for the next stable release to happen?

**Comment by almarklein** [comment]
> what's left to be done for the next stable release to happen?

I want to have a look at the binaries for Linux; whether updating Qt, or using PyQt5 fixes these nasty issues we're having.

I you want to try out PyQt5 with this branch that would be helpful, thanks!

**Comment by ghisvail** [comment]
> I you want to try out PyQt5 with this branch that would be helpful, thanks!

I'll spin up a venv with PyQt5 and the dev snapshot and program in it for the day. I'll report anything unusual.

**Comment by ghisvail** [comment]
QStringListModel in QtCore not QtWidgets.

[QStringListModel.diff.txt](https://github.com/pyzo/pyzo/files/486981/QStringListModel.diff.txt)

**Comment by ghisvail** [comment]
Here is the full diff I had to apply to allow Pyzo to **load** with PyQt5.

[load_with_pyqt5.diff.txt](https://github.com/pyzo/pyzo/files/487005/load_with_pyqt5.diff.txt)

Hope this helps.

**Comment by ghisvail** [comment]
And a little screenshot!

![pyzo_with_pyqt5](https://cloud.githubusercontent.com/assets/1964655/18744970/3a05cf7a-80b8-11e6-843c-099c187be5fd.png)

**Comment by almarklein** [comment]
Awesome! Thanks for that @ghisvail !

**Comment by ghisvail** [comment]
Nothing bad to report. Shall I turn the .diff into a PR?

**Comment by almarklein** [comment]
> Shall I turn the .diff into a PR?

Please :D
