### ISSUE TITLE
Help system broken in 4.2.1

### ISSUE THREAD

**Issue by ysalmon** [pyzo/pyzo#422]
Python's help system seems broken : typing ```help([])``` for example in the IEP console gives no answer (the call does not terminate).
This is with miniconda and both with and without IPython activated.

Running the same python3 interpreter in a system shell, I can do ```help([])``` with no problem.

**Comment by almarklein** [comment]
This was on Linux with the Pyzo binaries right?

**Comment by ysalmon** [comment]
Yes, and also with the latest git version (which, for a reason I do not understand, does not show parenthesis colouring in the console and also does not show tooltips despite the latest commit).

**Comment by ysalmon** [comment]
This also happens with the 32bit linux binaries, if that helps.

**Comment by ysalmon** [comment]
So, I went back to v4.1 and cherry-picked commits pertaining to brace matching and the tooltips that were broken. This alternative v4.1.1 has a working ```help``` (tested the binary version by crudely replacing /source/pyzo by my git working tree).
It is available on my fork as branch descartes https://github.com/ysalmon/pyzo/tree/descartes

**Comment by almarklein** [comment]
Sorry, I am confused. Are you saying that you know what commits introduced the bug, or that you now have a version that *does not* have it?

**Comment by ysalmon** [comment]
I have a version that does not have the bug. Therefore I suspect that it was introduced in one of the commits that I did not cherry-pick.

**Comment by almarklein** [comment]
It would help me a lot if you can point me to the commits that seemed to have introduced the bug.

**Comment by EmericT** [comment]
Just installed pyzo (via pip install pyzo pyzolib --upgrade) on ubuntu 16.04, same behavior when invoking help. 

Some more details, though : 
 - using help() all alone works perfectly. 
 - it also works fine when using python2.7 (both with iPython and without)

Pyzo version: 4.3.1 (source)
Platform: linux
Python version: 3.5.2
Qt version: 4.8.7
PyQt4 (API v2) version: 4.11.4

**Comment by almarklein** [comment]
Thanks for looking into it. Will look into it, but am rather swamped right now.

**Comment by almarklein** [comment]
Hard to tell what introduced it, since it seemed to be due to how Python's doc system selects a way to do help "pages". But found a solution nonetheless.
