### ISSUE TITLE
Tab (\T) not appearing correctly in Shell Output when Zoomed above 100%

### ISSUE THREAD

**Issue by scottie-uk** [pyzo/pyzo#424]
I am using Pyzo to teach students their first programming language and plan to use Pyzo in lectures. 
 Consequently, for students at the back to see the text output I have to work with the text Zoomed In.

On my Windows 10 machine, I was experimenting with \t in print lines and noticed that when zoomed in the \t seems equivalent to a space or at  some zoom zoom levels worse i.e. no space at all.   This may become quite confusing for my audience as when demonstrating the tab. Currently, I have to switch to the command line to show tab behaving properly. Below is an example for Python 3 which illustrates this problem:

#CODE
mk1 = "Harpo"
mk2 = "Groucho"
mk3 = "Chico"
mk4 = "Zeppo"

marksBrothers = mk1 + "\t" + mk2 + "\t" + mk3 + "\t" + mk4
print(marksBrothers)

print(mk1,mk2,mk3, mk4, sep="\t");

##END OF CODE

Also, What would really be useful instead of zoom controls would be the ability to set the font and size of the code and shell independently via a view menu or tool bar option.  

Thank you for taking the time to read this.

**Comment by ysalmon** [comment]
Yes, this is strange, it seems that the tabulation positions are fixed independently of the text zoom, or are not scaling in the same way. So when the text becomes bigger, it spans across more tab zones and the text following ```\t``` is pushed to the right. But just before this happens, it is very near.

Out of curiosity, as I also happen to use Python and Pyzo to teach basic informatics : why are you doing this thing with ```\t``` ? I do not ; am I missing something ?

If the point is not to explain ```\t```, you might achieve a good looking output with ```ljust```, eg.
```python
def pretty_print(L) :
   """Pretty print a list of strings, with regular spacing."""
   maxlength = max(len(x) for x in L)
   for x in L :
      print(x.ljust(maxlength), end=" ")
   print()
```

If your point is just to show the flexibility of ```print``` and ```sep```, you could just use two spaces or a comma.

**Comment by scottie-uk** [comment]
Yann,
                My point was to demonstrate the \t and \n characters as it applies to print and have the students for their first task do some print formatting using Print. I just noticed when I was presenting this zoomed in, that the \t did not look right. So switched to running the code on the command line so I could get the desired and expected output. Yes, I was showing the flexibility of print , sep, and end.

              Andrew Scott.


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dr. Andrew Scott
Assistant Professor,
Dept. Mathematics and Computer Science,
ST439
Western Carolina University
Tel: 828-227-3950
Web: http://agora.cs.wcu.edu/~ascott
Progranimate Project: http://progranimate.com
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by almarklein** [comment]
Hi @scottie-uk, thanks for taking the time to report this. Unfortunately, I do not know what to do with this; it is probably a bug (or feature?) of Qt.
