### ISSUE TITLE
Shell workspace contains string variable called "name" on startup

### ISSUE THREAD

**Issue by TARehman** [pyzo/pyzo#425]
I noticed today that starting a Pyzo shell results in a workspace which contains a variable called `name` upon each startup. It was bugging me, so I investigated a little bit.

As near as I can tell, it seems to come from the loop [here](https://github.com/pyzo/pyzo/blob/0864d621804364528a77b400edcdd68e4d3e202d/pyzo/pyzokernel/start.py#L137
), which is run during shell startup. If you add `del name` at the end of the loop, the workspace no longer contains `name` on startup.

It seems like you could move the cleanup section taking place at line 131 below the loop, and then add `name` to those deletions, but I may be misunderstanding another function that `name` has in the system.

**Comment by almarklein** [comment]
Thanks!
