### ISSUE TITLE
Create new environment partial failure

### ISSUE THREAD

**Issue by fstengel** [pyzo/pyzo#426]
When creating a new environment and checking the ``also install scientific packages'', the installation fails for the afore mentinned packages. What happens is that a python 3.5 environment is created and then the installer, using conda, goes on to try installing visvis and imageio. That fails since both packages seem to be limited to python 3.4

Basically one would either have to use a miniconda for python 3.4 (haven't found it) or remove/update the offending packages

**Comment by fstengel** [comment]
Oops, the title should be "Create..." and not "Creante..."

**Comment by almarklein** [comment]
I guess I should put some more effort soon into putting these up on conda-forge ...

**Comment by almarklein** [comment]
Mmm, I think this is with an older version of Pyzo. We don't have the option to install a new env from inside the GUI anymore. Users should manage their conda envs by themselves.

**Comment by fstengel** [comment]
Oh. I just looked at the current code, it seems the relevant menu item is still available (line 1008-9 in pyzo/core/menu.py) and the function it calls creates the dialog box that creates the issue (Installer in pyzo.util.bootstrapconda). I just tested again with 4.2.1...

**Comment by almarklein** [comment]
You're right ... will have a look then.
