### ISSUE TITLE
Wrong French translation

### ISSUE THREAD

**Issue by ysalmon** [pyzo/pyzo#427]
In the Run menu, the first entry (with purple arrow) states "Exécuter le script" and the second one "Exécuter le script principal" ; the 6th and 7th entries (green arrows) are "Exécuter le fichier" and "Exécuter le fichier principal".

Should it not be the converse ? Because it is the two first entries that require the program to be saved in a file (fichier in French), while the 6th and 7th do not.

This is very misleading for beginners who do not understand yet what a file is and how what is typed and displayed in the code editor is not necessarily the same as what is stored on disk.

**Comment by fstengel** [comment]
Another one:

In the help menu/About pyzo, the translation is "À propose de Pyzo", it should be "À propos de pyzo" (there is an extra "e")

**Comment by snarkturne** [comment]
You are right - I will correct this for the next release.

Vous avez tout à fait raison. Je corrige tout ça pour la prochaine Release. Que pensez-vous du terme d'onglet pour différencier le fichier de ce qui est visible dans l'éditeur ?

**Comment by fstengel** [comment]
So one would have on the 6th item of the run menu: "Executer l'onglet"? Sounds interesting. It would differetiate quite nicely and refer to the fact that it is what is in the panel that is executed not a file.

**Comment by ysalmon** [comment]
Oui, je pense que ça serait bien plus clair.
