### ISSUE TITLE
Numeric sorting in workspace

### ISSUE THREAD

**Issue by fstengel** [pyzo/pyzo#428]
This is purely cosmetic, still...

Imagine I create a variable with

a = [1, 2, 15]

and examine it using the workspace tool. If I sort using the repr (or name) column, the order is an alphanumeric order that is 1, 15 , 2 which is a bit annoying when sorting items that are supposed to be numbers. The thing is even more annoying when displaying lists/tuples with more than 10 elements: sorting using the name column places item 10 between items 1 and 2....

I can understand the choice made: it is far simpler to sort the representatives as strings. However, especially for lists/tuples, it would be nice that when one sorts on the name column, one obtains a numerical sort so that item number 10 comes after item number 9 and not between items number 1 and 2...

**Comment by almarklein** [comment]
Done!
