### ISSUE TITLE
Allow changing title of tab

### ISSUE THREAD

**Issue by ysalmon** [pyzo/pyzo#432]
I recently discovered in the contextual menu of tabs an option labelled "Rename". I thought it was a great idea, since when writing packages, files tend to be named `__init__.py` quite often.

However, it seems to be an option to rename the file on disk (which is also a nice feature), not just the title.

Would it not be great to be able to add some text to the tab titles ? It could be prepended to the actual file name.

**Comment by almarklein** [comment]
You have not convinced me yet :)  I fear that it can also be confusing to set a title that does not match the file name. What kind of use-case do you have in mind? I can think of a few (but am not sure if its worth the effort):

* shorten very long file names
* make very short names more descriptive
* when you have two files with the same name open (this is the strongest case IMO, though I would rather fix it by (automatically) also showing the part of the path that differs)

**Comment by ysalmon** [comment]
The third case is the one I am talking about. Furthermore, giving the user a possibility to alter the tab title would not change the default behaviour, so it would then up to the user to give intelligent titles, if this person decides to use custom titles.
Here is a part of my tabs at the moment ; not very practical.
![capture d ecran_2016-09-07_12-18-02](https://cloud.githubusercontent.com/assets/536850/18308551/4b4c8db0-74f5-11e6-99e9-8ef46f3acaf2.png)

**Comment by almarklein** [comment]
To what extent do you think would this be fixed if Pyzo would (automatically) also show the part of the path that is different? something like `../foo/../__init__.py` and `../bar/../__init__.py`. It results in longer names and would probably not be the same names if you'd manually set the title, but at least its automatic; I suspect that few people would use the manual method. What do you think?

**Comment by ysalmon** [comment]
Yes, this would be a great thing.

**Comment by almarklein** [comment]
Woozah!
