### ISSUE TITLE
Configure `shell` to python in a virtual environment

### ISSUE THREAD

**Issue by yltang52** [pyzo/pyzo#435]
Usually, I install python packages in virtual environments for different projects, not in the OS. So, is it possible (maybe in the future?)  to configure the `shell` to python in a virtual environment?

**Comment by almarklein** [comment]
Right now you can set the EXE of the interpreter to whatever you want. I don't know much about virtual envs (I use conda envs myself), but I imagine there is a special exe, or a global exe with some flags that should be run?

**Comment by yltang52** [comment]
OK, thanks.

**Comment by almarklein** [comment]
To be clear, if Pyzo needs some changes to make it work, I am open to get these changes in.

**Comment by almarklein** [comment]
This looks like a duplicate of #403. See http://www.pyzo.org/faq.html#how-can-i-use-pyzo-with-a-virtual-env

I'm closing this. Feel free to re-open if I misjudged.
