### ISSUE TITLE
Workspace filters request

### ISSUE THREAD

**Issue by fstengel** [pyzo/pyzo#439]
Could one add a filter that filters out methods for an object? The idea is that for some classes (a tkinter widget is a nice example) one has to contend with hundreds (around 200 for tkinter.Label) of methods when exploring an object and finding the variable/property one looks for can be rather time consuming

One possible way could be to extend the scope of the "hide function" filter. Another way would be to be able to arbitrarily extend the "hide xxx" items in the filter menu with a specific item such as "hide other" or "add exclusion"...

**Comment by almarklein** [comment]
I can see how a way to add arbitrary filters can be useful, though maybe that should be in the form of a search field in which you can also write exclusions.

The low hanging fruit is making "hide functions" also hide methods, which is what it should do anyway, IMO.

Do you care for looking into this and submit a PR? The relevant code should either be in `tools/pyzoWorkspace.py` or `pyzokernel/introspection.py` (I think the filtering occurs in the former).

**Comment by almarklein** [comment]
Some time ago I made "hide function" also hide methods, and I just made it hide buildin functions (e.g. methods of str) too.

Closing this now as I think the main issue has been resolved. Please reopen if you don't agree :)
