### ISSUE TITLE
Consider not vendoring QtPy 

### ISSUE THREAD

**Issue by ghisvail** [pyzo/pyzo#440]
From a packaging perspective, it would be desirable to rely on the system packaged `QtPy` rather than a vendored version. `QtPy` is available through PyPI and does not pull a preferred Qt backend, so I can't see a reason for vendoring rather than depending on it.

**Comment by almarklein** [comment]
Pyzo only needs a few of its modules (QtGui, QtCore, QtWidgets) and the code is small so I thought vendoring the part of qtpy that Pyzo needs seemed easier than adding a dependency. Anyway, for now vendoring is needed because there was a [bug](https://github.com/spyder-ide/qtpy/pull/74) in qtpy that prevented Pyzo from running on both PyQt4 and PyQt5.

**Comment by ghisvail** [comment]
I understand. The solution I would propose is to make the `util.qt` module attempt an import of an installed version of `QtPy` and, if unsuccessful, fall back to the vendored code. All of this should be achievable within `util.qt.__init__.py` without having to touch anything else, I believe.

Meanwhile, I'll ask the `QtPy` dev team to release a new stable version with the critical fix you require.

**Comment by almarklein** [comment]
hehe, I just said in my PR that I was i no hurry :P

**Comment by ghisvail** [comment]
Well now you have guessed that I did not read your PR first ^^. Do you know why it has yet to be merged?

**Comment by LocutusOfBorg** [comment]
we can always patch the Debian packaging while waiting for the new release... :)

**Comment by ghisvail** [comment]
@LocutusOfBorg I am not super comfortable with including unmerged patches (been burnt in the past with this). Considering the scope of `qtpy`, the more pragmatic approach is to allow the vendoring to take place, at least temporarily until this issue is resolved. It is not as sensitive as vendoring a copy of OpenSSL for instance ^^.

By the way Gianfranco, I pushed an update to the new upstream release on the [packaging repository](https://anonscm.debian.org/cgit/debian-science/packages/pyzo.git). Could you sponsor it please, thanks :)

**Comment by LocutusOfBorg** [comment]
in deferred/5 :)

**Comment by LocutusOfBorg** [comment]
I agree with your qtpy point ;)

**Comment by ghisvail** [comment]
> in deferred/5 :)

Too bad, I was hoping to get it quicker in `unstable` so I can start requesting the removal of `pyzolib` from the archive.

**Comment by LocutusOfBorg** [comment]
going in now
