### ISSUE TITLE
Translation not finished yet

### ISSUE THREAD

**Issue by yltang52** [pyzo/pyzo#445]
The following quoted UI texts are still not translated, although most of them already have "translate()" added in the code.

Shell --> "Create shell"
Module: core/menu.py
Line: 1023

Execute --> "Execute selection and advance"
Module: (not found)

Tool --> "File browser"
Module: (not found)

Tool --> History viewer
Module: tools/pyzoHistoryViewer.py
Line: 21

Tool --> "Interactive help"
Module: tools/pyzoInteractiveHelp.py
Line: 12

Tool --> "Logger"
Module: tools/pyzoLogger.py
Line: 15

Tool --> "Source structure"
Module: tools/pyzoSourceStructure.py
Line: 12

Tool --> "Web browser"
Module: tools/pyzoWebBrowser.py
Line: 20

Tool --> "Workspace"
Module: tools/pyzoWorkspace.py
Line: 13

Parameters for the SimpleDialog function:
Module: core/editorTabs.py
Lines: 63, 1350, 1392

**Comment by almarklein** [comment]
* The names of the tools cannot be translated, or at least, we'd have to make some bigger changes to the code to make that work.
* "Execute selection and advance" was added recently, after I asked for new translations.
* I will have a ook at "Create shell" and the parameters for the SimpleDialog function

**Comment by hlabrand** [comment]
I would like to add a few more that slipped through the cracks - I don't know how easy they are to locate in the code and to translate, but here they are:

- "(unsaved)" in the top bar (when creating a new file)
- the names of the languages are all in English
- "None" in "file > syntax parser", and in "View > Location of long line indicator"
- when booting Pyzo, the message "This is Pyzo the Python IDE for scientific computing" etc
- "click to select shell" when hovering over the Python button (first one) in the Shells window
- "Pyzo did detect a Python interpreter, but for scientific programming we recommend minicoda. If you want to manually specify the interpreter, set the exe in the shell config", and when you fix that problem it says "Happy coding!"

Thanks!

**Comment by almarklein** [comment]
Thanks @hlabrand, most strings should be relatively easy to find by performing a grep or a search with an IDE (like the "search in files" feature in Pyzo's file browser tool). Maybe I can interest you in making a pull request that makes these strings translatable?

**Comment by almarklein** [comment]
I've added some of the missing pieces mentioned in this issue that were not already covered by now.
