### ISSUE TITLE
conda command error: no module named 'conda'

### ISSUE THREAD

**Issue by umbe1987** [pyzo/pyzo#446]
I was using Pyzo with my Ubuntu 16 LTS without any problem since today.
I first installed matplotlib from the ubuntu terminal doing 'conda install matplotlib' and import was working correctly.
Then I tried to import the same module from Pyzo console (using the shell "/home/umberto/miniconda3/bin/python"), but import failed. So I removed Pyzo ('sudo -H python3 -m pip uninstall pyzolib pyzo') and reinstalled it to see if this would fix the problem.
I tried to install matplotlib via conda command through the python3 shell within Pyzo (always with 'conda install matplotlib'), and it installed, but I wasn't able to import matplotlib (a module error occurred).
I think I might now have a problem with the conda install (although I didn't touch it), since the Pyzo shell nor the ubuntu terminal seem to recognize the conda command (I am getting "Error in conda command: no module named 'conda'").
I am kind of lost right now, so I hope someone would help me keep using this amazing IDE.

**Comment by almarklein** [comment]
It seems like your conda env might be a bit broken. You can try `pip install conda` to re-install. Otherwise, if its not too much trouble, you can try re-installing miniconda. (BTW, you should be able to use multiple miniconda envs side-by side.)

**Comment by umbe1987** [comment]
Reinstalling miniconda did the trick. thank you so much for the help, and a special thanks for this beautiful piece of software!
