### ISSUE TITLE
Workspace: view of dictionary fails

### ISSUE THREAD

**Issue by fstengel** [pyzo/pyzo#447]
If I use this code
```python
d = {1: 3, 2: 444}
```
and try to explore variable d, it shows up as empty. Weirder:
```python
e = {"a":222}
```
I can look at it using the workspace (one item). However if I try to explore item "a", I get another failure.
If I add another numeric key (say e[1]=34), then dictionary e shows up as... empty

There must be some internal error. ~~Is there a way to have internal errors printed to some console? It would help a lot figuring what the problem is...~~ There is: logger; however, the errors must be caught, so no luck...

**Comment by almarklein** [comment]
Fixed in https://github.com/pyzo/pyzo/commit/c3c59ca4b398112f9ca2346c72fec3ce0ebb171b

**Comment by almarklein** [comment]
The errors occur in code that runs in the kernel. We cannot log messages to the Pyzo logger from there. Printing to the normal shell would be confusing for users. Therefore most errors in handling these introspection tasks are swallowed ...

**Comment by fstengel** [comment]
Thanks a lot. I had figured out something of the sort. The balance between being informative and overwhelming is quite difficult to attain satisfactorily. As it is Logger is a nice tool to have.

**Comment by almarklein** [comment]
Maybe we should add an extra channel by which the kernel can print messages to the logger ...
