### ISSUE TITLE
Encoding lines not respected when running as a script

### ISSUE THREAD

**Issue by fstengel** [pyzo/pyzo#450]
I have a file the starts with

``` python
#-*- coding: cp1252 -*-
```

Pyzo recognizes the encoding(i.e. shows _cp1252_ in _File>Encoding_) and executes the file (cmd/ctrl-E) without problems. Running it from the command line with a **python /path/to/file** works seamlessly as well. However when I use the _Run file as script_ menu item (shift-ctrl/cmd-E), I get the following error:

_Could not read script (decoding using UTF-8): "/path/to/file"_

It is as if pyzo is forcing the use of UTF-8 when sending the file to the shell.

**Comment by almarklein** [comment]
Just pushed a commit that ought to fix this. I verified that it worked locally Please reopen if it persist.
