### ISSUE TITLE
Crash with matplotlib.pyplot

### ISSUE THREAD

**Issue by lgm95** [pyzo/pyzo#451]
Using [v3.5.2, conda] Python 3.5.2 |Anaconda 4.2.0 (32-bit)| (default, Jul  5 2016, 11:45:57) on Windows (32 bits) with Pyzo interpreter with integrated event loop for PYQT5 (or other), plot appears but python crashes with error message :

Note on using QApplication.exec_(): 
The GUI event loop is already running in the pyzo kernel, and exec_()
does not block. In most cases your app should run fine without the need
for modifications. For clarity, this is what the pyzo kernel does:
- Prevent deletion of objects in the local scope of functions leading to exec_()
- Prevent system exit right after the exec_() call

The kernel process exited. (3221225477)

No error with [v3.4.1, conda] or pyzo 2015a
Thanks for help

**Comment by almarklein** [comment]
Could you provide a minimal code example that results in this issue?

**Comment by lgm95** [comment]
Example :
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0,10,100)
y = abscisses**2

plt.plot(x, y)

**Comment by almarklein** [comment]
If I recall correctly, MPL does not work with PyQt5. My suspicion is that MPL tries to load another GUI toolkit, which then breaks because PyQt5 is already loaded.

If you have PyQt4 or PySide installed, I'd recommend setting the "GUI integration" to either of these in Pyzo's shell configuration dialog.

**Comment by lgm95** [comment]
It seems not to be possible to choose PySide with python 3.5 :
    "...Complete output from command python setup.py egg_info:
    only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]"

And I have errors when trying to install PyQt4 with conda and pip :
  conda install PYQT4
  Fetching package metadata .............
  Solving package specifications:       => exit and return to prompt

  pip install PyQt4
  ...
  Could not find a version that satisfies the requirement PyQt4 (from versions: )
  No matching distribution found for PyQt4

  pip install E:\Downloads\PyQt4-4.11.4-cp35-none-win32.whl
  ...
  Exception:
  Error in pip command:
  'utf-8' codec can't decode byte 0xe8 in position 1206: invalid continuation byte

**Comment by almarklein** [comment]
`conda install pyqt=4`

**Comment by lgm95** [comment]
This command line shows packages to install, supercede or downgrade but do not proceed. Sorry for the newbee's questions...(can't find help on conda's website).

**Comment by almarklein** [comment]
It should ask you to proceed (Y) or cancel (N). Pressing enter will proceed.

**Comment by almarklein** [comment]
This looks like a Qt + MPL issue, not directly to Pyzo. Closing.
