### ISSUE TITLE
Improve PDF export options

### ISSUE THREAD

**Issue by ysalmon** [pyzo/pyzo#452]
Hi,
it is nice to have a PDF export option in Pyzo, but currently it is not customizable at all (as far as I know).
The feature I miss the most is to set the font size (and maybe preview it) and generate a black/white PDF.

Currently, the PDF is created with the same color scheme and the same font zoom level as the screen version, but these are generally not suitable for print.

Also, there are no line numbers, and no way to set a header/footer.

**Comment by almarklein** [comment]
I'd like these features too, but for PDF export we rely on Qt's print mechanics, so there is little that we can do. Though, perhaps we could create a new `PlainTextEdit` that we copy the code in, but including line numbers and styled in a configurable way. Sounds like it could be a nice thing to do for a contributor :)

**Comment by almarklein** [comment]
printing now includes line numbers: c50559b142ae3728420b6eb30bc8da86e42a71ff Small step in right direction, but leaving this open.
