### ISSUE TITLE
Autocompletion menu failing with 'Entry' key

### ISSUE THREAD

**Issue by benyoti** [pyzo/pyzo#454]
Hi,
There is a small bug in the autocompletion feature using either the editor or the ipython shell. When I start to write letters, the menu with all the variables starting with these letters appears so that I can select the right variable with the arrows keyboard, but when I do that and type the key 'Entry', it actually cancel the menu and goes back to the original letters I have started to write. This works fine if I select the variable by clicking with the mouse.

Pyzo version: 4.3.1 (source)
Platform: linux
Python version: 3.5.2+
Qt version: 5.7.0
PyQt5 version: 5.7

Apart from that I really want to congratulate the author for the 'full' debug mode, this is really what is missing from all other scientific python IDE!

**Comment by benyoti** [comment]
It looks like it works if you press the tab key before the entry key but I still think it's is a bug as the user would expect it to work just by pressing the entry key.

**Comment by almarklein** [comment]
It is deliberate, because we don't want an enter intended for a newline to get into the way. Its been on the wishlist for a while to make it easy to configure this behavior, but as of yet, you'd have to start the `logger shell`  (in tools) and run `pyzo.config.settings.autoComplete_acceptKeys = 'Tab Return'`.

**Comment by benyoti** [comment]
Alright, I understand. Thanks for pointing out how we can change this behavior!

**Comment by almarklein** [comment]
It is now possible to select the option from the menu https://github.com/pyzo/pyzo/commit/2c262e4f5fce898b661ae49c5c502fea354c845e

Plus more autocomp improvements: https://github.com/pyzo/pyzo/commit/56740c3d9724b7020d12d899ce779b64dabc30e8
