### ISSUE TITLE
Bug: Breakpoints not attached to line

### ISSUE THREAD

**Issue by jpauwels** [pyzo/pyzo#456]
If you insert a breakpoint and then insert a line above, the breakpoint doesn't move with the line it was placed on, but stays on the same line number.

**Comment by almarklein** [comment]
Fixed. It's a bit iffy if you modify the text closely around (e.g. move line with breakpoint down), due to the limited options that we have to associate a bp with a certain line. But at least these are cases where you see it. Breakpoints further below the text being edited moves along just fine.
