### ISSUE TITLE
Crash when trying to open or save a file on Wayland

### ISSUE THREAD

**Issue by LAntoine** [pyzo/pyzo#463]
When I try to open or save a file on Wayland Pyzo crashes and I get the following error.

```
(python3:11164): Gdk-WARNING **: gdkwindow-x11.c:5573 drawable is not a native X11 window
Segmentation fault (core dumped)
```

I am running GNOME on fedora 25 and it works well when I am using Xorg.

**Version info**
Pyzo version: 4.3.1 (source)
Platform: linux
Python version: 3.5.2
Qt version: 5.7.1
PyQt5 version: 5.7

**Comment by almarklein** [comment]
This looks like a Qt issue triggered by opening the open/save dialog. If you're interested you could isolate code for opening such a dialog and see if it is triggered by the way that Pyzo uses it, so maybe we can do something about it.

**Comment by almarklein** [comment]
In other words, could you please try this?

```py

from qtpy import QtWidgets

msg = 'Opening file(s)'
startdir = '~'
filter = "Python (*.py *.pyw);;"

app = QtWidgets.QApplication([])

filenames = QtWidgets.QFileDialog.getOpenFileNames(None, msg, startdir, filter)
if isinstance(filenames, tuple):  # PySide vs PyQt
    filenames = filenames[0]

print(filenames)

# app.exec_()
```

**Comment by LAntoine** [comment]
I don't have the bug anymore, I tried it on the 4.3.1 (source) and 4.4.0 version (source). 
It must have been corrected on Qt side.

Thanks for your help !

**Comment by almarklein** [comment]
Thanks for checking!
