### ISSUE TITLE
Blurred icons in shell toolbar using Fusion Qt theme in Windows 10

### ISSUE THREAD

**Issue by alacnorr** [pyzo/pyzo#464]
If the Qt theme Fusion is selected, the icons in the toobar on top of the shell window look blurred due to them being slightly downsized, probably due to some kind of padding used by the theme. When any other Qt theme is selected, the toolbar icons appear sharp and at their right size.

Apparently the issue can be fixed by changing the toolbar max height, in the below line in the __init__ of the class ShellStackWidget in the file pyzo\core\shellStack.py, that is
from
self._toolbar.setMaximumHeight(25)
to
self._toolbar.setMaximumHeight(26)

This higher value works with all Qt themes provided.

**Comment by almarklein** [comment]
Thanks for reporting and even providing a fix!
