### ISSUE TITLE
Problem export in pdf

### ISSUE THREAD

**Issue by titi56** [pyzo/pyzo#468]
Hello,

When I try to export my .py file from "File - Export to pdf", pdf file is not created, and I have this message :

Uncaught Python exception: 'module' object has no attribute 'QPrinter'
  File "C:\Program Files (x86)\pyzo\source\pyzo\core\menu.py", line 295, in <lambda>
    a.triggered.connect(lambda b=None: callback())
  File "C:\Program Files (x86)\pyzo\source\pyzo\core\menu.py", line 583, in _print
    printer = QtWidgets.QPrinter(QtWidgets.QPrinter.HighResolution)

What can I do to avoid it?
Thanks

**Comment by almarklein** [comment]
Thanks for reporting. I can confirm this is a bug. Fixed in https://github.com/pyzo/pyzo/commit/024fd1de78f7d03fa023378a84162e17dd840c6d

If you want to fix it yourself, please follow the changes in that commit, or wait for a new release.
