### ISSUE TITLE
Show "if __name__ == '__main__'" in source structure

### ISSUE THREAD

**Issue by lcvisser** [pyzo/pyzo#472]
It would be nice if the source structure shows the `if __name__ == '__main__'` entry point of a file, if it is present. Minor thing, but I find it very useful in PyDev and I think it should be too hard to add.

**Comment by almarklein** [comment]
Done in https://github.com/pyzo/pyzo/commit/a2c55f4d85cf0cb66cc18640a9b17f5621d83429
