### ISSUE TITLE
Failure of using all keyboard shortcuts

### ISSUE THREAD

**Issue by XuchanBao** [pyzo/pyzo#474]
At some point after installing PyQt5, I noticed all keyboard shortcuts in pyzo editor or shell stopped working, including copy/paste, save, open etc. However, inside some pop-up windows (like settings and shell configuration), some shortcuts like Ctrl+C and Ctrl+V still works.

**Comment by XuchanBao** [comment]
I tried uninstalling and reinstalling pyzo (in ubuntu VM using python3-pip), the issue persists.

**Comment by almarklein** [comment]
duplicate of #470
