### ISSUE TITLE
Calling exit() in Qt app takes an exceptional long time, even without GUI integration

### ISSUE THREAD

**Issue by sayabiws** [pyzo/pyzo#475]
Hello,

I'm currently developing a small application with PyQt4. I'm currently coding a "Quit" button, which simply exits the application (with `exit()`).

The thing is, whenever I start the application and quit with my Quit button, the application freezes for a few seconds before actually closing, while when I run it via the console (`python3 main.py`), it closes immediately when I press the Quit button.

The console tells me that the Pyzo kernel has an integrated event loop that prevents system exit right after the exec_() call. But when I set a new shell config up without GUI support, the message doesn't appear, but the application still freezes before closing.

This is very minor, but still, it's annoying.

Thanks by advance for any help!

**Comment by almarklein** [comment]
Mmm, tried to look into this to find the cause. No luck so far ...

```py
import sys
from qtpy import QtWidgets

app = QtWidgets.QApplication([])

def stop():
    exit()

b = QtWidgets.QPushButton('quit')
b.clicked.connect(stop)
b.show()

app.exec_()
```

**Comment by almarklein** [comment]
Using `app.quit()` instead is fast. If necessary, wrao `app._exec()` in `exit(..)` to terminate the process too.
