### ISSUE TITLE
Python 2.7 and qt4

### ISSUE THREAD

**Issue by Kybernaut** [pyzo/pyzo#477]
Hello guys,

I had a hard day trying to get mayavi running, and I think I tracked it down to a bug in pyzokernel/guiintegration.py.

Here's a short description of my setup:
Pyzo 4.3.1 running on Windows 10-64 Bit
Anaconda 2.7 (Anaconda2-4.3.1-Windows-x86_64)
I added mayavi to this via `conda install mayavi`.

In Spyder I can run mayavi-code without problems, in pyzo I get into trouble. (But I want to use pyzo, as spyder's "debugging capabilites" are... not good.)

Minimal source code for running into trouble (after long figuring around):
```
from qtpy import QtGui , QtWidgets, QtCore
print(QtWidgets.QWidget)
```

This leads to 

```
Traceback (most recent call last):
  File "D:\dev\src\myprog.py", line 8, in <module>
    from qtpy import QtGui , QtWidgets, QtCore
  File "d:\dev\anaconda2\lib\site-packages\qtpy\__init__.py", line 97, in <module>
    sip.setapi('QString', 2)
ValueError: API 'QString' has already been set to version 1
```

Changing guiintegration.py from

```
class App_pyqt4(App_qt):
    """ Hijack the PyQt4 mainloop.
    """
    
    def importCoreAndGui(self):
        # Try importing qt        
        import PyQt4
        from PyQt4 import QtGui, QtCore    
        return QtGui, QtCore
```

to

```
class App_pyqt4(App_qt):
    """ Hijack the PyQt4 mainloop.
    """
    
    def importCoreAndGui(self):
        
        import sip
        sip.setapi('QDate', 2)
        sip.setapi('QDateTime', 2)
        sip.setapi('QString', 2)
        sip.setapi('QTextStream', 2)
        sip.setapi('QTime', 2)
        sip.setapi('QUrl', 2)
        sip.setapi('QVariant', 2)

        # Try importing qt        
        import PyQt4
        from PyQt4 import QtGui, QtCore
        return QtGui, QtCore
```

solves the issue, and my minimal code from above prints

```
<class 'PyQt4.QtGui.QWidget'>
<class 'PyQt4.QtGui.QWidget'>
```

And: mayavi is running. Before my change a
```
import os
os.environ["QT_API"] = "pyqt"
from mayavi import mlab
```
lead to
```
d:\dev\anaconda2\lib\site-packages\pyface\qt\__init__.py in prepare_pyqt4()
ValueError: API 'QDate' has already been set to version 1`
```
Now it works.

I've never programmed qt, or any other gui in Python. In fact i recently started using Python, so maybe I didn't see an obvious solution. But this was the only thing, which worked. Environment-Variables, ipython options, nothing did the job.

In my understanding the code in guiintegration is instantiating qt in the wrong way. For instance in 
`pyzo\source\pyzo\util\qt\__init__.py` and in 'Anaconda2\Lib\site-packages\qtpy\__init__.py' it is done in the correct way, that's where I got the idea with the `setapi` from:
```
if API in PYQT4_API:
    try:
        import sip
        try:
            sip.setapi('QString', 2)
            sip.setapi('QVariant', 2)
            sip.setapi('QDate', 2)			
            sip.setapi('QDateTime', 2)
            sip.setapi('QTextStream', 2)
            sip.setapi('QTime', 2)
            sip.setapi('QUrl', 2)
        except AttributeError:
            # PyQt < v4.6
            pass
        from PyQt4.Qt import PYQT_VERSION_STR as PYQT_VERSION  # analysis:ignore
        from PyQt4.Qt import QT_VERSION_STR as QT_VERSION  # analysis:ignore
        PYSIDE_VERSION = None
        PYQT5 = False
        PYQT4 = True
```

As I'm absolutely not familiar with python, maybe one of you guys wants to fix this, or comment about my idea.

Thanks!

**Comment by almarklein** [comment]
I'm a bit unsure what the implications of setting the api might be for people who rely on version 1 of the API. I think that if your add `from qtpy import QtGui` to the startup script in the shell config, and remove the `# AFTERGUI` thing, that the correct API will be selected for you. Could you give that a shot?

**Comment by Kybernaut** [comment]
Hi Almar,

thanks, works like a charm.

I tried a lot in the shell configuration, and I also thought of the startup script. But I didn't try "Code to run at startup". If I had seen the "After GUI"-tag, maybe I would have come to that idea.

Thank you, I feel much better without changing the code!

For further information: What is the best source for info about configuration of Pyzo? I didn't find a real help file, discussing the "Shell configurations" or other preferences of Pyzo. Maybe in the code or elsewhere?

Thanks!

**Comment by almarklein** [comment]
> What is the best source for info about configuration of Pyzo?

... I agree that the docs of Pyzo could be better :) Hoovering over an item in the shell configuration will show a tooltip with some more info, but that's easily overlooked and not always as complete as it could be.
