### ISSUE TITLE
Pyzo 4.3.1 windows error

### ISSUE THREAD

**Issue by JohnLunzer** [pyzo/pyzo#478]
The Pyzo quickstart page isn't entirely clear on what my windows environment needs to look like. 

I currently have Anaconda with Python 2 installed on my system but I also have a conda environment with 3.5 installed. 

Step 1 of the quickstart guide says, "Install Pyzo". Done that.

Step 2 says "install Python environemnt" (I skipped this because I already have anaconda installed with my environments)

Step 3 implies I need to start Pyzo. Here is what I get when I try to start Pyzo:
![pyzo_error](https://cloud.githubusercontent.com/assets/8135795/25905421/faca2c76-356f-11e7-87a1-a8512c54afd8.png)

I'm confused as to what is necessary to run Pyzo because the "About Pyzo" page says that it can execute code from any Python version but the quickstart page says, "Make sure to use Python 3 and not Python 2". 

Any insight would be appreciated.

**Comment by almarklein** [comment]
This is odd, the prebuild binaries should have PySide or PyQt4 with them. Is `X:\` an actual drive on your machine? It kinda looks like its trying to use your system Python to resolve the import ...

**Comment by almarklein** [comment]
Could you try again with the latest binary release (4.4.0)?

**Comment by JohnLunzer** [comment]
Sorry for the delay. I tried with the 4.4.1 binary and it works without issue.

**Comment by almarklein** [comment]
No problem. Thanks for trying!
