### ISSUE TITLE
TKinter image

### ISSUE THREAD

**Issue by GPaddle** [pyzo/pyzo#480]
![probleme](https://cloud.githubusercontent.com/assets/28558552/26190636/cfbd216e-3baa-11e7-88e9-6ad8a15e34f0.png)

Here is my problem, I want to attach an image with pyzo by TKinter and the image looks not supported

Has someone an help to give me ?

**Comment by almarklein** [comment]
It seems like the path is invalid. You're using a relative path, but for that to work, the "current directory" must be correct (I assume its relative to the script?).

Try using an absolute path, or running the file as a script so that paths relative to the scripts can be used.
