### ISSUE TITLE
Call for new translations

### ISSUE THREAD

**Issue by almarklein** [pyzo/pyzo#481]
Hi @pyzo/translators !

I am doing a "sprint" on Pyzo right now, and plan to release in about a week. There are about 10 new translations since last time. If you can find the time, please update your translations. 

Thanks in advance!

**Comment by almarklein** [comment]
hold on a minute, some translations do not make it into the tr files ...

**Comment by almarklein** [comment]
ok, done. There are about 50 new strings to translate.

**Comment by yltang52** [comment]
1. I noticed that the line numbers in the `*.tr` files are a little different from those in the corresponding `*.py` files. Do we have to correct them?

2. Is there a way to know the places that I have to modify this time?

3. Some message strings need translation, however, they are not enclosed by the `translate()` function, for example, lines 741, 1343, 1353 in `menu.py`. Do we need to make that correction?

Thanks.

**Comment by almarklein** [comment]
1. Not sure why that would be. These are generated by PyQt's `lupdate` tool so I would not update them manually.

2. How do you mean?  The `linguist` tool it will tell you what strings need updating. 

3. Thanks for checking these. I shall make them translatable, but don't worry about it for this round.

**Comment by yltang52** [comment]
Question:

About the message at line 338 of `pyzo_zh_TW.tr`,  there is a `<comment> ... </comment>` item. How should I do about it?

**Comment by almarklein** [comment]
That is additional information for the translator to help understand the meaning of the text. It looks like you're editing the `.tr` files directly. This works, but are you aware that there are tools that make it easier for you to do the translations (e.g. see what translations need updating). To use that, in the Pyzo logger shell, type `linguist('Traditional Chinese')`.

**Comment by yltang52** [comment]
Yes, I do use `linguist`. I just inadvertently found the `<comment>` when I was trying to understand the `context` structure in the file. Thanks a lot.

**Comment by almarklein** [comment]
Pyzo 4.4.0 was released last week. Though I'll likely do a 4.4.1 soon, at least for OSX because there is a nasty font issue on Mac.

**Comment by yltang52** [comment]
A quick review:

1.
I upgraded Pyzo to version 4.4.0  with "sudo python3 -m pip install pyzo --upgrade" on Ubuntu 16.04 LTS. I found that when the mouse is on some menu item, the explanatory text used to show up. But now, the texts become a black rectangular.

2. There are still texts not translated in the Edit menu:
"Justify comment/docstring"
"Duplicate line"
"Delete line"

Although the first and third items are already in the translation file.

Thanks a lot.

![imag0856](https://user-images.githubusercontent.com/6300280/27787023-021b6cf8-6016-11e7-9fd0-15b9adf4c053.jpg)
.

**Comment by almarklein** [comment]
1. Is the black box in place of the tooltip a new problem in 4.4.0?
2. Mmm, the duplicate and delete line actions were indeed a late addition (after I posted this issue). Not sure about the "justify" action. I reran `lupdate()`, so that the new translations are ready to be translated too.

**Comment by yltang52** [comment]
Well, the black box occurred only on one of my computers and I'll look into it.
No other problems. Thanks and good job.

**Comment by yltang52** [comment]
Still have no clue why only one of my PCs has the "black box" problem. I installed pyzo with "sudo apt-get install python3-pip python3-pyqt5" and "sudo python3 -m pip install pyzo --upgrade". Now when I start pyzo, a question mark icon appear in the launcher and the explanation text of menu items appears as a black box (see the attached `pyzo5.png`).

However, if I uninstall `python3-pyqt4` and install `python3-pyqt5` instead, there will be no question mark icon in the launcher, but there will be vertical stripes in the file browser (`pyzo4.png`).

So, what's the problem?

![pyzo5](https://user-images.githubusercontent.com/6300280/28048400-54da69b8-6623-11e7-9fc5-08f5ab2f8eae.png)
![pyzo4](https://user-images.githubusercontent.com/6300280/28048402-57f9ae74-6623-11e7-879a-8c86b3427ca5.png)

**Comment by almarklein** [comment]
Unfortunately, I don't think there's much we can do about these issues from Pyzo. Both the striping and tooltips seem Qt-specific issues. The tooltips are also sortof platform dependent, as Qt tries make their use look and feel native...

**Comment by almarklein** [comment]
Closing this. I will create a new issue when I am about to do a release. You can still do translations, at any time when it suits you, really.
