### ISSUE TITLE
Interactive help tool does not work anymore on Win32 Pyzo 4.4.0

### ISSUE THREAD

**Issue by bertrand-micaux** [pyzo/pyzo#494]
I am currently testing Pyzo 4.4.0 on a Win32 platform, eager to enjoy the improvements to my favorite Python IDE.

I get a "No help available" answer for anything I type in the search field of the interactive help tool : for builtin functions, for module functions or for user-defined objects.

Help baloons which showed the syntax of functions while typing have also disappeared.

I am on a Win32 platform, using a Win64 MiniConda 4.3.16 distribution and Python 3.6.1.
Those issues do not appear with Pyzo 4.3.1 (tested with the same environment and same Pyzo config files).
In a console in Pyzo 4.4.0, `help` and `?` commands work as expected.

**Comment by Diti24** [comment]
Confirm same issue encountered on Linux platform

**Comment by almarklein** [comment]
Reproduced in the source version too.

**Comment by almarklein** [comment]
mmm, I can say for the first time that adding flake8 checking *resulted* in a bug. The interpreter uses `eval()` with commands that use the inspect module, but that import was removed, because pyflakes did not see its use ... :(

**Comment by almarklein** [comment]
Fixed that 88e049339c74aade48cc2d214a8f3df662698710. Now looking into the tooltips.

**Comment by almarklein** [comment]
Tooltips look fine now too. I was first looking at `isinstance`, for which we do not obtain the sig, because its a builtin and builtins were previously not inspectable. Fixed that too: 6506e49dd87f335ae502682a323d1f9e8a93361c

**Comment by bertrand-micaux** [comment]
It works, thanks !
