### ISSUE TITLE
Normalize copyright information project-wise

### ISSUE THREAD

**Issue by ghisvail** [pyzo/pyzo#496]
@almarklein Could the copyright information of the entire `pyzo` code base be normalized to `the Pyzo development team`? At the moment, `yoton` has different authorship than the rest of the code base for some reason.

**Comment by almarklein** [comment]
Done. BTW I think I'll release a patch release this week.

**Comment by ghisvail** [comment]
👍 thanks for the heads-up

**Comment by almarklein** [comment]
@ghisvail just released 4.4.1
