### ISSUE TITLE
Run file as script not working

### ISSUE THREAD

**Issue by hudcap** [pyzo/pyzo#498]
Running Pyzo 4.4.1 on Windows.

"Run file as script" saves the file, but does not run it.
It worked on 4.3
Not sure if the bug was introduced in 4.4 or 4.4.1

**Comment by almarklein** [comment]
I cannot reproduce this. Have you tried both the `menu > run > run file as script` and `Ctrl+Shift+E`?

**Comment by almarklein** [comment]
BTW: is this with or without IPyton shell?

**Comment by hudcap** [comment]
Yes, I tried the menu option, the keyboard shortcut, and the context menu of the file tab.
This is without the IPython shell.

I'm going to try downgrading to see if it solves it. Maybe it's not related to the new version.

**Comment by hudcap** [comment]
I confirmed that this works in 4.4, but does not work in 4.4.1

This is on Windows 10 64-bit Version 1703

**Comment by hudcap** [comment]
Aha! I discovered the logger :)
```
Uncaught Python exception: 'ipython'
  File "C:\Program Files (x86)\pyzo\source\pyzo\core\menu.py", line 293, in <lambda>
    a.triggered.connect(lambda b=None, v=value: callback(v))
  File "C:\Program Files (x86)\pyzo\source\pyzo\core\menu.py", line 1596, in _runFile
    self._runScript(editor, shell)
  File "C:\Program Files (x86)\pyzo\source\pyzo\core\menu.py", line 1609, in _runScript
    if shell._startup_info['ipython'] == 'yes':
```

I enabled IPython and then disabled it and now it works.
My guess is that the key `'ipython'` isn't created until the setting is turned on.

HTH

**Comment by almarklein** [comment]
Thanks for reporting and also finding the problem. I fixed the problem.
