### ISSUE TITLE
change a line in translation

### ISSUE THREAD

**Issue by flame51** [pyzo/pyzo#500]
in  pyzo\tools\pyzoSourceStructure.py
            text = translate('pyzoSourceStructure', 'Parsing ' + editor._name + ' ...')
seems this should be changed to
            text = translate('pyzoSourceStructure', 'Parsing ') + editor._name + ' ...'

**Comment by almarklein** [comment]
Good catch! Could you make a PR for that? You can even do it in the GitHub interface.

**Comment by flame51** [comment]
ok.

**Comment by almarklein** [comment]
Closed by #502, thanks!
