### ISSUE TITLE
a new style for SourceStructure and others

### ISSUE THREAD

**Issue by flame51** [pyzo/pyzo#503]
a new style for SourceStructure and others
in SourceStructure . use color and parenthesis to indicate class or def etc.  

![image](https://user-images.githubusercontent.com/26970348/29805544-ff5c52e2-8cbc-11e7-9a72-0539f4630f41.png)

all in black looks like this

![image](https://user-images.githubusercontent.com/26970348/29805613-5d6b2372-8cbd-11e7-8b00-6195c3e4adaa.png)

**Comment by flame51** [comment]
should I make a PR for this? (the style could be changed from whiteStyle to blackStyle manually )

**Comment by almarklein** [comment]
I have just made some changes to make the colors of the source structure the same as the default editor colors.

To allow custom colors, we should really work towards #80
