### ISSUE TITLE
Obsolete appstream format

### ISSUE THREAD

**Issue by ghisvail** [pyzo/pyzo#510]
See the following Lintian [error](https://lintian.debian.org/tags/appstream-metadata-legacy-format.html) reported for pyzo on Debian.

**Comment by almarklein** [comment]
How critical is this? Can it wait till the next release?

**Comment by ghisvail** [comment]
Since this is reported as a Lintian error, I cannot upgrade the Debian package without this issue being fixed (either by a new release or a hotfix patch).

**Comment by almarklein** [comment]
I updated the xml file. What's the easiest way to test that this works before doing a release?

**Comment by ghisvail** [comment]
From the [AppStream Debian guidelines](https://wiki.debian.org/AppStream/Guidelines):

> Metadata files can be validated for conformity with the specification using appstreamcli from the appstream package (appstreamcli validate <file>.xml)

Looks like there is a validator.

**Comment by almarklein** [comment]
Tried in 4 VM's, but no luck getting it installed/running without errors. The changes are quite small, actually; the only thing that I'm unsure about is the part:
```
 <provides>
   <binary>pyzo</binary>
</provides>
```

Do you know whether this would be correct? If so, let's just make a patch release and see what happens.

**Comment by ghisvail** [comment]
I believe this is correct.

**Comment by ghisvail** [comment]
> If so, let's just make a patch release and see what happens.

I'll be happy to iterate on that.

**Comment by almarklein** [comment]
I've just done a release.

**Comment by ghisvail** [comment]
I have updated the Debian package. FYI, the install location of the AppStream metadata has now changed from `/usr/share/appdata` to `/usr/share/metainfo`. The former is deprecated in favor of the latter.

**Comment by almarklein** [comment]
Awesome! I will update the path right away
