### ISSUE TITLE
Error: from sympy import *

### ISSUE THREAD

**Issue by hudcap** [pyzo/pyzo#516]
I have sympy 1.1.1 installed.
When I run ```from sympy import *``` in pyzo using both a Python shell and an IPython shell, I get the following error immediately, and after every single subsequent command (even non-sympy related):

    c:\users\[redacted]\miniconda3\lib\site-packages\sympy\core\decorators.py:38: SymPyDeprecationWarning: 
    
    C, including its class ClassRegistry, has been deprecated since SymPy
    1.0. It will be last supported in SymPy version 1.0. Use direct
    imports from the defining module instead. See
    https://github.com/sympy/sympy/issues/9371 for more info.
    
      _warn_deprecation(wrapped, 3)

This does not occur outside of pyzo.

**Comment by almarklein** [comment]
Are you sure that Pyzo and "outside of pyzo" use the same sympy versions? Have you tried updating sympy?

**Comment by hudcap** [comment]
I only have one Python installation (miniconda).
In both Pyzo and "outside of Pyzo," the command ```sympy.__version__``` returns ```1.1.1```
No updates were found for ```conda update sympy```
You're not getting this error?

**Comment by almarklein** [comment]
Nope, for me it looks like this, can you post what it shows for you? I have no idea where to look.

```
Python 3.6.1 | packaged by conda-forge | (default, Mar 24 2017, 01:02:36) on Windows (64 bits).
This is the Pyzo interpreter with integrated event loop for ASYNCIO.
Type 'help' for help, type '?' for a list of *magic* commands.

>>> from sympy import *

>>> 3 + 2
5

>>> 
```

**Comment by hudcap** [comment]
This is what I get:
```
Python 3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) on Windows (64 bits).
This is the Pyzo interpreter with integrated event loop for PYQT5.

Using IPython 6.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from sympy import *
c:\users\[me]\miniconda3\lib\site-packages\sympy\core\decorators.py:38: SymPyDeprecationWarning: 

C, including its class ClassRegistry, has been deprecated since SymPy
1.0. It will be last supported in SymPy version 1.0. Use direct
imports from the defining module instead. See
https://github.com/sympy/sympy/issues/9371 for more info.

  _warn_deprecation(wrapped, 3)

In [2]: 1 + 1
Out[2]: 2
c:\users\[me]\miniconda3\lib\site-packages\sympy\core\decorators.py:38: SymPyDeprecationWarning: 

C, including its class ClassRegistry, has been deprecated since SymPy
1.0. It will be last supported in SymPy version 1.0. Use direct
imports from the defining module instead. See
https://github.com/sympy/sympy/issues/9371 for more info.

  _warn_deprecation(wrapped, 3)

In [3]: 
```

**Comment by almarklein** [comment]
Ha! I can now reproduce it when I turn on the workspace tool (and only with IPython, it seems). I suspect this is related by the workspace tool trying to inspect the variables or something.

My take is that this is another case that demonstrates why `import *` is a bad idea ...
