### ISSUE TITLE
Ipython detection not working

### ISSUE THREAD

**Issue by maphew** [pyzo/pyzo#517]
I get errors like the below when I try to use "Run file as script" and "use Ipython if available" is checked in the shell configuration, and ipython isn't available in that shell.

```
Legacy Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) on Windows (32 bits).
This is the Pyzo interpreter with integrated event loop for TK.
Type 'help' for help, type '?' for a list of *magic* commands.

>>> %cd t:\test\scripts  File "<console>", line 1
    %cd t:\test\scripts
    ^
SyntaxError: invalid syntax

>>> %run -i T:\Test\scripts\centerpede.py
  File "<console>", line 1
    %run -i T:\Test\scripts\centerpede.py
    ^
SyntaxError: invalid syntax
```

Version info
Pyzo version: 4.4.2 (binary)
Platform: win32
Python version: 3.4.5
Qt version: 4.8.7
PySide version: 1.2.4

**Comment by almarklein** [comment]
Are you sure that IPython is installed in that environment?

**Comment by maphew** [comment]
No, ipython is not installed. The problem I'm reporting is that Pyzo doesn't detect that ipython isn't available and tries to use it anyway.

**Comment by almarklein** [comment]
> ... Pyzo doesn't detect that ipython isn't available 

Why do you think that? From the looks of the interpreter output, it looks like it does. And I would expect these commands to fail when not in IPython mode.

**Comment by maphew** [comment]
Those commands should not be issued when ipython is not available. Oh! I
get part of the misunderstanding:

It's not me typing those commands in the interpreter window. Its pyzo
entering them when I press F5 and similar.

**Comment by almarklein** [comment]
ah! Now I understand. Sorry for the confusion :) This indeed looks like a bug. I'll have a look at it soon. For the time being, just toggle the checkbox off.  Thanks for the report!

**Comment by almarklein** [comment]
Reproduced and fixed.
