### ISSUE TITLE
Show U+000C FORM FEED as a visible glyph

### ISSUE THREAD

**Issue by bignose-debian** [pyzo/pyzo#522]
The U+000C FORM FEED character is valid white space in Python source code. In a Pyzo editor, it has no display glyph and displays as zero width; the cursor can move over it in the document, with no change of position.

This makes it confusing to move through and edit a file containing that character, and makes it visually indistinguishable when the file is altered to insert or remove that character.

Please display the U+000C character in the text editor, with unique glyph of some kind (e.g. “FF” in small letters in a different colour; or the “^L” glyph as used in Emacs or Vim).

**Comment by almarklein** [comment]
I see your point. Unfortunately, this is out of our hands since it is a limitation/feature of the QPlainTextEdit.

**Comment by bignose-debian** [comment]
On 28-Jan-2018, Almar Klein wrote:
> I see your point.

Thank you :-)

> Unfortunately, this is out of our hands since it is a
> limitation/feature of the QPlainTextEdit.

Pyzo has a feature to enable or disable visible glyphs for other white
space (e.g. U+0009 and U+0020). Is that within Pyzo's control, and can
it be modified to show U+000C and other non-printable characters?

-- 
 \          “One time a cop pulled me over for running a stop sign. He |
  `\        said, ‘Didn't you see the stop sign?’ I said, ‘Yeah, but I |
_o__)                don't believe everything I read.’” —Steven Wright |
Ben Finney <ben@benfinney.id.au>

**Comment by almarklein** [comment]
Pyzo simply [sets](https://github.com/pyzo/pyzo/blob/master/pyzo/codeeditor/extensions/appearance.py#L664-L697) flags at the QPlainTextEdit's document: http://doc.qt.io/qt-5/qtextoption.html
