### ISSUE TITLE
Syntax highlighting not working when line contains a built-in function

### ISSUE THREAD

**Issue by kaktus018** [pyzo/pyzo#524]
With the newest version 4.5 the syntax highlighting is no longer working when a line contains the name of a built-in function which is e.g. called from a module.

Example:

import numpy as np
np.abs(-1) # This comment is NOT highlighted
abs(-1) # This comment is highlighted

**Comment by almarklein** [comment]
well spotted. This has been fixed. I plan to do another release soon.

**Comment by almarklein** [comment]
See https://github.com/pyzo/pyzo/commit/389cb9d8b6097cd6ac271dfc9761ac3868a5104b
