### ISSUE TITLE
Pyzo is not compatible with Python-3.7 , because use of the reserved word 'async'

### ISSUE THREAD

**Issue by stonebig** [pyzo/pyzo#529]
````
  File "C:\python-3.7.0b2.amd64\lib\site-packages\pyzo\yoton\clientserver.py", line 81
   def __init__(self, address, async=False, verbose=0):
                                    ^
SyntaxError: invalid syntax
````

**Comment by stonebig** [comment]
I integrated the "master" branch in WinPython-3.7 betas.

**Comment by almarklein** [comment]
For the record (for others chiming in) this has been fixed in master, but there has not been a new release since the fix.

**Comment by almarklein** [comment]
I agree. But I have a general lack of time right now. Perhaps after EuroPython.

**Comment by sm4rk0** [comment]
I've just filed a [LaunchPad bug](https://bugs.launchpad.net/ubuntu/+source/pyzo/+bug/1801588) and then found this one. Python 3.7 just entered disco-proposed repo - a staging repo for a development Ubuntu version (19.04).

**Comment by almarklein** [comment]
Oh, work to do then!

**Comment by almarklein** [comment]
Actually, release 4.6.0 and 4.6.1 both already include the fix.

**Comment by ferdymercury** [comment]
I saw this problem when upgrading Ubuntu 18 to Ubuntu 20 via do-release-upgrade, that led to a broken upgrade/install. The solution was to edit by hand the file /usr/share/pyzo/pyzo/yoton/clientserver.py and change the name of the parameter async on line 81 to assync, as well as two or three lines below. Then I run 'apt --fix-broken install' and the upgrade completed.
