### ISSUE TITLE
Really tiny icons on Windows retina display

### ISSUE THREAD

**Issue by almarklein** [pyzo/pyzo#531]
I saw this with a student. On Mac retina displays work fine afaik, but on Windows we might need to apply some Qt-foo... It is worth noting that there were *many* apps that had tiny icons on that machine (including e.g. MPL figures).

**Comment by ysalmon** [comment]
I also have tiny toolbar icons on Linux (KDE Plasma with DPI set to 192).

**Comment by micappe** [comment]
I attach a couple of example of how Pyzo looks on a 4K monitor in Windows 10 with a overall scaling of 200% in the first case, and of 100% in the second case. The latter makes everything too small and Windows unusable on the monitor, but is illustrates the relative scaling of text and icons. For comparison I also include a Matplotlib 3.0 figure, which scales properly in both cases.

![pyzo_200](https://user-images.githubusercontent.com/39297263/48625422-1a9b5d80-e9a7-11e8-901b-92d0ee68fdb4.png)
![pyzo_100](https://user-images.githubusercontent.com/39297263/48625428-1cfdb780-e9a7-11e8-8979-32d9dbdeaa66.png)

**Comment by divenex** [comment]
I attach a couple of example of how Pyzo looks on a 4K monitor in Windows 10 with an overall scaling of 200% in the first case, and of 100% in the second case. The latter makes everything too small and Windows unusable on the monitor but it illustrates the relative scaling of text and icons. For comparison, I also include a Matplotlib 3.0 figure, which scales properly in both cases.

![pyzo_200](https://user-images.githubusercontent.com/39297263/48625422-1a9b5d80-e9a7-11e8-901b-92d0ee68fdb4.png)
![pyzo_100](https://user-images.githubusercontent.com/39297263/48625428-1cfdb780-e9a7-11e8-8979-32d9dbdeaa66.png)

**Comment by almarklein** [comment]
I just pushed a [commit](https://github.com/pyzo/pyzo/commit/e568c5364d1c184dfbe17774669ef8b2608b1d60) that I think/hope will fix this.

**Comment by divenex** [comment]
Great thank you. However there is a bug: as it is, this does not work. However, it completely fixed the issue if I set

    os.environ['QT_AUTO_SCREEN_SCALE_FACTOR'] = "1"

With this fix, Pyzo looks great in Windows 10 on my 4K display with 200% scaling. I also checked that the icons scale properly also when I change the display scaling to 100% and restart Pyzo.

**Comment by ysalmon** [comment]
Alas, neither the commit nor @divenex version improves things with KUbuntu 18.04.

**Comment by almarklein** [comment]
> it completely fixed the issue if I set [...]

Awesome!

> Alas, neither the commit nor @divenex version improves things with KUbuntu 18.04.

:(

I'll dig a little more tomorrow. @ysalmon What version of Qt is that? I think you'd need 5.something.

**Comment by ysalmon** [comment]
Version info
Pyzo version: 4.6.2 (source)
Platform: linux
Python version: 3.6.7
Qt version: 5.9.5
PyQt5 version: 5.10.1

**Comment by ysalmon** [comment]
Another Qt project has an issue about this too, and a workaround : https://github.com/gitahead/gitahead/issues/178#issuecomment-468725766

I tested it :  ``QT_SCREEN_SCALE_FACTORS=2 pyzo`` gives nicer icons on my system.

Maybe there is a way to force it from within Pyzo ?

**Comment by almarklein** [comment]
Great that you found a solution! Is it enough to set it in the ENV var section in the shell config?

> Maybe there is a way to force it from within Pyzo ?

Well, the point is that we should only do it for high-res displays, and if Qt has problems auto-detecting it, I don't think it would be easy to do for us :)  We could add it by default to the shell config dialog, but in commented form, so users can enable it as needed.

**Comment by almarklein** [comment]
Ok, forget my last comment. The factor must be applied to the Pyzo process, not the one of the interpreter, lol.

**Comment by almarklein** [comment]
Let's close this, right?

**Comment by stonebig** [comment]
works great, worth a small maintainance release ?

**Comment by ysalmon** [comment]
Until a new release, it is easy to tweak the desktop file (shortcut in the application menu) to prepend ``QT_SCREEN_SCALE_FACTORS=2``.

**Comment by almarklein** [comment]
> a small maintainance release ?

**Comment by almarklein** [comment]
Do you have a date in mind before which you'd want a release? I'm planning on a release end of august / early september.

**Comment by stonebig** [comment]
I picked today master from github, so whenever is best for you will be ok.
