### ISSUE TITLE
Ubuntu 18.04: Cannot lock the pyzo icon on the dock

### ISSUE THREAD

**Issue by yltang52** [pyzo/pyzo#533]
Just installed Ubuntu 18.04 beta2 and found that the pyzo icon is not able to be locked on the dock. There just no such option when right-clicking the icon.

**Comment by almarklein** [comment]
That is odd. Pyzo itself is completely unaware of the dock. Maybe its a Qt problem? You could try running Pyzo from source using the system Qt libs.

**Comment by yltang52** [comment]
How do I run Pyzo from source using the system Qt libs?

BTW, Pyzo can be started from the terminal, but it is not available in the "Activities" (the top left corner of the Ubuntu 18.04 desktop). Is it the reason that it cannot be locked?

**Comment by almarklein** [comment]
> How do I run Pyzo from source using the system Qt libs?

Install PyQt (4 or 5) for Python3, and pip install pyzo, then run from there.

> [...]  is not available in the "Activities" (the top left corner of the Ubuntu 18.04 desktop). Is it the reason that it cannot be locked?

I have no idea; I have not used Ubuntu in a while :)

**Comment by yltang52** [comment]
I made an application icon file `/usr/share/applications/pyzo.desktop` as follows:

    [Desktop Entry]
    Name=Pyzo
    Type=Application
    Exec=/usr/local/bin/pyzo
    Terminal=false
    Icon=/usr/local/lib/python3.6/dist-packages/pyzo/resources/appicons/pyzologo32.png
    Comment=Integrated Development Environment
    NoDisplay=false
    Categories=Development;IDE;
    Name[en]=Pyzo

And then installed it.

`sudo desktop-file-install /usr/share/applications/pyzo.desktop`

Now it works.

**Comment by almarklein** [comment]
Nice!

Also note the `pyzo.appdata.xml` freedesktop file in the root of the Pyzo repo.
