### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by lachhebo** [pyzo/pyzo#534]
It would be great to have a flatpack package for pyzo, so every linux user could use it.

**Comment by almarklein** [comment]
I hear about "flatpack" for the first time. AFAIK there is a Debian package, and one can always use `pip install pyzo`. For my understanding, what would a flatpack add?

**Comment by lachhebo** [comment]
Sorry I mean flatpak (not flatpack), it is way to distribute application on linux regardless of
distribution, for people who are not using debian, it would make pyzo much easier to install. 
(https://flatpak.org/)

**Comment by almarklein** [comment]
Flatpak seems like a very nice idea!  And I agree that it would be a good idea to be able to distrubute Pyzo in this way. I don't have a lot of free cycles right now though. Would you be interested in taking this on (with help from me where needed)?

**Comment by lachhebo** [comment]
Hi, 

I have worked a lot and finally I managed to create a json manifest file for pyzo, I have tried on my fedora and it worked :)

Actually, I have just used pip to create the package.  

This is the org.kde.python3-pyzo.json file : 
```
{
    "app-id": "org.kde.python3-pyzo",
    "runtime": "org.kde.Platform",
    "runtime-version": "5.10",
    "sdk": "org.kde.Sdk",
    "command": "pyzo",
    "finish-args": [
        /* X11 + XShm access */
        "--share=ipc", "--socket=x11",
        /* Wayland access */
        "--socket=wayland",
        /* Needs to access the home directory: */
        "--filesystem=home"
	],
    "modules": [ 
    	{
			"name": "pyqt5",
			"config-opts": [ "--disable-static", "--enable-x11" ],
			"no-autogen": true,
			"buildsystem": "simple",
			"build-commands": [ 
				"pip3 install --no-index --find-links \"file://${PWD}\" --prefix=/app PyQt5==5.9.2"
			],
			"sources": [
				{
					"type": "file",
					"url": "https://files.pythonhosted.org/packages/3a/c6/26270f5550f00920045c2f0b222a7d03d7a64382825c68bf0bb1a51d854c/PyQt5-5.9.2-5.9.3-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl",
					"sha256": "5dab7244b6932606490b47a0692e03d7b72d89f7d3dfa3d147a8b34d6af72451"
				},
				{
					"type": "file",
					"url": "https://files.pythonhosted.org/packages/6b/46/2869369c8ec634ec9dc714b84834e9264acbe87eb7492328efccfa0c855e/sip-4.19.8-cp35-cp35m-manylinux1_x86_64.whl",
					"sha256": "e72955e12f4fccf27aa421be383453d697b8a44bde2cc26b08d876fd492d0174"
				}
			]
		},
		{
		    "name": "python3-pyzo",
		    "buildsystem": "simple",
		    "build-commands": [
		        "pip3 install --no-index --find-links=\"file://${PWD}\" --prefix=${FLATPAK_DEST} pyzo"
		    ],
		    "sources": [
		        {
		            "type": "file",
		            "url": "https://files.pythonhosted.org/packages/d2/53/ac9dacfcb36e7ed772979f9fef2a8d93378da9ab0daf48541636a6400990/pyzo-4.5.1.tar.gz",
		            "sha256": "5a2813cb566d678806989d308c5421e2655a7e8cce36c50418a940ad145b5fad"
		        }
		    ]
		}
	]
}

```
To try it, you need to install flatpak and flatpak-builder on your distribution. 

Then you need the kde runtime : 
```
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub org.kde.Platform//5.10
flatpak install flathub org.kde.Sdk//5.10
```

Then you need to build the flatpak and create a repo by using the command line : 
```
flatpak-builder --repo=pyzo-repo python3-pyzo org.kde.python3-pyzo.json 
flatpak --user remote-add --no-gpg-verify --if-not-exists pyzo-repo pyzo-repo
flatpak --user install pyzo-repo org.kde.python3-pyzo
```
Eventually, to run it, you need to use the command line : 
`
flatpak run org.kde.python3-pyzo `

The only issue I'have seen is there are no desktop.file generated.
We should change a little bit the file architecture of the application to add this important functionality. 
http://docs.flatpak.org/en/latest/conventions.html#application-icons.

**Comment by almarklein** [comment]
I am open to adding files to the repo if that helps, just open a PR.

**Comment by lachhebo** [comment]
Hi, 

Last month, I have been taken by my exam. Today I worked a bit on the flatpak version of pyzo. Actually i did not have to modify the repository. I just needed to use some files on top of the targz  archive. 

I have made a repository in github for the flatpak package. 

> https://github.com/lachhebo/Flatpak-Pyzo

Try it, If you like it, I suggest we try to post it on flathub.

**Comment by almarklein** [comment]
Great! Thanks for the work!

How do you feel about moving it to githin.com/pyzo/Flatpak-Pyzo (and giving you full rights to that repo)?

> I suggest we try to post it on flathub.

Awesome!

**Comment by lachhebo** [comment]
Great, 

I have looked how to push a new applications into flathub here :  https://github.com/flathub/flathub

> Fork the Flathub repository on GitHub
> Clone the fork: git clone --branch=new-pr git@github.com:your_github_username/flathub.git
> Create a new branch with your app’s name: git checkout -b your_app_name
> Add your app’s manifest to the branch, commit it and push the commit
> Open a pull request against the new-pr branch on Github
> Your pull request will then be reviewed by the Flathub admins

I think you should fork the flathub repository inside  github.com/pyzo/flatpak-pyzo and give me full right to the repo, then i will push the manifest inside the github.com/pyzo/flatpak-pyzo repo and make a new pull request.

**Comment by almarklein** [comment]
Thanks. Done!

**Comment by lachhebo** [comment]
You're welcome, 

I have pushed a new branch Pyzo on the repository, and open a pull request. 
We will see how flathub maintainer and eventually how user react to this new of way to install Pyzo.

**Comment by almarklein** [comment]
Done! I plan to do a release soon. Let's see how this goes ...

**Comment by almarklein** [comment]
A release has been made (4.6.0) @lachhebo you care to update the flatpak?

**Comment by lachhebo** [comment]
hi, 

yes i will update it within the week
