### ISSUE TITLE
trying to make pyzo work by default in Winpython

### ISSUE THREAD

**Issue by stonebig** [pyzo/pyzo#537]
Hi,

I would like to have pyzo working out of the box in WinPython.
At the moment I understand that I need:
- to launch pyzo from %winpydir% directory,
- have a shell config pre-made pointing to ".\python.exe".

Question: where is hidden that shell config ?  (so I may pre-create it)

**Comment by almarklein** [comment]
The folder location of the setttings file (I think this is what you mean) can be seen in help > about Pyzo.

The portable settings folder might also be of interest: See https://github.com/pyzo/pyzo/blob/master/freezeScript.py#L262 and also the `_settings` folder in the binary version of Pyzo.

**Comment by stonebig** [comment]
ok, found. thank you very much.
