### ISSUE TITLE
ValueError: Text channel requires string messages.

### ISSUE THREAD

**Issue by ghost** [pyzo/pyzo#542]
(Ubunut 18.04) (Flask 1.0.2) (Python 3.6.5) (IPython 5.5.0) (Pyzo 4.4.3) (Qt 5.9.5) (PyQt 5.10.1)
Tried to run following code in Pyzo:

```
from flask import Flask

app = Flask(__name__)

@app.route("/")
def test():
  return "Test"
  
if __name__ == "__main__":
  app.run()
```

Get following error output
```
Traceback (most recent call last):
  File ~/hello_flask.py", line 11, in <module>
    app.run()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 938, in run
    cli.show_server_banner(self.env, self.debug, self.name, False)
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 629, in show_server_banner
    click.echo(message)
  File "/usr/local/lib/python3.6/dist-packages/click/utils.py", line 259, in echo
    file.write(message)
  File "/usr/share/pyzo/pyzo/yoton/channels/channels_file.py", line 148, in write
    self._channel.send( message[i:i+chunkSize] )
  File "/usr/share/pyzo/pyzo/yoton/channels/channels_pubsub.py", line 68, in send
    self._send( self.message_to_bytes(message) )
  File "/usr/share/pyzo/pyzo/yoton/channels/message_types.py", line 98, in message_to_bytes
    raise ValueError("Text channel requires string messages.")
ValueError: Text channel requires string messages.
```

This is not an issue with the code. This is an issue with Pyzo. The code ran successfully when run from the command line.

**Comment by almarklein** [comment]
I suspect that `click/utils.py` is writing directly to stdout, and is trying to send bytes over it. I think this can be considered a bug in `click`, or perhaps in `flask` though I suppose Python's original stdout file object allows it.

Ironically, the docs of `click.utils.echo()` say "has improved support for handling Unicode and binary data that does not fail no matter how badly configured the system is.". https://github.com/pallets/click/blob/master/click/utils.py#L167

I think it would be good to make an issue at the click repo. But first, let's be more sure. Could you debug this a bit, e.g. put `print(type(message))` at the top of `click.utils.echo()` to see whether this is indeed the case?

**Comment by almarklein** [comment]
I just looked into it. Things turned out to be more subtle/complex ...

Click is indeed trying to write bytes to stdout, but it does this because it tested whether stdout can write bytes or strings. It does this by trying to write `b''`. In our `FileWrapper` that we put at `sys.stdout`, we have a little chunking mechanism, which causes nothing to happen when zero bytes are being written, so we don't throw the error there :(

Anyway, it's Pyzo's fault. I apologize by suggesting the blame at `click`. It's fixed now.

**Comment by jmg-74** [comment]
Still got the same issue with 
(Mint 20 LTS based on Ubuntu 20.04 ) (Flask 1.1.2) (Python 3.8.2) (IPython 5.5.0) (Pyzo 4.4.3) (Qt 5.12.8) (PyQt5 5.14.1)

**Comment by almarklein** [comment]
> Pyzo 4.4.3

That version of Pyzo is from before this was fixed :)

**Comment by jmg-74** [comment]
Shame on me :-p thank you for being so kind in your answer ! Sorry for wasting your time...
(I re-installed Mint recently, so I thought I got a recent version and I didn't verify...)

**Comment by almarklein** [comment]
No problem :)
