### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by yltang52** [pyzo/pyzo#543]
I followed http://blogs.univ-poitiers.fr/laurentsignac/2013/09/01/sublime-dark-iep/ to change Pyzo into the dark theme. However, built-in functions like `open()`, `str()`, `int()`, and `float()` all appear black (on a dark background). How do I change their color?

Setting the following won't work:
    `S["Syntax.keyword"]`
    `S["Syntax.builtins"]`

Thanks.

**Comment by almarklein** [comment]
You found the solution? :)

**Comment by yltang52** [comment]
Yes, add the following:

S["Syntax.builtins"] = "fore:%s, bold:no, italic:no, underline:no" % lspink

**Comment by falconstryker** [comment]
This didn't work for me. What did was changing the color of an instance, so adding:
`S["Syntax.instance"]= "fore:%s, bold:no, italic:no, underline:no" % lsorange`
