### ISSUE TITLE
Pyzo 4.5.1 on Win 7 does not find Miniconda3

### ISSUE THREAD

**Issue by AxelBoldt** [pyzo/pyzo#548]
I followed the instructions on http://www.pyzo.org/start.html and installed Pyzo 4.5.1 and then Miniconda3-latest-Windows-x86_64.exe on Windows 7, accepting all defaults during installation. After start of Pyzo, I get the message "Pyzo detected a Python interpreter, but for scientific programming we recommend miniconda. If you want to manually specify the interpreter, set the exe in the shell config. Click one of the links above, or refresh."  Screenshot of the message is attached.

![pyzo screenshot](https://user-images.githubusercontent.com/8941698/43226911-7b4ebf12-905d-11e8-8c55-1562261a4dee.PNG)

**Comment by almarklein** [comment]
In it not unlikely that the conda team decided to put conda in another location. I think I have seen something similar recently. Will look into it.

In the meanwhile, you can edit the shell config to enter the path to Conda's python.exe there.

**Comment by almarklein** [comment]
@AxelBoldt do you know where miniconda installed Python? Just to make sure that it corresponds to what I've just tried.

**Comment by almarklein** [comment]
Basiclaly, Pyzo now checks the Windows-registry, and the directories here: 
```py
                    ['C:/', '~/',
                     'C:/program files/', 'C:/program files (x86)/', 'C:/ProgramData/',
                     '~/appdata/local/programs/python/',
                     '~/appdata/local/continuum/', '~/appdata/local/anaconda/',
                     ]
```

**Comment by AxelBoldt** [comment]
On my (German Windows 7) system, the Pyzo Shell configurations window shows in the exe box: "C:\ProgramData\Miniconda3\python.exe  [v3.6.5, conda]".

**Comment by almarklein** [comment]
Thanks for the quick reply @AxelBoldt. That directory was just added, so it should work in the next release. Thanks for reporting!
