### ISSUE TITLE
Find appropriate parser based on content for scripts with no extension

### ISSUE THREAD

**Issue by ysalmon** [pyzo/pyzo#555]
Currently, Pyzo detects which parser to use with the file name's extension.
This causes python scripts with no extension to have no syntactic coloration.

I think when there is no extension, Pyzo should inspect the file content to guess the appropriate parser. This can be done with the ```file``` utility is that is available, or simply by looking for a shebang in the first line and recognizing the interpreter's name.

**Comment by ysalmon** [comment]
Here is a PR #556 for this. I tested it locally, it seems to work.

**Comment by almarklein** [comment]
Fixed by #556
