### ISSUE TITLE
Menu entry to reload file / autoreload on external change

### ISSUE THREAD

**Issue by ysalmon** [pyzo/pyzo#558]
Greetings,
when working with version management systems like git, sometimes an opened file is modified by a checkout. In such a case, a menu entry to reload the file from disk would be nice.
A prompt to reload in case of external change would also be interesting.

**Comment by almarklein** [comment]
This should already work. If not, it's a bug (but it works for me all the time). The way it works now is that Pyzo will display a prompt when it detects that the file has been changed externally.

**Comment by almarklein** [comment]
That's really curious... what OS are you on?

It works consistently for me with Git checkouts. Here is a simple workflow that I just tried. Maybe I'm overseeing something?

* open `/some/file.py` in Pyzo.
* open it in anoether text editor, make a change, and save.
* Go back to Pyzo, as soon as the editor with that file become active, the prompt is shown.

**Comment by almarklein** [comment]
Actually, it should be (mostly) OS and file system independent, because it simply checks the mtime of the currently open file on a regular interval.

**Comment by ysalmon** [comment]
Indeed, it worked yesterday. I have to recall what I was doing when I thought it did not…
