### ISSUE TITLE
Invoking shell commands from Pyzo/IPython

### ISSUE THREAD

**Issue by ysalmon** [pyzo/pyzo#566]
Greetings,
I discovered that in the Pyzo (IPython) console, ```!``` allows to run a shell command and get its output as a list of strings. This in interesting. It can also be used in the following form for instance
```
files = !ls
```

I do not know if this is intended but I can see use cases for this.

However, could we impose a space before ```!``` and no space after ? Currently, ```files =! ls``` does the same, and it is a conceivable typo for ```files != ls``` which thus leads to very strange things for beginners.

It would also be nice to be able to optionally disable this or have a warning issued about what is happening (maybe just the first time in a session ?).

**Comment by almarklein** [comment]
Sorry, this is a feature handled by IPython.
