### ISSUE TITLE
starting with default OS language (if in the list of available)

### ISSUE THREAD

**Issue by stonebig** [pyzo/pyzo#567]
On Windows, at first start, would it be possible to guess the default langage of the operating system, and set the menus to that language ?

for example, if you start it on a french pc, menu would by default appear in french instead of english.

(or I missed something, and 'normal' pyzo does that)

**Comment by stonebig** [comment]
something like https://github.com/spyder-ide/spyder/blob/e7a862a1c4f1cfd54aae7a44efcab5f581d55ffa/spyder/utils/qthelpers.py#L110..L120  ?

**Comment by almarklein** [comment]
Makes sense!

**Comment by almarklein** [comment]
Makes sense!
