### ISSUE TITLE
Nested elements in Workspace

### ISSUE THREAD

**Issue by markuman** [pyzo/pyzo#571]
Nested elements are not browsable.

![nested](https://user-images.githubusercontent.com/3920157/47674605-fcb4b700-dbb7-11e8-809c-affd7037c84c.gif)

```
Python 3.7.1 (default, Oct 22 2018, 10:41:28) on linux (64 bits).
This is the Pyzo interpreter with integrated event loop for PYQT5.
Type 'help' for help, type '?' for a list of *magic* commands.
```

**Comment by ysalmon** [comment]
I believe this is not related to nesting but to the way the keys of a dict are enumerated (without square brackets and quotes in the case of string).

My PR #618 correctly manages the following
```
d = {"one" : [1,2,3], 4 : 6, frozenset({3}) : 45, (1,) : 0}
```
