### ISSUE TITLE
"edit shell configuration" doesn't seem to work on my PC

### ISSUE THREAD

**Issue by stonebig** [pyzo/pyzo#575]
well, it doesn't work even going back to pyzo-4.5.1 or to current master ... What could be a likely cause of this regression on my new PC ?

**Comment by almarklein** [comment]
Try removing (or better, renaming) the config file (see help > about for the application directory where the config file is).

**Comment by almarklein** [comment]
Odd ... did you recently install a new Python interpreter (of any kind)?  Pyzo tries to detect interpreters on your system when the shell config is loaded. It also tries to retrieve their versions, so something may be going wrong there ... Have you tried opening the logger shell to see if any errors are produced?

**Comment by almarklein** [comment]
(or running Pyzo from a terminal to capture any stdout)

**Comment by stonebig** [comment]
ok, will digg along these 2 ideas. thanks, Almar.

**Comment by hudcap** [comment]
I just started having this problem after installing a standard Python 3.7.2 environment alongside my Miniconda environment on Windows 10.
Pyzo version 4.7.1
Logger shows the following:

```
Uncaught Python exception: _getfullpathname: path should be string, bytes or os.PathLike, not NoneType
  File "C:\Program Files (x86)\pyzo\source\pyzo\core\menu.py", line 296, in <lambda>
    a.triggered.connect(lambda b=None: callback())
  File "C:\Program Files (x86)\pyzo\source\pyzo\core\menu.py", line 1088, in _editConfig2
    d = ShellInfoDialog()
  File "C:\Program Files (x86)\pyzo\source\pyzo\core\shellInfoDialog.py", line 607, in __init__
    self.interpreters = list(reversed(get_interpreters('2.4')))
  File "C:\Program Files (x86)\pyzo\source\pyzo\util\interpreters\__init__.py", line 27, in get_interpreters
    pythons = _get_interpreters_win()
  File "C:\Program Files (x86)\pyzo\source\pyzo\util\interpreters\__init__.py", line 89, in _get_interpreters_win
    found = [os.path.normcase(os.path.abspath(v)).strip('\\') for v in found]
  File "C:\Program Files (x86)\pyzo\source\pyzo\util\interpreters\__init__.py", line 89, in <listcomp>
    found = [os.path.normcase(os.path.abspath(v)).strip('\\') for v in found]
  File "C:\Python37\lib\ntpath.py", line 526, in abspath
```

Digging quickly through the code, it seems like this has something to do with the search for Python in the Windows registry, where some problem is causing the path to be returned as `None`.
I'd be happy to investigate further if someone can point me in the right direction.

**Comment by hudcap** [comment]
I dug a little more and found an empty version key (3.4) in my registry.
Deleting it solved the problem.
I'm not going to attempt a pull request because I can see different possible places/methods to handle it, but I believe the problem is that `get_interpreters_in_reg()` will return all versions, event empty ones, and then `_get_interpreters_win()` will add the empty install path to `found` on line 73, which then causes the error later.
HTH

**Comment by stonebig** [comment]
there is indeed no system python in my particular case, only the one currently use per pyzo.... shall be fixable

**Comment by stonebig** [comment]
maybe it's a matter of having one 'None' in the found list
````
['C:\\WinP\\bd37\\buPs2\\WPy64-3730\\python-3.7.3rc1.amd64', None, 'C:\\WinP\\bd36\\winpython-3.6.8-amd64\\python-3.6.8.amd64\\', None,
````

**Comment by stonebig** [comment]
ok, let me propose a patch

````
    found = [x for x in found if x ]
    # Normalize all paths, and remove trailing backslashes
    found = [os.path.normcase(os.path.abspath(v)).strip('\\') for v in found]
````

**Comment by almarklein** [comment]
Thanks @stonebig  and @hudcap !
