### ISSUE TITLE
new shell - bash (terminal)

### ISSUE THREAD

**Issue by markuman** [pyzo/pyzo#577]
I like to have also a bash / terminal inside pyzo. However, simply add a shell configuration with execute path `/bin/bash` failed.

![pyzoshell](https://user-images.githubusercontent.com/3920157/48400722-6fc93c00-e727-11e8-824e-156c1103405b.png)

Any idea how to realize that?

**Comment by almarklein** [comment]
The kernels are Python-only. Pyzo does not provide a terminal emulator. I fou really want it, my best bet would be to make a custom tool for it.
