### ISSUE TITLE
Cursor switches contexts when mouse-over scrolling

### ISSUE THREAD

**Issue by oaoutpost0** [pyzo/pyzo#579]
When I have the cursor in the shell, and then mouse over and scroll in the code editor without clicking, the cursor changes back to the code instead of staying the shell.

Os: Windows 10, 64 bit

**Comment by almarklein** [comment]
That is odd, not sure where to start looking. Could you check whether the shortcut for `view > select editor` is not set to something odd (default is Ctrl-9, F2)?

**Comment by oaoutpost0** [comment]
Yes, I have checked and they are at the defaults.

**Comment by almarklein** [comment]
I just checked more thoroughly:
* I can indeed reproduce this in the latest binary version (4.6.2)
* It is not present when I run Pyzo from source, also not if I point git to the snapsnot corresponding to v4.6.2.

This looks like a problem specific to either Qt (4.8.7 in the binary) or PySide (1.2.4). (I use Qt 5.11.1 with PyQt5 5.11.2 when running as source). I will update these the next that I do a release ...

**Comment by oaoutpost0** [comment]
Okay, great! I'll test it when there is a new update. :)

**Comment by almarklein** [comment]
Just tested:
* 4.6.2: issue is present
* 4.7.4: issue not present
* 4.8.0 (to be released today): not present
