### ISSUE TITLE
Add the poject root directory into `sys.paty` automatically

### ISSUE THREAD

**Issue by yltang52** [pyzo/pyzo#580]
I used to execute Python modules with `Run file as script` in Pyzo. Now I have a project with the following directory structure:

```
project/
    pa/
        a.py
    pb/
        b.py
```

In `b.py`, there is a `from pa import a` statement, which always crashes with the error message: `ModuleNotFoundError: No module named 'pa'`.

I noticed that whenever I `Run file as script` on `b.y`, `pb/` directory will be added to the `sys.path`. How do I make settings for `Run file as script` in order to add the project root directory (`project/`) into `sys.path` such that the `import` in `b.py` will work?

**Comment by yltang52** [comment]
I got it: just add the project directory to `pythonPath` in `Shell configuration.

**Comment by almarklein** [comment]
> just add the project directory to pythonPath in Shell configuration.

Yes, that should do the trick (and is perfectly fine).

So you have a module that you're also running as a script. I like that approach too, but sometimes its easier to put the script-part in a separate file, and place it outside of the library. If you place it in the root, then things just work.
