### ISSUE TITLE
Auto-close brackets and quotes missing from menu

### ISSUE THREAD

**Issue by hudcap** [pyzo/pyzo#582]
I updated to Pyzo 4.6.2 on Windows 10 64-bit.
The auto-close brackets and quotes option turned itself on.
I can't find either option in the menu. From what I can see in the code, it looks like it should be under Settings -> Autocompletion.
I am able to change the settings by entering:

    pyzo.config.settings.autoClose_Brackets = 0
    pyzo.config.settings.autoClose_Quotes = 0

**Comment by almarklein** [comment]
Yes, menu > Settings > Autocompletion > Auto close brackets (at the bottom).

**Comment by hudcap** [comment]
The menu items are missing for me.

**Comment by hudcap** [comment]
Pyzo version: 4.6.2 (binary)
Platform: win32
Python version: 3.4.5
Qt version: 4.8.7
PySide version: 1.2.4

Since you mentioned that, I checked the menu.py file in my installation, and lo and behold, those lines are missing.
I tried reinstalling using the Windows binary, but those lines are still missing.

**Comment by almarklein** [comment]
Wow, that's interesting. But above all, annoying. Glad you found the cause! And thanks for reporting back :)
