### ISSUE TITLE
Python 3.7.1 and Windows 10 gui failure

### ISSUE THREAD

**Issue by hudcap** [pyzo/pyzo#583]
I updated to python 3.7.1 on Windows 10.
When I open Pyzo, I get the following error in the shell:

    Python 3.7.1 | packaged by conda-forge | (default, Nov 13 2018, 19:01:41) on Windows (64 bits).
    qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "C:\Program Files (x86)\pyzo" even though it was found.
    This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
    
    Available platform plugins are: minimal, offscreen, windows.
    
    
    The kernel process exited. (3221226505)

I tried reinstalling Pyzo, but it didn't help.
With `QT_DEBUG_PLUGINS=1`, it looks like it's finding `qwindows.dll` in the Miniconda3 platforms folder, but gives the error

    QLibraryPrivate::loadPlugin failed on "C:/Users/[ME]/Miniconda3/Library/plugins/platforms/qwindows.dll" : "Cannot load library C:\\Users\\[ME]\\Miniconda3\\Library\\plugins\\platforms\\qwindows.dll: The specified procedure could not be found."

For now, I switched the gui to Tk, which works.

Any ideas?

**Comment by hudcap** [comment]
I uninstalled Miniconda3 and reinstalled, but it still didn't work.
Then at some point in middle of reinstalling packages, it started working again.
Not sure exactly when, or which packages fixed it.
Not complaining, but ¯\_(ツ)_/¯

**Comment by almarklein** [comment]
Glad to hear it "fixed itself". Sorry to hear that this kind of stuff still happens :(
