### ISSUE TITLE
Date/version on Flathub not in line with release notes

### ISSUE THREAD

**Issue by btreut** [pyzo/pyzo#584]
Info page on [flathub](https://flathub.org/apps/details/org.pyzo.pyzo) has Feb, 14th, 2018 as last update date for 4.6.1, but [release notes](https://github.com/pyzo/pyzo/wiki/Release_notes) have Oct. 19th, 2018 and Feb, 14th, 2018 correspoding to 4.5.1.

What is correct?

**Comment by almarklein** [comment]
cc @lachhebo who maintains the flatpack distribution. If you install the flatpack and go to help about, what version does it say? Maybe the flatpack was updated and the date was forgotten?

**Comment by almarklein** [comment]
Thanks!
