### ISSUE TITLE
Code analysis and occurrence highlight

### ISSUE THREAD

**Issue by kklmn** [pyzo/pyzo#585]
Hi,

1. I see that people have already asked for occurrence highlights, e.g. at [#148](https://github.com/pyzo/pyzo/issues/148) and [#309](https://github.com/pyzo/pyzo/issues/309). And I see the issues are closed (the links in them are dead though), so I assume the feature is available. Where can I enable it?

2. Real-time code analysis (by pyflakes) would be also nice. Any plans for it?

**Comment by almarklein** [comment]
1. Select a word. All occurrences are marked yellow.

2. Well, there have been plans for that for quite a while. It is one of a collection of things that I'd like to see improved, and that I feel should probably be done in one big overhaul. Say a Pyzo 5. So far I've not been able to allocate the time for this. And I also don't have a clear enough picture yet of what it should look like.

**Comment by kklmn** [comment]
> 1. Select a word. All occurrences are marked yellow.
No, they are not.
![image](https://user-images.githubusercontent.com/17322580/52747409-fe2db200-2fe3-11e9-9930-5c1e9bd30b64.png)
version 4.6.1. Windows 10, if this matters

**Comment by almarklein** [comment]
That's not selecting :P  Try double-clicking on a word.

**Comment by kklmn** [comment]
ok, I see. It works indeed. I have it different in my previous (current) IDE. There it is active by just landing the cursor.
Thanks
