### ISSUE TITLE
Please add a default install_requires otherwise mac install show 'No module named 'PySide''

### ISSUE THREAD

**Issue by lishoujun** [pyzo/pyzo#586]
Hi there, pyzo is a good mini ide for me.
In mac I use pip install pyzo to install ,but when I run pyzo,it shows 
'ModuleNotFoundError: No module named 'PySide''
then I install  PySide it shows 
'only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]'

finaly i install PySide2 by a web search.
I think it should have a default install_requires if none of 'PySide' or 'PySide2' or 'PyQt5' or 'PyQt4' are installed like this  https://stackoverflow.com/a/49338206

**Comment by almarklein** [comment]
Have you tried installing PyQt5?

**Comment by lishoujun** [comment]
no I search PySide find PySide2 will work，  so just install PySide2

**Comment by almarklein** [comment]
Ok, thanks for the info. But we cannot add a requirement, because Pyzo is supposed to work with either Qt backend, and forcing the installation of one will cause conflicts with the others.
