### ISSUE TITLE
Second monitor and dark mode in macOS Mojave

### ISSUE THREAD

**Issue by Vic3198** [pyzo/pyzo#593]
Hi,
I use Pyzo everyday on Mac, and there are two little things that would make Pyzo experience even better:
  •  Make Pyzo compatible with macOS 10.14 Mojave dark mode. Having a dark interface is highly eyes-resting!
  • Add the ability to split editor, shell, and other tools into separate windows that can each be put in full-screen on separate monitors

Thanks,
Vic

**Comment by almarklein** [comment]
The upcoming release (should be within a week, as soon as I have my OS X VM sorted) will have different themes for syntax highlighting. I am not sure how well the widget backgrounds would be coloured along with the native theme. But we make use of PyInstaller now, which should be our best bet on getting good integration with native themes.

Separate windows is probably not going to happen soon though.
