### ISSUE TITLE
Using pygments for pyzo's syntax coloring

### ISSUE THREAD

**Issue by edreamleo** [pyzo/pyzo#598]
Hello Almar,

I emailed you this at almar@www.almarklein.org, but the email bounced.

I've recently added support for pygments to Leo. Something similar could *easily* be added to pyzo.

The [qtconsole package from Jupyter](https://github.com/jupyter/qtconsole/tree/master/qtconsole) teaches how to do most of the job. Jupyter's [pygments_highlighter.py](https://github.com/jupyter/qtconsole/blob/master/qtconsole/pygments_highlighter.py) contains the code. The PygmentsBlockUserData class monkey-patches QTextBlockUserData in order to save state.  QSyntaxHighlighter.highlightBlock uses that state.

Leo's PygmentsColorizer.mainLoop method is a repackaging of highlightBlock.  It elegantly fixes an apparent qtconsole bug so that multi-line tokens are colored properly.

It is easy to add add coloring for Leo's additional syntax for *all* pygments' lexer classes.  It would be just as easy to add coloring for pyzo cells.  Something like this:
```python
def patch_lexer(self, language, lexer):
    class PatchedLexer(lexer.__class__):
        tokens = {
            'root': [
               << regex describing pyzo cell >>
               inherit,
            ],
        }
    return PatchedLexer()
```

All the Leo code is in [leoColorizer.py](https://github.com/leo-editor/leo-editor/blob/devel/leo/core/leoColorizer.py), best viewed with Leo. I'll be happy to discuss this further if you are interested.

Edward

**Comment by almarklein** [comment]
Thanks! I've been wanting to make use of Pygments for a few years :)  but at the same time I'd like to use the same parser to generate the content of the source structure. So far I've not found the time to take this on...

**Comment by edreamleo** [comment]
On Thu, May 16, 2019 at 8:03 AM Almar Klein <notifications@github.com>
wrote:

> Thanks! I've been wanting to make use of Pygments for a few years :) but
> at the same time I'd like to use the same parser to generate the content of
> the source structure. So far I've not found the time to take this on...
>

You're welcome.

Edward
