### ISSUE TITLE
FYI: Using pyzo's best features in Leo

### ISSUE THREAD

**Issue by edreamleo** [pyzo/pyzo#599]
As a courtesy, I want to tell you about a project that promises to greatly improve [Leo](http://leoeditor.com/). The idea is simple: **bring pyzo's best features into Leo**. For latest details, see posts on [Leo's forum](https://groups.google.com/forum/#!forum/leo-editor).

Please let me know immediately if you have any concerns about this project.

~You can see the the present state of the project by running Leo from [Leo's pyzo branch](https://github.com/leo-editor/leo-editor/tree/pyzo) with the --pyzo command-line option.~ **Update**: the prototype code in the pyzo branch has been abandoned.

**Benefits to Leo**

- Much better handling of the Leo's main window. ~Leo's component windows will be pyzo tools. Leo's users will be able to drag Leo's tool windows around, and Leo will restore the location of those windows when Leo starts up.~ **Update**: Leo may eventually use a QDockWidget, but that project will have nothing to do with pyzo.

- Leo will have access to ~all of~ some of pyzo's cool tool windows, especially the file browser and Shell windows, and *all the features they provide*. **Update**: Leo will host these tools in Leo's tabbed Log pane.

**Discussion**

**Update**: I prototyped basing Leo on pyzo's startup code.  That prototype has been abandoned. Instead, Leo will remain *exactly* as it has always been, except for one or two new pyzoic panes in Leo's tabbed Log pane.

~Almost all the pyzo-related code is in [pyzo_shims.py](https://github.com/leo-editor/leo-editor/blob/pyzo/leo/core/pyzo_shims.py), best viewed with Leo. Except for over-rides of the `__init__` and `_populate` methods of pyzo's MainWindow class, Leo accesses pyzo's code *only* via imports.~ **Update**: All pyzo-related work is now in Leo's **pyzo_support.py** plugin.

~pyzo_shims.py~ pyzo_support.py contains the pyzo copyright at the top.  I will fully and gratefully acknowledge you and pyzo in Leo's docs.

**Comment by edreamleo** [comment]
**Additional notes**:

1. [pyzo.leo](https://github.com/leo-editor/leo-editor-contrib/blob/master/StudyOutlines/pyzo.leo) in [leo-editor-contrib](https://github.com/leo-editor/leo-editor-contrib) contains a "live" view of pyzo's sources. I have used it mostly to add exploratory traces.  This resides in my personal [pyzo repository](https://github.com/edreamleo/pyzo). This repo exists only to track changes.  It will never be incorporated anywhere else.

    This pyzo repo patches pyzo to use a dark theme.  It's at rev 043e438b7, which supports a new 'dark_background' setting. Oh yes, there is an additional override: MainWindow.setStyleSheet. Iirc, this avoids a flash when using a dark background. Anyway, these patches will find their way into leo_shim.py, not pyzo.

2. Unlike typical Leonine usage, [leoPyRef.leo](https://github.com/leo-editor/leo-editor/blob/pyzo/leo/core/LeoPyRef.leo) in [Leo's pyzo branch](https://github.com/leo-editor/leo-editor/tree/pyzo) contains my *personal, local* version of Leo's sources.  This is safe because there will never be a need to merge two different versions of this .leo (xml) file.  The commits involving LeoPyRef.leo have the checkin message "Looking over my shoulder" so that anyone can see all my nodes, which naturally include copious numbers of clones.

**Comment by almarklein** [comment]
Thanks for the heads-up :) Good to see that things like the file explorer make their way into other projects.

**Comment by edreamleo** [comment]
On Thu, May 16, 2019 at 8:01 AM Almar Klein <notifications@github.com>
wrote:

> Thanks for the heads-up :) Good to see that things like the file explorer
> make their way into other projects.
>
Glad to hear you approve.

Edward

**Comment by edreamleo** [comment]
I have abandoned this projects, for the reasons given in [this post](https://groups.google.com/d/msg/leo-editor/fVGuU2XzqjU/hqdgJ3TxBAAJ).  To summarize: anyone can get the benefits of both pyzo and Leo by running them side by side.

**Comment by almarklein** [comment]
I see your point, good luck with developing Leo to be Leo :)

**Comment by edreamleo** [comment]
Heh.  I'm now officially dithering, once again, about adding pyzo features to Leo.  See [this post](https://groups.google.com/d/msg/leo-editor/fVGuU2XzqjU/ZKOeTslOAQAJ).
