### ISSUE TITLE
source structure does not list some functions

### ISSUE THREAD

**Issue by iraytrace** [pyzo/pyzo#601]
Source Structure panel may not display all valid functions in a source module.  The text below (available [here](https://github.com/pyzo/pyzo/files/3041751/asdf_py.txt) as asdf_py.txt which should be renamed to asdf.py after download) demonstrates the issue.

    def pyzo_shows_me_in_structure():
         pass

    def pyzo_does_not_show_me_in_structure(c: float,
        n: float,
        quad_edge_length: float,
        value: float,
        low=0.0,
        span=1.0):
            pass

    def i_have_same_args_and_i_am_in_structure(c: float, n:float,
        quad_edge_length: float, value: float, low=0.0, span=1.0):
            pass

This displays in pyzo as the following:

![pyzo_bug](https://user-images.githubusercontent.com/3651273/55529551-f0092300-566f-11e9-936e-e02dc8d90baf.PNG)

Note that the function 'pyzo_does_not_show_me_in_structure' is not present in the Source Structure view.  This was observed with pyzo 4.7.3 on Windows 10.

**Comment by almarklein** [comment]
Thanks for the report! Yes, this is a known issue, but it was not on the issue tracker yet. This needs to be addressed for the next release.

**Comment by almarklein** [comment]
This is because of the way that the source parser works. It would need a proper refactoring (make it use of sphinx, for instance) to fix it proper, but for now I've increased a counter so it will only fail for function defs spread over more than 16 lines.
