### ISSUE TITLE
No themes available

### ISSUE THREAD

**Issue by yltang52** [pyzo/pyzo#602]
Just downloaded and installed pyzo 4.7.3 on Windows, and there are theme options from Settings > Edit syntax styles.

However, on Ubuntu 18.04, pyzo upgraded with `sudo python3 -m pip install pyzo --upgrade` has no theme options.

How do I get the themes on Ubuntu?

**Comment by almarklein** [comment]
Thanks for the heads-up! There was a line missing in `setup.py` to make the themes be packed in the source distribution. I just fixed it and pushed a new release.
