### ISSUE TITLE
Setting > Edit Syntax style: the "Save" button is always grayed out

### ISSUE THREAD

**Issue by yltang52** [pyzo/pyzo#609]
The title says it all: unable to change the style.

Ubuntu 18.04
Pyzo version: 4.7.4 (source)
Platform: linux
Python version: 3.6.7
Qt version: 5.9.5
PyQt5 version: 5.10.1

**Comment by almarklein** [comment]
IIRC it wont let you override the builtin styles; you need to create a new style. That said, I understand that this is confusing and needs some work to make this more clear.

**Comment by yltang52** [comment]
BTW, it is time to do the add more translation?

**Comment by almarklein** [comment]
> BTW, it is time to do the add more translation?

Yeah, I've been a bit lazy with contacting the translaters lately. New translations are welcome anytime :)
