### ISSUE TITLE
Unify and reduce margins

### ISSUE THREAD

**Issue by kelsa-pi** [pyzo/pyzo#627]
Margins between gui elements editor, shell, logger and plugins are not consistent  as shown in the image below. Second, they are to thick IMHO. 
My suggestion is to unify and reduce margins. It would increase screen real estate and improve look & feel (for me anyway). I guess this can be done by config option/s.

Image description:
Left - current margins, setContentsMargins(0,0,0,0) and setContentsMargins(4,4,4,4), for more details [pyzo search](https://github.com/pyzo/pyzo/search?q=setContentsMargins&unscoped_q=setContentsMargins)
Right - very exaggerated example, unfied and reduced margins for editor, shell, logger and plugins ( setContentsMargins(0,0,0,0) )

![margins](https://user-images.githubusercontent.com/19865053/62395617-1e8d0100-b571-11e9-894f-7705b1c53a9f.png)

**Comment by almarklein** [comment]
Making the margins more consistent would certainly be a good idea. I'm not sure if I'd want them to be much smaller; it does give a bit of extra space, but it also makes it feel more "cramped".

**Comment by almarklein** [comment]
Fixed by #629
