### ISSUE TITLE
FYI: Leo and pyzo redux

### ISSUE THREAD

**Issue by edreamleo** [pyzo/pyzo#632]
I have restarted plans to embed significant parts of pyzo into Leo. Leo's **[pyzo_in_leo plugin](https://github.com/leo-editor/leo-editor/blob/pyzo/leo/plugins/pyzo_in_leo.py)**, contained in [Leo's pyzo branch](https://github.com/leo-editor/leo-editor/tree/pyzo), contains the code. It is remarkably simple. [Leo issue #1093](https://github.com/leo-editor/leo-editor/issues/1093) contains an overview of all pyzo-related projects in Leo.

I have discussed all my plans and discoveries re pyzo at [Leo's forum](https://groups.google.com/forum/#!forum/leo-editor). This issue is a distillation of several month's posts.

**Adapting Leo to Pyzo**

Leo 6.0 uses Qt docks by default. This had nothing to do with pyzo, but was a precondition for all pyzo-related work.  [Leo issue #1289](https://github.com/leo-editor/leo-editor/issues/1289) suggests using singleton docks. Again, this has nothing to do with pyzo, but is a necessary precondition for further work.

**Adapting Pyzo to Leo**

Aha! **Leo must *not* call pyzo.start!** This avoids unwanted side effects. Instead, the plugin calls **pyzo_start**, a copy of pyzo.start adapted for Leo. Described [here](https://groups.google.com/d/msg/leo-editor/jIloLkjyCF8/ySVZh0pZDAAJ) and [here](https://groups.google.com/d/msg/leo-editor/jIloLkjyCF8/C7XeAtV2DAAJ).

Aha! **pyzo_start must init pyzo in *exactly* the same order as pyzo.start**. This new clarity yielded [rapid progress](https://groups.google.com/d/msg/leo-editor/Dz_KECGA4Y4/YbLArlwsDQAJ).

The present code contains only one real monkey patch.  Changes and additions to pyzo_start become de-facto monkey-patches.  It's really really easy.

**Code reuse**

Any dev who want to use pyzo's code should be aware of the Aha's described above.

The leo/plugins/pyzo folder will contain a full copy of pyzo.  This ensures that Leo's users can use pyzo's features without installing pyzo.  It fully resolves a long-standing question involving use-by-copy vs use-by-import.  The present code gets the best of both approaches. 

At the code level, pyzo.config is probably the single biggest obstacle to reusing code.  It's not a show stopper, but it implies significant munging of code.  At a design level, even reusing the Pyzo File Browser will require significant adaptation for most apps.  For example, Leo's environment is significantly different from pyzo's.

**Summary**

Adapting Leo to pyzo carries little risk because the work is valuable on its own.

The breakthroughs described above significantly reduce the risks involved in the Pyzo-in-Leo project. Much work remains, but imo this project is worth any amount of effort.

All questions and comments welcome.

**Comment by almarklein** [comment]
Thanks for the update :)

**Comment by edreamleo** [comment]
On Tue, Aug 27, 2019 at 4:40 AM Almar Klein <notifications@github.com>
wrote:

> Thanks for the update :)
>
You're welcome.

Edward
