### ISSUE TITLE
Release ?

### ISSUE THREAD

**Issue by ysalmon** [pyzo/pyzo#633]
Would it be possible to integrate the various improvements to Pyzo into a new release ? In teaching environments, we may still be able to upgrade in time for _la rentrée_ (2 september) where system admins are responsive, but in any case they would require a release with an executable setup program and so on.

**Comment by almarklein** [comment]
Yes, let's do a release early next week!

**Comment by almarklein** [comment]
Done!

**Comment by ysalmon** [comment]
Great, tested it : I was over-precise at some point and the Qt from Debian 9 does not like this. See #636

**Comment by almarklein** [comment]
Will do a minor-release and push to pypi, new binaries should not be needed.

**Comment by almarklein** [comment]
done :)

**Comment by ysalmon** [comment]
You tagged it v0.8.1 instead of v4.8.1 and it shows out of place in [releases](https://github.com/pyzo/pyzo/releases).

**Comment by almarklein** [comment]
Nice catch. Fixed.

**Comment by ysalmon** [comment]
Also, the 4.8.1 release does not present tar.gz for Linux or MacOS or Windows, and the 4.8.0 contains the faulty code base. I agree the "freeze" part does not need to be updated but one still needs to have a release with the correct .py files.

**Comment by ArchangeGabriel** [comment]
@ysalmon Source tar.gz is available at https://github.com/pyzo/pyzo/archive/v4.8.1.tar.gz.

Binaries for 4.8.0 are identical to 4.8.1, so rebuilding is a bit pointless. Just use 4.8.0 if you are using pre-built binaries.

**Comment by ysalmon** [comment]
I know. I am talking about other people not as up-to-date as to how Pyzo works. They will go to https://pyzo.org/start.html, download the relevant file for their OS and get 4.8.0, they will untar and run it and, assuming they are with a system that is affected by the problems fixed in 4.8.1, Pyzo will crash. Not good.

**Comment by ArchangeGabriel** [comment]
AFAIU, this cannot be the case. The prebuilt binaries are not depending on an external Qt or Python but instead are statically compiled against those dependencies, which means they cannot be affected by the bugs.

The bugs are only affecting those trying to compile from source against old version of Python and Qt, e.g. Debian users or RHEL-based distros ones.

**Comment by almarklein** [comment]
@ysalmon do you mean that someone downloads the binary and then `cd`'s into the source directory that it contains, and runs the source using the system's Python?

**Comment by ysalmon** [comment]
No, they will run the pyzo binary. But this will run the source, including pyzoInteractiveHelp.py and the version of that file shipped with 4.8.0 crashes on Debian 9 (with ``PreferSystem = yes`` in ``qt.conf``if that matters).

**Comment by almarklein** [comment]
Ok, so if I create a Linux binary for 4.8.1 and update the website to link to it, we should be fine, right?

**Comment by ysalmon** [comment]
For Linux yes. For other OSs I do not know — does the Windows release embed its own Qt ?

**Comment by almarklein** [comment]
I'm pretty sure it does, but the Linux version does too...

**Comment by almarklein** [comment]
> with PreferSystem = yes in qt.confif that matters

I think that makes all the difference. What `qt.conf` is that? Did you change the one in the Pyzo root dir?

**Comment by ysalmon** [comment]
Forget it : I had in my deployment script a very old instruction to uncomment the PreferSystem line in pyzo's qt.conf. But pyzo 4.8.0 does not ship that file so my script is now a NOP in that regard.

Plus, I just tested the 4.8.0 binary release on my system : it crashes too, so in fact the problem is not related to Debian 9 having an old Qt as I thought but to the pyzo binary itself. Running ``source/pyzo/__init__.py`` works.

What is at fault is a bad interaction between the binary pyzo and the source.

**Comment by ysalmon** [comment]
I made tests on virtual machines with Win7 and Win10 : things seem to work correctly there so indeed there is no need for an update for these OSs. But there is for Linux.

**Comment by almarklein** [comment]
I re-build the binary for Linux and updated the links on the website.
