### ISSUE TITLE
Could not bind to any of the 32 ports tried.

### ISSUE THREAD

**Issue by damianquijano** [pyzo/pyzo#634]
Does not load console.
My laptop is WIndows 10, 64bit. I tried pyzo-4.6.2-win32 portable and pyzo-4.7.3-win64-windows10.exe.
![image](https://user-images.githubusercontent.com/1993091/63649066-8bbe2d00-c6fe-11e9-9a68-30d947577101.png)

damianquijano@gmail.com
------------------------------------------------------

![image](https://user-images.githubusercontent.com/1993091/63649074-a55f7480-c6fe-11e9-985d-11293a0238fd.png)

----------------------------------------
![image](https://user-images.githubusercontent.com/1993091/63649079-db045d80-c6fe-11e9-958d-754123218d2d.png)

---------------------------------

![image](https://user-images.githubusercontent.com/1993091/63649082-e6578900-c6fe-11e9-9923-0f1df5f80d4d.png)

**Comment by almarklein** [comment]
Hi, could it be that you have a rather strict firewall that is preventing the kernel and IDE to connect? If so, please add an exception.

**Comment by almarklein** [comment]
> Before the recent Windows 10 updates, it worked fine.

That is interesting ... this code has been unchanged for many years. Maybe *some* program now happens to use many ports in the same port range.

**Comment by almarklein** [comment]
In `pyzo/core/kernelbroker.py` at line 438, you can try to increase the `max_tries`. This is not a proper fix, I suppose, but it will help determine whether it's blocked because other programs already use all 32 ports, or something else.

**Comment by damianquijano** [comment]
> In `pyzo/core/kernelbroker.py` at line 438, you can try to increase the `max_tries`. This is not a proper fix, I suppose, but it will help determine whether it's blocked because other programs already use all 32 ports, or something else.

Nothing, I tried with 64, error: " not bind to any of the 64 ports tried."

**Comment by almarklein** [comment]
What about changing ":PYZO+256" to just "PYZO"? I have a feeling that the whole port range is somehow blocked on your machine.

**Comment by damianquijano** [comment]
> What about changing ":PYZO+256" to just "PYZO"? I have a feeling that the whole port range is somehow blocked on your machine.

Wuaooo...working!. 
#c = self._context.bind(address+':PYZO+256', max_tries=64)  replaced by
 c = self._context.bind(address+':PYZO', max_tries=64)  
Let's see if it is a stable solution. I need to understand how it  process sockets, thank you very much.

**Comment by damianquijano** [comment]
Sorry my very bad english.

**Comment by damianquijano** [comment]
I have to clarify, that I used the portable (zip) version pyzo-4.7.3-win64.zip, that way I can access the source. I imagine that with the installable .exe it is not so simple, although I tried from the configurations folder.

**Comment by almarklein** [comment]
> Wuaooo...working!.

Great! Could you do me a favor and get an estimate on what number of the `+xxx` part the connection will fail? I'm not sure if your case translates to other potential users, but if it does, it would be good to have a better understanding :)

> I imagine that with the installable .exe it is not so simple

The application has the same files, but since its usually installed in a special folder where you need admin privileges to install files, it's harder. Otherwise it's the same.

**Comment by damianquijano** [comment]
> > Wuaooo...working!.
> 
> Great! Could you do me a favor and get an estimate on what number of the `+xxx` part the connection will fail? I'm not sure if your case translates to other potential users, but if it does, it would be good to have a better understanding :)
> 
> > I imagine that with the installable .exe it is not so simple
> 
> The application has the same files, but since its usually installed in a special folder where you need admin privileges to install files, it's harder. Otherwise it's the same.

OK: fail with ":PYZO+256"     

For now it works well. I have another computer with Windows 10 without update, and it works fine. I will do the update and see if it fails again.

**Comment by almarklein** [comment]
Closing this - fixed in #646. I'm leaving the duplicate issue #644 open for the time being.
