### ISSUE TITLE
Black artifact windows triggered by menu tooltips

### ISSUE THREAD

**Issue by Tontyna** [pyzo/pyzo#638]
On Windows 7 (when using a 64bit Pyzo with PyQt5) annoying black rectangular artifacts pop up 
when hovering menu items providing a tooltip. Modal windows that stay on top system-wide. Almost invisible when they manage to collapse to a small black line -- but sometimes they occupy a square of about 190x160 pixels.

Inspired by #399 I tweaked the environment variable `QT_GRAPHICSSYSTEM`. But to no avail. 

Hence I suspect this issue isn't related to the graphics mode but to the way how tooltips for menu items are created.

Only workarounds so far:

- Use keyboard to select a menu item.
- Slow down when clicking/hovering menu items. Let the artifacts flicker until they collapse to a minuscule black line.

**Comment by almarklein** [comment]
I can reproduce the black squares appearance for the Windows7 build. It seems to be specific to this build and I have no idea why it's there or how to get rid of it. You could play with (or just disable) the code here: https://github.com/pyzo/pyzo/blob/master/pyzo/core/menu.py#L55

**Comment by Tontyna** [comment]
Will play with the Pyzo code, but I don't think it can be fixed within Pyzo -- I mean: What can you do to display a tooltip but calling `QtWidgets.QToolTip.showText()`?

I already compared the Qt4 and Qt5 `qtooltip.cpp` source -- didn't enlight me, no relevant changes. Maybe it's related to a change deep inside Qt5, the way how they provide the parent window instance for modal windows (cf. https://forum.qt.io/topic/73576/qt5-can-tooltip-popups-be-prevented-from-raising-the-window). Can't help but thinking that the black artifact is a workaround, a dummy parent window because maybe the submenu items lack an appropriate handle. Not being a C++ programmer I finally gave up to find the place where the tooltip window actually is created.

BTW: I use the ZIP distributions of Pyzo, not the installer, so no special "Windows7 build" here.

**Comment by almarklein** [comment]
> Will play with the Pyzo code, but I don't think it can be fixed within Pyzo -- I mean: What can you do to display a tooltip but calling QtWidgets.QToolTip.showText()?

Well, there is some code there (in Pyzo) because tooltips dont display by default in Qt menu's apparently. Worst case, you an disable them there.

> BTW: I use the ZIP distributions of Pyzo, not the installer, so no special "Windows7 build" here.

Ah, you're running from source? Interesting, because I see the same black rectangles on Win10 if using the win7 build. Perhaps its some interplay between Qt and Windows window manager...

**Comment by Tontyna** [comment]
I **love** ZIP distributions!
 
What's special about the Windows 7 build?

**Comment by almarklein** [comment]
Wait, what zip distribution do you mean? Do you run from source or are you using `pyzo-4.8.0-win64.zip`?

**Comment by Tontyna** [comment]
I am using `pyzo-4.8.0-win64.zip`

Also using `pyzo-4.7.0-win64.zip`, `pyzo-4.6.0-win32.zip` etc.

And yes, the black boxes appear on my Windows 10 system too.

**Comment by almarklein** [comment]
Ah, that's basically the Windows 10 build then :)  But you'r right, it's present there as well. Looking closely, I think I can even see the black squares sometimes, very briefly, when running from source. For some reason they are present much longer in de binary build. And apparently sometimes stick :(

I guess we should find a better way to display these tooltips. Or even consider hiding them might be better ...

**Comment by Tontyna** [comment]
> I think I can even see the black squares sometimes, very briefly, when running from source.

Can confirm this when running from source (master branch, PyQt/Qt 5.12.1) on Windows 7.

Wenn switching to latest PyQt/Qt 5.13.0, I'm unable to see squares any more. Only flickering lines -- unless you know what to look for you might overlook them. Maybe my eyes are too slow, maybe Riverbank improved Qt -- but definitely I cannot produce sticking squares when running from source. Arising the question: What happens inside PyInstaller?

Now that I managed to run Pyzo from source  I'll play a bit with the source... Wow! It's even possible to run & debug Pyzo within Pyzo!

BTW: Forgot to mention that Pyzo is great :heart:

**Comment by almarklein** [comment]
> Wenn switching to latest PyQt/Qt 5.13.0, I'm unable to see squares any more.

Interesting. I actually tried to update PyQt on the build machine, but then the binary was broken so I reverted. I guess its worth investigating though ... or maybe switch to PySide ...

**Comment by Tontyna** [comment]
> tooltips dont display by default in Qt menu's apparently

But since Qt 5.1. there is [`QMenu.toolTipsVisible`](https://doc.qt.io/qt-5/qmenu.html#toolTipsVisible-prop). No need to `menuBar.hovered.connect(onHover)`, instead `self.setToolTipsVisible(True)` in `Menu.__init__()` and finally (additionally to)  `setStatusTip` a call to `setToolTip` with the appropriate `tt`.

And the black boxes disappear. At least I can't spot them any more.

Of course, not an option (and not required) when Qt4 is used.

**Comment by Tontyna** [comment]
> or maybe switch to PySide2

Tried running (from source) with PySide2, too. Everything seems to be okay until I close Pyzo --  the famous Windows fatal error dialog "Python has stopped working -- Check online|Close|Debug") pops up -- I remember there was a reason and a fix for this one...
