### ISSUE TITLE
Best practice for determining script location

### ISSUE THREAD

**Issue by maphew** [pyzo/pyzo#642]
I use the idiom of `here = path.abspath(path.dirname(__file__))` to get path of currently running file a lot. It's widely used, the PyPa packaging tutorial for example. Ufortunately it doesn't work in Pyzo's shells:

~~~
>>> (executing file "__init__.py")
Traceback (most recent call last):
  File "C:\Users\mattw\code\utils\winfolders\winsf\__init__.py", line 43, in <module>
    here = path.abspath(path.dirname(__file__))
NameError: name '__file__' is not defined
~~~

I've worked around it by using a `try: except NameError` block to catch the error and define a hardcoded path on my dev machine but I'd like a solution that's portable for other devs. What do you suggest?

**Comment by almarklein** [comment]
It *does* work when you're running a file as a script. Because in that case there is a clear entry point. 

When the Pyzo shell just starts up, no script has run, so there is no file to set `__file__` for. So in this case Pyzo mimics the behavior as the standard Python prompt.

So in terms of best practices, use *run as script* when that script needs resources relative to its location.

**Comment by maphew** [comment]
I get syntax errors with _run as script_.  The shell is from a miniconda env with very little installed (python, win32com). From the leading `%` I'm guessing this feature requires ipython?

In the opening post the error is after pressing `F5` to run the code. I'm not sure which item in the Run menu that corresponds to, if any.

~~~
Python 3.7.4 (default, Aug  9 2019, 18:34:13) on Windows (64 bits).
This is the Pyzo interpreter with integrated event loop for ASYNCIO.
Type 'help' for help, type '?' for a list of *magic* commands.

>>> %cd "c:\users\mattw\code\utils\winsf\winsf"
  File "<console>", line 1
    %cd "c:\users\mattw\code\utils\winsf\winsf"
    ^
SyntaxError: invalid syntax

>>> %run -i "C:\Users\mattw\code\utils\winsf\winsf\__init__.py"
  File "<console>", line 1
    %run -i "C:\Users\mattw\code\utils\winsf\winsf\__init__.py"
    ^
SyntaxError: invalid syntax
~~~

**Comment by almarklein** [comment]
Try disabling "use IPython if available" in the shell config. The way that run as script works is different if you're using IPython. I now suspect that it only looks at that checkbox, not whether IPython is actually available. If this is the case it must be fixed.

**Comment by maphew** [comment]
Ah yes, after unchecking that option _Run as script_ works and I can remove my workaround. Thanks!

**Comment by almarklein** [comment]
The checkmark should now not matter. The IDE correctly checked whether the kernel reports using IPython or not, but the kernel did not set that flag correctly. This is now fixed via
https://github.com/pyzo/pyzo/commit/7cec0a56418c8003ea88392f890871d496f4ce5c
