### ISSUE TITLE
Warn when loggin.basicConfig() is used

### ISSUE THREAD

**Issue by maphew** [pyzo/pyzo#645]
```
# pyzo-test-logger.py
import os
from datetime import date
import logging

logfile = "test.log"
logging.basicConfig(filename=logfile, level=logging.DEBUG)

logging.debug(f"Logfile for {date.today()} [{(os.path.abspath(logfile))}]")

logging.info("this is an info line")
logging.warning("this is a warning line")
logging.debug("this is a debug line")
```

Load into Pyzo 4.8.0 for Windows and press F5 or Ctrl-Shift-E:

```
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 22:01:29) on Windows (64 bits).
This is the Pyzo interpreter with integrated event loop for ASYNCIO.
Type 'help' for help, type '?' for a list of *magic* commands.

>>> (executing file "pyzo-test-logger.py")
this is a warning line

>>> 
```
Problems:
- the logfile is not created on disk
- the messages emitted to py shell don't match the loglevel set

The same file with Pyzo 4.7.3 also had problems, but not the same. In the 4.7.3 case all messages were printed to shell console, but it still didn't create the log file.

The same file run from command shell works as expected, a log file is created and it has all messages:
```
> python D:\pyzo-test-logger.py
> type D:\test.log
DEBUG:root:Logfile for 2019-09-10 [D:\test.log]
INFO:root:this is an info line
WARNING:root:this is a warning line
DEBUG:root:this is a debug line
```

**Comment by almarklein** [comment]
```
>>> logging.basicConfig?

    Do basic configuration for the logging system.

    This function does nothing if the root logger already has handlers
    configured. [...]
```

Pyzo adds handlers to the root logger, which is why this fails. Not much we can do there, I think. I suppose the workaround would be to avoid using `logging.basicConfig()` in Pyzo.

**Comment by maphew** [comment]
Would it be possible to print a warning message in Pyzo when logging module used? A coworker and I spent a good part of a day troubleshooting the wrong things, thinking it was our code.

**Comment by almarklein** [comment]
Ai, sorry to hear that :(

What would be a good approach in your opinion? First thing that comes to mind is overloading (monkey-patching) `logging.basicConfig()` ...

**Comment by maphew** [comment]
Sorry, I'm not knowledgeable enough to suggest how. My dev skills are still solidly amateur ;-)

**Comment by almarklein** [comment]
No problem :) I reopened the issue and will have a look at it.
