### ISSUE TITLE
Printing too much causing crash ?

### ISSUE THREAD

**Issue by ysalmon** [pyzo/pyzo#652]
A colleague told his students that Python's RNG would not pick a number more than 10 standard deviations. So, naturally, a student tested this :
```
import random
h = 0
n = 0
while h >=0 :
   h = random.gauss(10,1)
   print('la valeur numéro', n, 'vaut :',h )
   n = n+1
print('Au bout de', n,'opérations, un nombre négatif a été trouvé :', h, 'à moi les croissants :)')
```
The script crashes after roughly 900000 iterations and my colleague wonders if this is because Pyzo's print buffer is not able to cope with the number/speed of prints.
Is that plausible ?

**Comment by almarklein** [comment]
Printing text costs time. It should not crash though. What happens is:

The part that takes time is adding the text to the Qt widget so it can be displayed. There is an internal buffer that the IDE tries to process (i.e. display the text). If the IDE cannot keep up, the buffer fills up, causing the kernel process to slow down. This is to prevent the consumption of huge amounts of memory when a lot of text is printed. Further, the IDE truncates the displayed lines when it becomes very large. 

In what way does the script crash? Is there an error message? I'm running the script now to see what happens. It's at 300k now :)

**Comment by almarklein** [comment]
Will it ever stop by the way? I removed the print-call in the loop to make it run faster. It went to `n=1697504582` without stopping :)
