### ISSUE TITLE
Possible bug in _get_interpreters_win

### ISSUE THREAD

**Issue by edreamleo** [pyzo/pyzo#654]
It's not clear whether the following problem will ever actually affect pyzo itself.

In Leo's pyzo_in_leo plugin, the following line throws a TypeError, because found contains None.

    found = [os.path.normcase(os.path.abspath(v)).strip('\\') for v in found]

Leo's pyzo_in_leo plugin monkey-patches _get_interpreters_win so that the line becomes:
```
found = [os.path.normcase(os.path.abspath(v)).strip('\\') for v in found
            if v is not None]
```
The crash started happening when Leo's monkey-patched close_handler was upgraded so it contains the following:
```
def do_nothing(*args, **kwargs):
    pass

pyzo.main.saveWindowState = do_nothing
pyzo.saveConfig()
    # The next reload crashes in _get_interpreters_win.
pyzo.command_history.save()
```

**Comment by almarklein** [comment]
Thanks for the heads up!

The following [line](https://github.com/pyzo/pyzo/blob/master/pyzo/util/interpreters/__init__.py#L89) is just above the line you mentioned:
```py
    found = [v for v in found if v]
```
Which is where the `None`'s should already be removed. This line was added about 7 months ago, for the exact purpose that you are mentioning. Can it be that your fork does not yet contain this fix?
