### ISSUE TITLE
Defining function to variable Autocomplete not working..

### ISSUE THREAD

**Issue by timeisflowing** [pyzo/pyzo#655]
Hello, 

Running autocomplete with The called class function no problem

Sample: 

from PyQt5.QtNetwork import *

QNet and press tab working complete QNetworkInterface

But when I define the variable to the function

manager = QNetworkAccessManager() working
manager. press tab not access library function not working auto complete

what can I do ?

**Comment by almarklein** [comment]
Pyzo will not automatically execute code, except for automatic imports. If you have executed the line `manager = QNetworkAccessManager()`, then Pyzo should be able to autocomplete `manager`. But if that line has not been executed, then the variable `manager` does not exist, so Pyzo cannot know what's inside.

**Comment by timeisflowing** [comment]
That is, immediately after the object, a space of and . when I say tab, we can easily list executable objects.. and we'll take the parameter I need and remove the object we're looking for first. I think that's the only solution for now, thank you. 

Respects!
![autocomplete-test](https://user-images.githubusercontent.com/5330431/67043363-6f94a600-f119-11e9-830b-50f9b450c7dd.png)
