### ISSUE TITLE
Pyzo doesn't start with PySide on archlinux

### ISSUE THREAD

**Issue by URemery** [pyzo/pyzo#657]
Hi,
Just installed pyzo on my archlinux laptop (from the official repositories) and it shows this error at startup  : 

> [ugor@archlinux ~]$ pyzo
Started our command server
Loaded theme 'Default'
Loaded theme 'Solarized_Light'
Loaded theme 'Dark'
Loaded theme 'Scintilla'
Loaded theme 'Solarized_Dark'
Uncaught Python exception: 'NoneType' object is not iterable
  File "/usr/bin/pyzo", line 3, in <module>
    pyzo.start()
  File "/usr/lib/python3.8/site-packages/pyzo/__init__.py", line 276, in start
    from pyzo.core.main import MainWindow
  File "/usr/lib/python3.8/site-packages/pyzo/core/main.py", line 20, in <module>
    from pyzo.core.icons import IconArtist
  File "/usr/lib/python3.8/site-packages/pyzo/core/icons.py", line 131, in <module>
    class TabCloseButton(QtWidgets.QToolButton):

I had to install PyQt5, which is flagged as optional dependency of pyzo on archlinux repos (see https://www.archlinux.org/packages/community/any/pyzo/ ), for pyzo to start effectively.

It's fine for me but you might want to fix this bug. Keep up the good work !

Ugo

**Comment by almarklein** [comment]
No idea who is maintaining those though, not sure how to reach the ppl who can fix it.

**Comment by ArchangeGabriel** [comment]
Well there is my name in the `Maintainer` field. ;) But indeed it does not gives you an email straight away.

Anyway, should I understand that `'PySide' or 'PySide2' or 'PyQt5' or 'PyQt4'` is not true and `PyQt5` is actually required?

**Comment by almarklein** [comment]
In theory it should work with any of the four Qt libs. But maybe something slipped in that broke this assumption. This is currently not tested. It would anyway be safer to use use either PyQt5 or PySide2.

**Comment by almarklein** [comment]
Maybe it's best to simply advocate that either PySide2 or PyQt5 is needed ...

**Comment by almarklein** [comment]
Closing: Pyzo does no longer claims to work with PySide/PyQt4. Though I would not mind a PR to revive support.

**Comment by ArchangeGabriel** [comment]
@almarklein But the ArchLinux package is using PySide2 by default (we don’t even have PySide in the repo).

**Comment by almarklein** [comment]
Are you saying that it does not work with PySide2? If so, what version is that? I've ran Pyzo with PySide2 just fine.

**Comment by ArchangeGabriel** [comment]
At the time the reporter opened this ticket, we were having Pyzo 4.9, Python 3.8 and PySide2 5.13.2. I cannot try Pyzo without PyQt5 for now, but will give it a shot tonight if I remember to.
