### ISSUE TITLE
Win10. Problem with the FileBrowser in Pyzo

### ISSUE THREAD

**Issue by BGonard** [pyzo/pyzo#661]
The FileBrowser in Pyzo cannot open the directories whose name contains a space.
I use Pyzo 4.9, with Windows 10. 
Thank you,
BGonard,

**Comment by BGonard** [comment]
The message is :
Error: [WinError 5] Accès refusé : 'C:\\Users\\Utilisateur\\Menu Démarrer'

**Comment by stonebig** [comment]
It's curious, I don't have that problem:

![image](https://user-images.githubusercontent.com/4312421/70649381-4b52d280-1c4d-11ea-8545-f1b8a6ce7887.png)

**Comment by BGonard** [comment]
Ok, thank you. 
The problem is that my directory is hidden, or is a shortcut. 

Sorry.

 B.
