### ISSUE TITLE
Retina display support on Mac

### ISSUE THREAD

**Issue by josefuher** [pyzo/pyzo#663]
Version 4.9.0 does use full Retina display resolution. Info.plist has to be extended manually by:

<key>NSHighResolutionCapable</key> 
<string>True</string>

**Comment by almarklein** [comment]
Also learned about this as a generic solution:
```py
import ctypes
try: ctypes.windll.shcore.SetProcessDpiAwareness (True)
except: pass
QApplication.setAttribute(Qt.AA_EnableHighDpiScaling, True)
QCoreApplication.setAttribute(Qt.AA_UseHighDpiPixmaps, True)
```

**Comment by almarklein** [comment]
Added that in #674

**Comment by almarklein** [comment]
Added `NSHighResolutionCapable` in #675

**Comment by almarklein** [comment]
It *should* now work, binary available: https://github.com/pyzo/pyzo/releases. Please re-open if necessary :)
