### ISSUE TITLE
Library mismatch between pyzo and system

### ISSUE THREAD

**Issue by ysalmon** [pyzo/pyzo#665]
While doing a lab session with PIL (pillow), displaying an image was not possible due to the following error
```
display-im6.q16: unable to load module `/usr/lib/x86_64-linux-gnu/ImageMagick-6.9.10/modules-Q16/coders/png.la': file not found @ error/module.c/OpenModule/1314.
display-im6.q16: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/560.
display-im6.q16: no decode delegate for this image format `' @ error/constitute.c/ReadImage/560.
```
After investigation, pillow just does ``os.system("display /tmp/sometempfile.png")``. Running display in a terminal worked fine.

Running ``os.system("ldd $(which display)")`` shows that libraries bundled with Pyzo are used first, and system libraries only if pyzo does not bring its own. Turns out they are incompatible.

In fact, commands run from python running in Pyzo with os.system (or subprocess.call) run with an environment that has LD_LIBRARY_PATH set to Pyzo's dir.

**Is this intentional on Pyzo's part ?**

In the shell config in Pyzo, I added ``LD_LIBRARY_PATH=/`` and this solves my compatibility problem.

**Is there a potential drawback to this ?**
If not, maybe it should be part of the default environment ?

**Comment by almarklein** [comment]
> [...] LD_LIBRARY_PATH set to Pyzo's dir. Is this intentional on Pyzo's part ?

I'm pretty sure that PyInstaller sets this to ensure that Pyzo works when frozen. The problem is that the env variable leaks through to the kernels. It's not the first time PyInstaller mechanics cause problems with the kernels :)

Ideally, we'd detect `LD_LIBRARY_PATH` before it's set, and re-apply it to the env when we spawn the kernel subprocess. But I'm not sure if we can...

Setting the `LD_LIBRARY_PATH` in the shell config seems like the best workaround for now.

> Is there a potential drawback to this?

Yeah, I suppose if a user relies on `LD_LIBRARY_PATH` in some way, she would have to apply the same value in the shell config ...

**Comment by Tontyna** [comment]
Same issue here, albeit with Cairo, Pango and Fontconfig -- pyzo from binary `pyzo-4.9.0-linux64.tar.gz`.

Got (Fontconfig) info about being `Unable to update the static FcBlanks`.
BTW: `FcBlanks` is deprecated in current Fontconfig 

Setting `LD_LIBRARY_PATH=` in the shell config helped. Shell switched to system libraries. But still, Fontconfig wasn't happy:

```
Fontconfig warning: "/home/xxx/pyzo-4.9.0/source/pyzo/resources/fonts/linux_fonts.conf", line 195: blank doesn't take any effect anymore. please remove it from your fonts.conf
```

Yes, yes, `FcBlanks` is deprecated...

Setting `FONTCONFIG_FILE=` in the shell made things worse -- Fontconfig wasn't able to find any fonts anymore:

```
Fontconfig warning: no <cachedir> elements found. Check configuration.
Fontconfig warning: adding <cachedir>/var/cache/fontconfig</cachedir>
/home/xxx/weasyprint/fonts.py:230: UserWarning: FontConfig: No fonts configured. Expect ugly output.
  'FontConfig: No fonts configured. '
Fontconfig warning: adding <cachedir prefix="xdg">fontconfig</cachedir>
```

And in fact: all letters rendered as rectangles.

Eventually I edited the `linux_fonts.conf` -- copied my `/etc/fonts/fonts.conf`. Everything seems to work now.

To be honest: I stopped using frozen pyzo, created a virtual environment, pip installed PyQt5 and run pyzo from source.

**Comment by almarklein** [comment]
@ysalmon What version of Pyzo is that?

This [issue in PyInstaller](https://github.com/pyinstaller/pyinstaller/pull/2148) seems to have fixed this in PyInstaller in 2016. I did some digging:

- 4.6.1 was the last version build on 14.04 with py2exe
- 4.7.0 to 4.9.0 were build on 16.04 with PyInstaller 3.4 (sept 2018)
- from 4.10.0 we're building binaries on Azure pipelines.

I just tried this in both Pyzo 1.9.0 and 1.10.0 (both binary):
* In terminal `export LD_LIBRARY_PATH=/home/almar/foo`
* Run pyzo from terminal
* In Pyzo's shell: `os.getenv("LD_LIBRARY_PATH")` --> result has Pyzo's root dir + `/home/almar/foo`.

**Comment by almarklein** [comment]
Ok, So now I think I understand that the problem is that PyInstaller *prepends* the binary Pyzo root dir. We can totally fix that!

**Comment by almarklein** [comment]
Incidentally, this also fixes the issue that on Linux the GUI integration with PyQt can be problematic.

**Comment by Tontyna** [comment]
Wanted to see what happened to `LD_LIBRARY_PATH` in v4.10.0` and later, but was unable to do that because pyzo binary crashes, see #678.

**Comment by Tontyna** [comment]
By carefully avoiding my keyboard (thank you, mouse!) I finally was able to check the `LD_LIBRARY_PATH` -- both, in the tarball and current master `os.environ['LD_LIBRARY_PATH']`, of the shell still points to the pyzo installation root.

To understand what happens I'll have to dive deeper into the pyzo source...

**Comment by almarklein** [comment]
Just released 4.10.1, and tried to verify that this is fixed. It was not. But the reason was quite obvious; I was too quick in writing the first solution. I just pushed a commit to fix it for real (also confirmed it). Will release 4.10.2 in  a bit.

**Comment by Tontyna** [comment]
Libraries in the shell now seem to be the ones from the system, but shell's fontconfig still follows the `FONTCONFIG_FILE` set by Pyzo and complains about `line 195: blank doesn't take any effect anymore. please remove it from your fonts.conf`.

As a workaround my shell now has the following startup code:

```python
import os; os.environ.pop("FONTCONFIG_FILE",""); os.environ.pop("LD_LIBRARY_PATH","")
```

(didn't like `LD_LIBRARY_PATH` being set to an empty string)

**Comment by almarklein** [comment]
Let's discuss in #685
