### ISSUE TITLE
pyzo v4.10.0 binary crashes on Linux

### ISSUE THREAD

**Issue by Tontyna** [pyzo/pyzo#678]
OMG! Extracting `pyzo-4.10.0-linux64.tar.gz` and starting the `pyzo` launcher from terminal pyzo crashes with `Segmentation fault` as soon as I press a key on my keyboard.

The terminal output indicates besides a lot of `Gtk-WARNING: **: Theme parsing error:...` that pyzo's FontConfig has been updated since v4.9.0 -- `Unable to update the static FcBlanks: 0x0600` -- and finally `Segmentation fault`.

System is Ubuntu Bionic
Machine: x86_64
Version: <span>#</span>40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019
Release: 5.0.0-37-generic

Doesn't help to exchange the `source/pyzo` with current master-branch source, including #676.

----

Summary of this issue (by AK):

Observations:
* There are some warning/error messages, but Pyzo startsup just fine. It segfaults the moment a key is pressed.
* The build is performed on Azure Pipelines, on an Ubuntu 16.04 VM.
* Somehow the resulting frozen app contains a different set of libs than Pyzo v4.9.0 which was also build on Ubuntu 16.04 (but via a Virtualbox VM). It mostly contains *more* libs, but some libs are also "missing".
* `libxkbcommon` seems to be causing the segfault.
* The `v4.9.0` build has `libxkbcommon.so.0` and `libxkbcommon-x11.so.0` while in v4.10.0 there is only the former. If I either remove `libxkbcommon`, or add `libxkbcommon-x11`, the segfault is gone.

Questions:
* Why is PyInstaller incapable of selecting the correct set of dependencies in this situation?
* What can we do to fix it?

Things I tried (and did not work unless mentioned otherwise):
* Use older versions of PyInstaller, and also the bleeding edge dev version.
* Different Python versions via the `UsePythonVersion` Azure Pipelines task.
* Using a ppa to install Python 3.6 (Pyzo needs 3.6, while 16.04 has 3.5). 
* Using Docker to build on a ManyLinux VM. Ha! Not suitable for PyInstaller because it (deliberately does not contain libpython).
* PySide2 instead of PyQt5.
* Use 18.04: running the resulting application does not popup Pyzo but simply freezes.
* Using Docker `python:3.7-stretch`: works on 18.04, and no fontconfig warnings :). On 20.04 there are many fontconfig warnings and it works!

**Comment by almarklein** [comment]
😢

**Comment by almarklein** [comment]
Fired up a VM and I can reproduce the problem. I think I did make some changes in CI to use Python 3.7 and PyQt5 instead of 3.6 and PySide2. I'll try with a recent built artifact.

**Comment by almarklein** [comment]
Thanks for the heads-up btw :D

**Comment by almarklein** [comment]
Maybe things will be less prone to issues like this if we freeze on a ManyLinux VM?

**Comment by Tontyna** [comment]
> I think I did make some changes in CI to use Python 3.7 and PyQt5 instead of 3.6

My crashing v4.10.0 binary uses Python 3.6:

```
Version info
Pyzo version: 4.10.0 (binary)
Platform: linux
Python version: 3.6.10
Qt version: 5.14.0
PyQt5 version: 5.14.1
```

while the working v4.9.0 binary uses Python 3.5:
```
Version info
Pyzo version: 4.9.0 (binary)
Platform: linux
Python version: 3.5.2
Qt version: 5.5.1
PyQt5 version: 5.5.1
```

**Comment by Tontyna** [comment]
I suspect there are libraries missing in the binary. Why else should the pyzo command server try (and fail) to load libraries from `/usr/lib/x86_64-linux-gnu/gio/modules/`?

I got similar warnings when I deleted `libcairo.so.2` from the binary root (in the hope that my shells would load the more recent system cairo).

**Comment by almarklein** [comment]
Tried to build on ManyLinux, but running into PyInstaller not finding the Python lib and I'm too tired to chase that down. Also tried building with PySide2 instead of PyQt5 but running into the exact same problem. *Sigh*

**Comment by almarklein** [comment]
> I suspect there are libraries missing in the binary.

I just put the contents of the tar file of v4.9.0 and v4.10.0 side by side, and the latter includes much *more* libs (like 40). I suspect it puts in too many, causing Pyzo to use its own lib instead of the system lib, but then that lib has a dependency that is *not* included, but the system lib then being incompatible. Or something along that line ...

**Comment by Tontyna** [comment]
Same impression here.
