### ISSUE TITLE
Why does Github think this repo is 86% HTML?

### ISSUE THREAD

**Issue by almarklein** [pyzo/pyzo#680]
WTF

**Comment by Tontyna** [comment]
It's a mystery -- https://github.com/pyzo/pyzo/search?l=html retrieves ZERO html files

Maybe following advice #4 on https://github.com/github/linguist#troubleshooting is the way to go.

**Comment by adddvent** [comment]
There is one big (ca. 9 MiB) HTML file in the repo:
https://github.com/pyzo/pyzo/blob/master/pyzo/pyzokernel/start.html

It has "choropleth.py example" as its name in the header, depends on bokeh.js and contains the coordinates of the borders of the states of the USA. That file seems to be out of place.

**Comment by almarklein** [comment]
Oh wow. It looks like this was an artifact during testing the Tornado integration, and I accidentally committed it. Thanks @adddvent ! I removed the file, and now GH reports 99.8% Python :)
