### ISSUE TITLE
Do not start autocompletion from first character

### ISSUE THREAD

**Issue by ysalmon** [pyzo/pyzo#689]
When I am typing a short variable like ``i`` in a loop, Pyzo pops up its autocompletion list with everything that begins with ``i``, which is more annoying than helpful.

I think there was an option to start autocompletion after only 3 or 4 characters at a point. Or I am confusing with another IDE ?

In any case I propose to add it (back ?).

**Comment by almarklein** [comment]
mmm ... it seemed like a good idea, but now that I'm using it, there is a use-case for which it really hurts discoverability. And this is when autocompleting an attribute. Any change we can fix that?

**Comment by ysalmon** [comment]
Le 27/02/2020 à 12:37, Almar Klein a écrit :
> mmm ... it seemed like a good idea, but now that I'm using it, there is
> a use-case for which it really hurts discoverability. And this is when
> autocompleting an attribute.
What do you mean ?

**Comment by almarklein** [comment]
`>> some_object.`  -> I want my autocompletion to popup directly now, to see what's inside.
