### ISSUE TITLE
The process failed to start (invalid command?). (1)

### ISSUE THREAD

**Issue by safaa173** [pyzo/pyzo#701]
when I start pyzo the shell doesn't work (![Annotation 2020-04-14 232625](https://user-images.githubusercontent.com/63678446/79275939-65284e80-7ea7-11ea-9d8d-66a2e999f02d.png)
  ) .
What I understood is that there's an error in the main script.

**Comment by almarklein** [comment]
You can resolve this by installing a newer Python version. This is an error that has been fixed long ago :)
