### ISSUE TITLE
The current TCP port range used by Pyzo gets blocked 

### ISSUE THREAD

**Issue by igordevries** [pyzo/pyzo#702]
Hi
After restarting my computer yesterday, the shell does not start anymore (screen remains blank), and after a while the whole program hangs. I have tried several shells but they all give the same result. I have tested the python installation in a windows cmd shell, and it works normally. 
Regards, Igor

Pyzo:
Pyzo version: 4.10.2 (binary)
Platform: win32
Python version: 3.7.6
Qt version: 5.14.1
PyQt5 version: 5.14.1

Pyzo directories
Pyzo source directory: C:\Users\dvi\Programs\pyzo\source\pyzo
Pyzo config directory: C:\Users\dvi\AppData\Roaming\pyzo
Pyzo userdata directory: C:\Users\dvi\AppData\Roaming\pyzo

Windows:
Microsoft Windows [Version 10.0.17763.1098]

**Comment by almarklein** [comment]
Thanks for filing this. I don't think I have ever seen or heard the shell being completely blank ...
Could you please open the logger (from the tools menu) and see if it shows any error messages?

Could there perhaps be a firewall or anti-virus software preventing the Python process (for the kernel) to start up?

**Comment by igordevries** [comment]
Hi, thanks for your quick response. In the logger I see the error below repeated a large number of times:

```
Exception while handling event:
Could not bind to any of the 256 ports tried.
line 178 of C:\Users\dvi\Programs\pyzo\source\pyzo\yoton\connection_tcp.py.
```

Regards, Igor

**Comment by almarklein** [comment]
Aha, this looks like an issue [that we had last year](https://github.com/pyzo/pyzo/issues/634). Except now it's worse.

Some background: Pyzo tries to open a tcp connection in the ephemeral port range, starting at an arbitrary port number. If that does not work, it picks the next number, etc. until it tried 256 ports, after which it gives up. The first arbitrary port number is obtained by hashing the string "pyzo", which is 53281.

https://github.com/pyzo/pyzo/blob/master/pyzo/core/kernelbroker.py#L391-L393
https://github.com/pyzo/pyzo/blob/master/pyzo/yoton/connection_tcp.py#L163-L178

I suspect that the firewall is blocking whole ranges of ports. I wonder if there are other ranges which are safe to use ...

**Comment by igordevries** [comment]
yes, IT department is constantly tinkering with the firewall settings (very annoying), would you have any suggestions as how to further diagnose this?

**Comment by almarklein** [comment]
So Pyzo uses the range of "Dynamic, private or ephemeral ports: 49152–65535. The question, I think is whether your IT department prohibits this whole range, or a subset. If a subset, we can pick a different starting port. Otherwise .... we'd have to find ourselves a spot in the registered port range (1024 to 49151), I think?

Also, if we do find a way out for you, I'd love to know more about the why, and whether its likely to apply for other users as well. If so, we may fix it by applying a simple change in Pyzo. Otherwise, we may need to introduce a setting to let users specify the port range (I hope this won't be necessary).

**Comment by igordevries** [comment]
ok, is there a way I can manually try this out?

**Comment by almarklein** [comment]
Yes, you could edit the Pyzo source `/path/to/pyzo-bin/source/pyzo/core/kernelbroker.py`. On line 392 you can change "localhost:pyzo" with "localhost:49151" (or any other port number).

**Comment by igordevries** [comment]
yes, that did the trick! thanks very much!

**Comment by almarklein** [comment]
Great! I would love to learn what port worked for you. And whether we can do something to help prevent this issue for other users, or to provided a workaround for users that face this problem.

**Comment by igordevries** [comment]
The first port you suggested (49151) worked. I verified that this was indeed the problem by running alternately with the original and then with the changed port. Let me know if I can be of further help...
Regards, Igor

**Comment by almarklein** [comment]
Ah, that port I suggested was actually a typo, I copied the wong number. That port should actually be the last port *not* in the ephemeral range :)  Could you try 49152 and 50000 for me?

**Comment by igordevries** [comment]
49151, 49152, and 50000 all work.

**Comment by almarklein** [comment]
Thanks. I'll try to see if I can find out why `53281` to `53281 + 256` don't work. If you don't mind, I might ask you to try some ports later :)

**Comment by igordevries** [comment]
yes, let me know.

**Comment by almarklein** [comment]
I changed the port number to `port_hash("PYZO")`: 50369. I hope this fixes it, and does not cause blocks on other systems ...
