### ISSUE TITLE
Font enumeration takes too much time

### ISSUE THREAD

**Issue by ysalmon** [pyzo/pyzo#703]
When hovering over the font selection submenu (in View menu), Pyzo enumerates all monospaced fonts.

If a large number of fonts is installed on the system, this takes several minutes.

It is blocking, meaning that if one just happened to pause the mouse cursor there without any real intent to change the font, one has to wait for nothing.

Moreover, the result of the enumeration is not cached, so that if one wants to change the font but mistakenly moves away from the submenu (or just want to try different fonts in succession), one must wait again and again.

**Comment by almarklein** [comment]
I understand the problem, but I've had to wait for more than a second or so, so never thought this would be much of a problem. But waiting minutes is. 

Is this on a system with a particularly large number of fonts, or is it a slow system in general?

A cache, and maybe doing the enumeration in a separate thread could help ...

**Comment by ysalmon** [comment]
Yes, there are lots of fonts but the system is not slow (data is on a SSD, inter alia).

**Comment by almarklein** [comment]
Ok, let's get it fixed then :)

**Comment by ysalmon** [comment]
Here is how it's done in TexStudio, a C++ Qt app ; it seems to be much faster : https://github.com/texstudio-org/texstudio/blob/936655fde97de85b66c2f3033dfdf3fe86854e67/src/configdialog.cpp#L1108.

**Comment by l33tlinuxh4x0r** [comment]
I just wanted to confirm this bug... It takes about a minute for me too. I also have a fast system with lots of fonts installed.

**Comment by almarklein** [comment]
@ysalmon thanks for that link. I think it provided the answer. We were instantiating each font into a Font object in order to see whether it's monospaced. I supposed this takes time. 

Here's a snippet that you could try to run. The first number should be that minute-long wait, the second should be faster.

```
import time
from PyQt5 import QtGui

db = QtGui.QFontDatabase()
QFont, QFontInfo = QtGui.QFont, QtGui.QFontInfo

t1 = time.perf_counter()
names1 = [fn for fn in db.families() if QtGui.QFontInfo(QtGui.QFont(fn)).fixedPitch()]  # old version
t2 = time.perf_counter()
names2 = [fn for fn in db.families() if db.isFixedPitch(fn)]  # new version
t3 = time.perf_counter()

print(t2 - t1, t3 - t2)
```

**Comment by almarklein** [comment]
This change has been applied to the current master. I hope this makes it fast enough. If it's still multiple seconds, then we should also introduce a cache ...
