### ISSUE TITLE
Editor tabs do not theme.

### ISSUE THREAD

**Issue by l33tlinuxh4x0r** [pyzo/pyzo#706]
See included screenshot. The tabs of the editor never change no matter what theme is applied.
![Screenshot from 2020-07-05 18-00-08](https://user-images.githubusercontent.com/1632838/86543090-6aff6000-bee9-11ea-9a0e-8552e8ac92f7.png)

**Comment by almarklein** [comment]
The tabs are custom-styled, so this is expected :)
