### ISSUE TITLE
Usual shortcut for { make ( with Pyzo 4.10.2)

### ISSUE THREAD

**Issue by jowe19** [pyzo/pyzo#711]
The usual shortcut for "{" in macOS (Option +/ () make "(" with Pyzo 4.10.2, instead of {. 

How can I fix it ?

**Comment by almarklein** [comment]
Does the behavior change when turning off `Settings > autocompletion >Auto close brackets` (last option)?

**Comment by jowe19** [comment]
Yes, it does.
The bracket appears whenever the "Auto close brackets" option is disabled.

**Comment by almarklein** [comment]
> The bracket appears

The correct one, you mean? :)

**Comment by jowe19** [comment]
Yes, the correct one.

**Comment by almarklein** [comment]
Ok, so this looks like a duplicate of #662 ... I'd need to see if this can be fixed. In the mean while, you'd have to do without auto bracket closing...

**Comment by almarklein** [comment]
Fixed in #726. Will a release soon (maybe today).
