### ISSUE TITLE
Pyzo replacing "," with "." when typing in bépo layout

### ISSUE THREAD

**Issue by Manu0225** [pyzo/pyzo#720]
Hi, 
as a Frenchman I type in bépo, which is an alternative keyboard layout to azerty. It seldom causes problems in apps, but in Pyzo, when I am typing code, whether in the shell or in an open python file, all my "," are replaced by "."  
(this has never happened to me outside of Pyzo)
This is not the case when I am using the "Search and replace" fields.

I have no idea why this occurs, and when i switch to azerty the issue doesn’t happen anymore.

This is a bit annoying as I have to paste the "," character from another window to be able to access it

**Comment by almarklein** [comment]
Hi, thanks for reporting this!

> This is a bit annoying as I have to paste the "," character from another window to be able to access it

Arg, sorry for that! 

Could you try this: In the menu > settings > autocompletion, turn off the auto-close quotes and auto-close braces? Maybe its far-fetched, but a somewhat similar issue could be resolved when turning this feature off.

**Comment by almarklein** [comment]
I don't think you sounded rude :)

I'll have a look when I dive into that other issue. In the mean time, if you have more info, please let me know here!

**Comment by almarklein** [comment]
I looked at images of the Bépo layout, and the "," and "." are not on the same key, are they? Could you tell me more about how you'd type these characters, to get a bit better understanding how that works, and where that could go wrong in Pyzo.

**Comment by Manu0225** [comment]
they are not on the same key, indeed!

If you look at this image :
https://download.tuxfamily.org/dvorak/wiki/images/Bepo-1.1-base.png
then "," is the key between "e" and "c". It’s in direct access so I just type it directly, with no modifier (no maj, no alt, nothing)
same goes for "." which is between "x" and "k": direct access so again, no modifier, I just type it directly.

 The funny/strange thing is that when I type "," in the "Find and replace" fields of Pyzo, it’s entered correctly!

**Comment by almarklein** [comment]
This is suspicious: https://github.com/pyzo/pyzo/blob/master/pyzo/codeeditor/extensions/behaviour.py#L158-L183

**Comment by almarklein** [comment]
@Manu0225 do you have a chance to try disabling this code to see if it solves the issue? You can edit the source of your local copy of Pyzo (see `menu > help > about` for the Pyzo source directory).

**Comment by almarklein** [comment]
I have disabled that code in #726, since it was the only code that I could find that could cause this error. Will do a release probably today. Please let me know if the error persists!

**Comment by Manu0225** [comment]
> @Manu0225 do you have a chance to try disabling this code to see if it solves the issue? You can edit the source of your local copy of Pyzo (see `menu > help > about` for the Pyzo source directory).

It worked!!!
Thank you so much!!
