### ISSUE TITLE
Pyzo is broken on MacOS BigSur

### ISSUE THREAD

**Issue by jowe19** [pyzo/pyzo#731]
I just installed the latest OS of Apple (MacOS 11)  and Pyzo no longer opens. Do you know how to fix this?

**Comment by ak-cuervo** [comment]
I'm having the same issue. The task bar shows that pyzo is launched (a dot under the pyzo icon) but the interface never launches. I checked security and everything appears correctly configured.

**Comment by ak-cuervo** [comment]
Downloaded latest version and reinstalled. Did not solve the problem.

**Comment by almarklein** [comment]
Thanks for reporting this issue! I don't have a Mac to reproduce this, so I may ask for help to test something here ;)

I did a bit of research, and I suspect that this is an upstream issue with PyInstaller (https://github.com/pyinstaller/pyinstaller/issues/5107), due to a change in MacOS 11. Though I also see some changes to CPython for supporting that MacOS version.

One thing we could try is to do a binary build on the latest CPython 3.8 or 3.9. I'll probably have time for this Monday. In the mean time, if anyone has more info on this, please comment here ...

**Comment by JeanCasteres** [comment]
Hello,
I am having the same issue. I use:
- Anaconda3-2020.07-MacOSX-x86_64
- pyzo-4.11.0-macos
for a scholar project. Not able to rebuild from scratch.
Thank you for your help.

**Comment by almarklein** [comment]
I changed CI to build on Python 3.9. Here is the build for MacOS: https://www.dropbox.com/s/yd6scya89spz5ie/pyzo-4.11.1-macos.dmg?dl=1

If some of you could test-drive it, that would be great!

**Comment by jowe19** [comment]
Thank's for this release, but I have the same issue as described on Friday. 
Python version : 3.8 (Miniconda)

**Comment by almarklein** [comment]
Spyder is suffering from the same issue (https://github.com/spyder-ide/spyder/issues/14222).

Another (intermediate) solution could be to run Pyzo from source. Just `pip install pyzo` and run `python -m pyzo`. I'm not sure what the default Python version is, so you may need to install python 3.9 with homebrew as is proposed is this [comment](https://github.com/spyder-ide/spyder/issues/14222#issuecomment-727602712).

**Comment by JeanCasteres** [comment]
Hello,
Tried it and still have the same issue. please find the log attached if it does help.
Sincerely, JC
[pyzo-crashdump-20201116.zip](https://github.com/pyzo/pyzo/files/5546004/pyzo-crashdump-20201116.zip)

**Comment by SzamCha** [comment]
Here is result from terminal :

(base) samuelchalifour@iMac-de-Samuel ~ % pip install pyzo
Collecting pyzo
  Downloading pyzo-4.11.0.tar.gz (2.1 MB)
     |████████████████████████████████| 2.1 MB 5.3 MB/s 
Building wheels for collected packages: pyzo
  Building wheel for pyzo (setup.py) ... done
  Created wheel for pyzo: filename=pyzo-4.11.0-py3-none-any.whl size=2200942 sha256=caecedba2126818320dbdd15d9d39bc24519520bc4cb8de37599fd35c5eb5036
  Stored in directory: /Users/samuelchalifour/Library/Caches/pip/wheels/22/9f/a7/90ffc9065028cbf9b9d72a896d08f35e8fef7f0980f6a57cb8
Successfully built pyzo
Installing collected packages: pyzo
Successfully installed pyzo-4.11.0
(base) samuelchalifour@iMac-de-Samuel ~ % python -m pyzo
Traceback (most recent call last):
  File "/Users/samuelchalifour/opt/miniconda3/lib/python3.8/site-packages/pyzo/util/qt/__init__.py", line 168, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/samuelchalifour/opt/miniconda3/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/samuelchalifour/opt/miniconda3/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/samuelchalifour/opt/miniconda3/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/samuelchalifour/opt/miniconda3/lib/python3.8/site-packages/pyzo/__init__.py", line 74, in <module>
    from pyzo.util import paths
  File "/Users/samuelchalifour/opt/miniconda3/lib/python3.8/site-packages/pyzo/util/paths.py", line 23, in <module>
    from pyzo.util.qt import QtCore
  File "/Users/samuelchalifour/opt/miniconda3/lib/python3.8/site-packages/pyzo/util/qt/__init__.py", line 175, in <module>
    raise PythonQtError("No Qt bindings could be found")
pyzo.util.qt.PythonQtError: No Qt bindings could be found
(base) samuelchalifour@iMac-de-Samuel ~ %

**Comment by jowe19** [comment]
@SzamCha I get the same issue. Finally I have installed Python 3.9 with the installer of https://www.python.org (with homebrew, this is currently not possible to install matplotlib or panda https://github.com/numpy/numpy/issues/17784).

After that, I tried 
`pip3 install pyqt5`

and `python3 -m pyzo` gives now :
<img width="670" alt="Capture d’écran 2020-11-16 à 14 26 05" src="https://user-images.githubusercontent.com/19306526/99257746-cafeff00-2817-11eb-937d-2b0428764629.png">

**Comment by almarklein** [comment]
@SzamCha, sorry you'd also need to install `pyqt5`, it's not in the dependencies, because either PyQt5 or PySide2 is possible ...

@jowe19 so ... does it work? Is the IDE visible, or does it just hang there?

**Comment by jowe19** [comment]
> @jowe19 so ... does it work? Is the IDE visible, or does it just hang there?

But Pyzo is not visible (just opened in the dock).

**Comment by SzamCha** [comment]
"loading qt French : Failed" and still no visible IDE. 
I'll try Python 3.9 first.

**Comment by almarklein** [comment]
From the discussion on the Spyder issue, two solutions seem to emerge:
* Using `pip install pyqt5==5.13`  to install a version of PyQt5 that appears to work.
* Setting the `QT_MAC_WANTS_LAYER` env variable to "1".

I just ran a new build with the latter (potential) fix: https://www.dropbox.com/s/zmnvb7nzvedh5cz/pyzo-4.11.1.2-macos.dmg?dl=1

**Comment by jowe19** [comment]
> From the discussion on the Spyder issue, two solutions seem to emerge:
> 
> * Using `pip install pyqt5==5.13`  to install a version of PyQt5 that appears to work.
> * Setting the `QT_MAC_WANTS_LAYER` env variable to "1".
> 
> I just ran a new build with the latter (potential) fix: https://www.dropbox.com/s/zmnvb7nzvedh5cz/pyzo-4.11.1.2-macos.dmg?dl=1

Great ! It's working perfectly.

**Comment by mickelsp** [comment]
I experienced the same issue (Pyzo app looking like it was open in the dock, but not showing up) on Big Sur on an M1 Mac mini. The new build appears to have resolved the issue for me as well. Thanks!

**Comment by almarklein** [comment]
This is great news. I will merge the PR and publish the new binaries in the official way!

**Comment by JeanCasteres** [comment]
Hello,
I downloaded I just ran a new build with the latter (potential) fix: https://www.dropbox.com/s/zmnvb7nzvedh5cz/pyzo-4.11.1.2-macos.dmg?dl=1
The 4.11.1.2 build works fine for me, thank you very much.

**Comment by operade** [comment]
Works fine for me too : thank you so much !!

**Comment by SzamCha** [comment]
Thx !!!

**Comment by almarklein** [comment]
A new version has been released. Thanks for testing everyone!

**Comment by TilinMad** [comment]
hello, i just got a mac and, until reading this topic, couldn't run pyzo. Thanks to you, I manage to run pyzo but I cannot open a python file or save my program. Do you have an idea for a solution? thanks for this helpful topic ! (I'm French so my English can be bad 😓)

**Comment by almarklein** [comment]
> [...] I cannot open a python file or save my program.

Can you be more specific what happens instead? Are there error messages? You could open the logger (menu > tools > logger) to see if any errors or warnings are logged.
