### ISSUE TITLE
Compatibility with Apple M1’s chip

### ISSUE THREAD

**Issue by AlistairL1** [pyzo/pyzo#733]
Good morning,

As you may have seen, Apple has unveiled their own computer chip, the M1 built on ARM.

I’m writing this message to know wether you will update your app for these Macs or not and if you do so, how long will it take.

**Comment by almarklein** [comment]
Good point. We're now building on Azure pipelines. As soon as they have machines for ARM MacOS we can use these to build binaries for that platform. However, I would not be surprised if PyInstaller and PyQt may also take a while to update. We'll see ...

**Comment by almarklein** [comment]
Apparently, we don't even have to do anything. It just works! https://github.com/pyzo/pyzo/issues/736#issuecomment-739426094

**Comment by jajadu** [comment]
> Apparently, we don't even have to do anything. It just works! [#736 (comment)](https://github.com/pyzo/pyzo/issues/736#issuecomment-739426094)

Hey @almarklein, Thanks for your help. 
Although it works now, I think you should consider updating it to make it as a native ARM app in the future. 
Apple will surely drop Rosetta2 (which makes x86 app works on ARM Macs) in around 2 years so or less as they did before with the transition to Intel Macs ; so consider it if it's possible please :) (it'll also make it less ressource demanding ^^)

Thanks a lot !

**Comment by almarklein** [comment]
@xTidus-006 I agree. Most of the work should be setting up a new CI build.

**Comment by bdieterm** [comment]
A native Pyzo app for Apple Silicon was added via #1049 by @almarklein for Pyzo version >= 4.16.0.
