### ISSUE TITLE
The process failed to start (invalid command?). (1) with Anaconda

### ISSUE THREAD

**Issue by norrrbit** [pyzo/pyzo#735]
Starting python 3.9 from Anaconda environment in Pyzo on linux Mint gives:

 ```
Traceback (most recent call last):
  File "/usr/share/pyzo/pyzo/pyzokernel/start.py", line 46, in <module>
    import yoton
  File "/usr/share/pyzo/pyzo/yoton/__init__.py", line 39, in <module>
    from yoton.clientserver import RequestServer, do_request
  File "/usr/share/pyzo/pyzo/yoton/clientserver.py", line 81
    def __init__(self, address, async=False, verbose=0):
                                    ^
SyntaxError: invalid syntax

The process failed to start (invalid command?). (1)

```
Pyzo does find proper python executable when configuring shell (.../Anaconda3/envs/efirma/bin/python)
Running system python3 in Pyzo goes OK.
Running python 3.9 from Anaconda environment in terminal goes well too.

Please help.

**Comment by almarklein** [comment]
I think you're using a somewhat older version of Pyzo; we've fixed this bug quite some time ago :)  Please try updating to the latest version.

**Comment by norrrbit** [comment]
You were right - ugrading from Pyzo 4.4.3 to 4.11.2 did help.
You've done a great job with Pyzo!!
Thanks a lot!


pon., 23 lis 2020 o 10:59 Almar Klein <notifications@github.com> napisał(a):
