### ISSUE TITLE
Python on M1 Macs

### ISSUE THREAD

**Issue by jajadu** [pyzo/pyzo#736]
Hi everyone ! First of all, thanks for the potential help you could provide.

I just bought a new Mac on based on ARM and I tried to install Python and use Pyzo to code. I was before coding at school on Linux and Windows and at home, with Windows only. 

However, I'm quite novice and faced an issue with Python :
when i try to run a code using plt.show() such as this easy one 

"import matplotlib.pyplot as plt

x = [1,2,3,4,5,6,7,8]
y = [4,1,3,6,1,3,5,2]

plt.scatter(x,y)

plt.title('Nuage de points avec Matplotlib')
plt.xlabel('x')
plt.ylabel('y')

plt.savefig('ScatterPlot_01.png')
plt.show()"

another window show the graph but i see in the shell that the run isn't finished. In addition to that, when i try to close the window, the multicolor logo of Macs shows up and in the monitor activity, it says that Python is not responding.
So that's quite annoying. Do you think i did something wrong ?
I installed the latest version of Python for MacOs, 3.9.0.

Thank you very much.

**Comment by almarklein** [comment]
Hi!

Out of curiosity, you installed Pyzo via pip then, right?

Anyway, it would be good to put `plt.ion()` after importing `plt`, to turn on interactive mode. Further, make sure you have PyQt5 installed (`pip install pyqt5`). If that still does not work, go to the shell configuration dialog (via the menu) and select pyqt5 for the GUI integration.

**Comment by jajadu** [comment]
Hey @almarklein ! Thanks for your fast reply! :) 

Hmm I don't think so. I downloaded it on the Pyzo's website. Does it change something ?

It seems to work with your solution now !! Thank you so much ! I spend more than hours to find a solution and you helped me so fastly 😊
However, can I ask you something else ? 
What does pyqt5 ? I'm still a newbie on Python. It just prevents the program from a loop ? 
And could it have any impact on other programs ?

Thank you once again!

**Comment by almarklein** [comment]
> I downloaded it on the Pyzo's website. Does it change something ?

Wait, what? Is a MacOS app compiled for x86 supposed to run on ARM?

Qt is a GUI toolkit. PyQt5 is a Python wrapper for it. E.g. Pyzo is build on top of PyQt as well. Anyway, when Matplotlib shows a figure, it needs a GUI toolkit to provide a window to draw to. Additionally, we want that window to be active (so you can e.g. zoom in your plot) and also keep the Pyzo shell active. For that to work, Pyzo needs to integrate with the PyQt5 event loop.

Quite a lot of specific terms in there, I hope you follow :)

**Comment by jajadu** [comment]
Yes, most x86 apps work on ARM Macs because Apple added "Rosetta 2" with macOS Big Sur which "transcodes" x86 apps for ARM. Only a few don't work because of the plugins or something like that, I heard.
However, it's surely better to have native ARM apps but those new chips M1 are incredible 😊

Hmm I didn't understand everything but thank you anyway ! I hope I understand all quite soon :)

Thanks a lot ! I'll close this issue :)

**Comment by almarklein** [comment]
You're welcome! Have fun learning Python!
