### ISSUE TITLE
PySide6 support

### ISSUE THREAD

**Issue by stonebig** [pyzo/pyzo#742]
hello,

Would it be possible to get an easy PySide6 support ?
There is a compatibility fix merged for pyqtgraph https://github.com/pyqtgraph/pyqtgraph/pull/1495
There is an effort of compatibility fix for QtPy https://github.com/spyder-ide/qtpy/pull/225

**Comment by stonebig** [comment]
I'm stucked  trying to replace Qdirmodel replacement per  QFileSystemModel for PySide6 to go one step further.
https://github.com/pyzo/pyzo/blob/master/pyzo/tools/pyzoFileBrowser/browser.py#line300

I noticed you did it one time on https://github.com/pyzo/pyzo/commit/8190af6cbababdfb6fa57b15d9a79e3414c7382a

would it be possible to do it there too ?

**Comment by almarklein** [comment]
Oef, it's been a few years since I looked at that code. Since QDirModel  is obsolete, I think that would be the replacement indeed. Did you manage to fix the flush/pendingevents that you mentioned in the Spyder PR?

**Comment by stonebig** [comment]
well, I did "someting", not sure it was the thing to do

**Comment by stonebig** [comment]
with Pyside-6.6.2.1:
- existing vendored Qtpy: no Qt implementation found
- with QtPy-master of 2021-12-11
![image](https://user-images.githubusercontent.com/4312421/145686309-aff39795-8736-4bd8-8ef1-0de87efd6ff3.png)
- with the proposed patch and vendoring QtPy-master of 2021-12-11
![image](https://user-images.githubusercontent.com/4312421/145686411-f5ce2381-b987-496e-a6d8-f75a21c3150f.png)

**Comment by almarklein** [comment]
Fixed in master. I am now working on revamping the freeze process and CD.
