### ISSUE TITLE
No module named 'sqlite3'

### ISSUE THREAD

**Issue by kelsa-pi** [pyzo/pyzo#743]
Hi,

If I install Python 3.9.2 (latest exe for win 64 bit), and then pip install pyzo - no error.
The problem arises if:
1. install [pyzo-4.11.2-win64.zip](https://github.com/pyzo/pyzo/releases/download/v4.11.2/pyzo-4.11.2-win64.zip).
2. Type "import sqlite3" in the logger or default shell:
    ModuleNotFoundError: No module named 'sqlite3'

Best

**Comment by almarklein** [comment]
What happens if you open run Python 3.9.2 in the terminal and `>> import sqlite3`?

Just to be sure, is the shell using the Python 3.9.2 interpreter?

**Comment by kelsa-pi** [comment]
Hi,

thanks for your interest!

> What happens if you open run Python 3.9.2 in the terminal and >> import sqlite3?

C:\Users\$USER>python
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>>

> Just to be sure, is the shell using the Python 3.9.2 interpreter?

Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) on Windows (64 bits).
This is the Pyzo interpreter with integrated event loop for PYQT5.
Type 'help' for help, type '?' for a list of *magic* commands.
>>> import sqlite3
>>> 

Best

**Comment by almarklein** [comment]
Now I'm confused, you second sample seems to suggest that `import sqlite3` runs without errors.

**Comment by kelsa-pi** [comment]
Sorry for poor wording.
My goal is to activate my plugin in Tool menu. My plugin need sqlite to operate.

I downloaded package package `pyzo-4.11.2-win64.zip` and started pyzo.
When I activate my plugin via Tool menu, Pyzo produce `No module named 'sqlite3' error`. Maybe is python dll defective or similar?

If I install Python 3.9.2 (latest exe for win 64 bit from Python download page), then `pip install pyzo`, then run pyzo `python -m pyzo`, and then run `import import sqlite3 `- no error, plugin is active.
Best

**Comment by almarklein** [comment]
Ah, now I understand. So when the binaries for Pyzo are build, it will only include modules that are used. sqlite is not used in Pyzo itself, so it's not bundled in the binary distribution.

This means that if you create a plugin that uses a dependency which is not a dependency of Pyzo already, you can only use that plugin when running Pyzo from source.
