### ISSUE TITLE
Most recent version of Pyzo which supports Windows 7

### ISSUE THREAD

**Issue by andrewdaviddeyoung** [pyzo/pyzo#747]
Hi,

I installed [Anaconda3](https://www.anaconda.com/products/individual) 64-bit on my Windows 7 (64-bit) computer. Anaconda3 in turn installed Python 3.8.8 (along with many other packages). I am able to successfully run Python 3.8.8 using `python` on the command line and by using IDLE, which Anaconda3 had also installed.

However, I am now trying to install Pyzo on my Windows 7 computer.  I installed Pyzo 4.11.2 (the latest version of Pyzo), but when I try to run it, I get the following error message:

> The program can't start because `api-ms-win-core-path-l1-1-0.dll` is missing from your computer. Try reinstalling the program to fix this problem.

The issue seems to be that Pyzo 4.11.2 probably doesn't support Windows 7 ( [https://bugs.python.org/issue40740](https://bugs.python.org/issue40740) ).

Does anyone know what is the most recent version of Pyzo that still supported Windows 7?

Thanks, 
Andrew

**Comment by almarklein** [comment]
My guess would be 4.9.0, because 4.10.2 is the first one in which the builds are automated.

An alternative could be to run Pyzo from source. Install PyQt5 via conda and Pyzo via pip, and just run `python -m pyzo`.

**Comment by andrewdaviddeyoung** [comment]
Pyzo 4.9.0 works for me on Windows 7. Thanks for your help.
