### ISSUE TITLE
pyzo in usb 

### ISSUE THREAD

**Issue by Aurore35** [pyzo/pyzo#751]
Hello,
I want to use pyzo and miniconda on a usb key.
It works at home, but not at work, i couldn't configure pyzo's shell to not look for files in "c: \ program files \" or "/ usr /". 
And so I have a problem with the Windows plugins.
Can you help me ?

**Comment by almarklein** [comment]
If your're using the binary Pyzo, have you looked at the settings directory in the root?

**Comment by Aurore35** [comment]
all the computers I use are under windows 10.
I installed miniconda 4.9.2 and pyzo 4.11.2.
I have an error message: "qt.qpa.plugin: Could not find the Qt platform plugin" windows "in" "
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem. "
I probably made a mistake on the shell configuration, but I don't know which one.

**Comment by almarklein** [comment]
Do you see that error when you try to start Pyzo, or when you try to do something in the shell?

**Comment by Aurore35** [comment]
I see this error when i start Pyzo.

**Comment by almarklein** [comment]
But wait ... does Pyzo itself start and is this error shown in the shell, or do you try to start Pyzo from the commandline and see this error?

**Comment by Aurore35** [comment]
Pyzo is installed at my work, but I need a version that only works on my USB stick.
When I launch pyzo from my key, the interpreter opens with the computer's pyzo shell.
So I make a new shell with the python path present in the miniconda of my key.
This is where I think I'm making a mistake, I don't really understand the role of GUI, pythonpath and startup script.
I put a copy of my [screen.]
![problemePyzo](https://user-images.githubusercontent.com/85994497/122376835-cd1f6c80-cf64-11eb-8bdf-9561321873f6.PNG)

**Comment by adddvent** [comment]
Hi Aurore! Some years ago I created a usb key to run Python and Pyzo on any Windows machine and had to solve a problem that raised the error message "could not find or load the qt platform plugin":

Software I used at that time:
- Anaconda3-5.0.1-Windows-x86.exe (Python 3.6.3 x86)
- Pyzo 4.4.2

To solve the problem I had to copy the
"\\Anaconda3\\Library\\plugins\\platforms"
folder to
"\\Anaconda3"
(both located on the usb key).

see https://github.com/ContinuumIO/anaconda-issues/issues/1270

I guess, for Miniconda it will be the same as for Anaconda.


By the way, this is the file/folder structure I used on the usb key:
- .\\Anaconda3\\ [containing python.exe]
- .\\pyzo-4.4.2\\ [containing pyzo.exe]
- .\\workspace [just an empty folder]
- .\\_pyzo.bat


And this was the Pyzo Shell configuration:
- name: Python
- exe: ..\\Anaconda3\\python.exe
- gui: PyQt5
- pythonPath: ..\\Anaconda3
- startupScript:
- startDir: ..\\..\\..\\workspace

[Yes, you can use relative Paths in the shell configuration, and there is no need for a startup script.]

Settings were stored inside the Pyzo software directory, e.g.:
.\\pyzo-4.4.2\\settings\\pyzo\\command_history.py [you can write-protect this file if you don't want to save the history]


I don't know if this also works for newer versions, so take this with a grain of salt.

I hope this helps.

**Comment by Aurore35** [comment]
Hi adddvent,
Great this finally works!!! Many thanks!

**Comment by almarklein** [comment]
Thanks for the help @adddvent, and for referencing the anaconda issue. Very strange that the fact that there is a workaround made them close the issue.
