### ISSUE TITLE
Pyzo error Big Sur

### ISSUE THREAD

**Issue by lvante** [pyzo/pyzo#755]
Dear,

I have been using Pyzo (version 4.4.2) for a while on MacOs Catalina. Today, I have updated to MacOs Big Sur and when opening Pyzo, I get the following message:

_Dyld Error Message:
  dyld: No shared cache present
Library not loaded: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python
  Reason: image not found

Binary Images:
       0x100000000 -        0x100000fff +org.python.python (3.6.3 - 3.6.3) <DB2A01C0-6DBB-DB93-EC82-117C736AC754> /Library/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python
    0x7fff60b01000 -     0x7fff60b9cfff  dyld (852) <1AC76561-4F9A-34B1-BA7C-4516CACEAED7> /usr/lib/dyld_

---
I read online that python 3.6 is not supported on Big Sur any more and therefore that one should update to a newer version (e.g. 3.9). Therefore, I downloaded python 3.9. However, when configuring the shell to 3.9, I get the following error in the shell:

_Traceback (most recent call last):
  File "/Applications/pyzo.app/Contents/MacOS/source/pyzo/pyzokernel/start.py", line 46, in <module>
    import yoton
  File "/Applications/pyzo.app/Contents/MacOS/source/pyzo/yoton/__init__.py", line 39, in <module>
    from yoton.clientserver import RequestServer, do_request
  File "/Applications/pyzo.app/Contents/MacOS/source/pyzo/yoton/clientserver.py", line 81
    def __init__(self, address, async=False, verbose=0):
                                ^
SyntaxError: invalid syntax_

I have no clue how to fix this new error. I read someone online advising me to update Pyzo, however I cannot find a way to update Pyzo.
Can anyone help me out? 

If you need more information on certain versions etc., please let me know and I will look them up, as I am not sure what information is needed!

**Comment by SzamCha** [comment]
Hi,
I don't remember having the same problem or how I fixed it if I had it.
Here is the screenshot of my working shell configuration if it helps.

Best regards

**Comment by lvante** [comment]
> Hi, I don't remember having the same problem or how I fixed it if I had it. Here is the screenshot of my working shell configuration if it helps. Best regards
> […](#)

Am I correct that I do not see an image attached?

**Comment by SzamCha** [comment]
Here is the picture 
<img width="752" alt="Capture d’écran 2021-07-20 à 15 38 19" src="https://user-images.githubusercontent.com/70018865/126449641-27cfc0e6-4777-41bc-8264-d9a5ec189264.png">

**Comment by lvante** [comment]
> Here is the picture
> <img alt="Capture d’écran 2021-07-20 à 15 38 19" width="752" src="https://user-images.githubusercontent.com/70018865/126449641-27cfc0e6-4777-41bc-8264-d9a5ec189264.png">

Thank you for the reply! I tried using the same settings, but this still yields the same problem, namely:

_Traceback (most recent call last):
  File "/Applications/pyzo.app/Contents/MacOS/source/pyzo/pyzokernel/start.py", line 46, in <module>
    import yoton
  File "/Applications/pyzo.app/Contents/MacOS/source/pyzo/yoton/__init__.py", line 39, in <module>
    from yoton.clientserver import RequestServer, do_request
  File "/Applications/pyzo.app/Contents/MacOS/source/pyzo/yoton/clientserver.py", line 81
    def __init__(self, address, async=False, verbose=0):
                                ^
SyntaxError: invalid syntax_

**Comment by almarklein** [comment]
That's a very odd error. That file is normally valid Python. The only reason I can think of now is that this file has somehow changed. Perhaps you could try replacing that file with a fresh version from here: https://github.com/pyzo/pyzo/blob/master/pyzo/yoton/clientserver.py

**Comment by lvante** [comment]
> That's a very odd error. That file is normally valid Python. The only reason I can think of now is that this file has somehow changed. Perhaps you could try replacing that file with a fresh version from here: https://github.com/pyzo/pyzo/blob/master/pyzo/yoton/clientserver.py

If I go to the map location, I do not see a file called "clientserver.py". 
Could you maybe tell me how I download the file from that link? I am not that familiar with using Github. Thank you already for helping!

**Comment by almarklein** [comment]
Ah, I think you may be using an older version of Pyzo. You can update via e.g. `pip install -U pyzo`

**Comment by lvante** [comment]
> Ah, I think you may be using an older version of Pyzo. You can update via e.g. `pip install -U pyzo`

Tried doing that before, however as my shells are not working I cannot do those commands. Can I run it in the terminal doing something like:
`python3.9 pip install -U pyzo`

Thank you!

**Comment by almarklein** [comment]
`python -m pip install -U pyzo`

Maybe `python` would need to be different to target the 3.9 exe.

**Comment by lvante** [comment]
> `python -m pip install -U pyzo`
> 
> Maybe `python` would need to be different to target the 3.9 exe.

`python3.9 -m pip install -U pyzo` worked and said that it 'successfully installed pyzo-4.11.2'. However, opening pyzo it still says version 4.4.2 (as before). Already restarted my computer, didn't change.

Any tips what I can do?

**Comment by almarklein** [comment]
Could it be that when you start Pyzo, it is not using Python 3.9? (you can see this in the about dialog too).

**Comment by lvante** [comment]
> Could it be that when you start Pyzo, it is not using Python 3.9? (you can see this in the about dialog too).

It is probably not using Python 3.9 indeed, my about dialog namely mentions:
Pyzo - Python to the people!

Version info
Pyzo version: 4.4.2 (binary)
Platform: darwin
Python version: 3.4.6
Qt version: 4.8.7
PySide version: 1.2.2

Pyzo directories
Pyzo source directory: /Applications/pyzo.app/Contents/MacOS/source/pyzo
Pyzo userdata directory: /Users/name/.pyzo

---
Which is really strange, as I do not have python 3.4 installed at all (as far as I can see). I have two version in my path, namely 3.6 and 3.9 at the path:
/Library/Frameworks/Python.framework/Versions

**Comment by almarklein** [comment]
Oh, I see what's going on. I somehow assumed you were running Pyzo from source, but you're not. You should just download and install the latest Pyzo, and that should probably fix it :)

**Comment by lvante** [comment]
> Oh, I see what's going on. I somehow assumed you were running Pyzo from source, but you're not. You should just download and install the latest Pyzo, and that should probably fix it :)

Thanks for the reply!
One more question about installing the new pyzo:Do I remove the older version of pyzo first? If so, what should I exactly remove (as I know that simply dragging the program to the trash does not remove all other packages).

**Comment by almarklein** [comment]
Yes, I think you can drag it to the trash. Pyzo is independent from the Python versions installed on the system. In other words, the Pyzo app should be self-contained. One exception is the configuration, which is stored elsewhere on the system.

**Comment by lvante** [comment]
It is indeed working when using the new downloaded one. However, I cannot install pyzo as an application anymore. It immediately goes to my desktop background

Is there a way to install it as an application (as it was before)?

**Comment by lvante** [comment]
I fixed the problem of the figures not closing by installing PyQt5.
It seems now that my pyzo is working as before! Thank you very much for your help :D

**Comment by almarklein** [comment]
Glad to hear!
