### ISSUE TITLE
4.11.4 broken on MacOS: damaged dmg file

### ISSUE THREAD

**Issue by jowe19** [pyzo/pyzo#769]
Hi, 
I just downloaded Pyzo version 4.11.4, but I can't open the application (Mac OS Monterey 12.0.1).
<img width="326" alt="Capture d’écran 2021-11-28 à 14 16 04" src="https://user-images.githubusercontent.com/19306526/143769502-56982a82-94d5-4743-acc9-6149b1806ae5.png">

**Comment by almarklein** [comment]
Thanks for the report. This looks similar to #756. I had hoped that maybe it was a glitch in PyInstaller that had been fixed in the mean time. I'm not sure what it could be otherwise and right now I don't have the time (nor a Mac machine) to look into this.

For the time being, please install Pyzo from source (required pyqt5 or pyside2).

**Comment by jowe19** [comment]
Thanks for your answer. I will stay for the moment in 4.11.2 (that works perfectly). I prefer to have Pyzo as an independent application in my applications folder.

**Comment by almarklein** [comment]
Interesting that 4.11.2 *does* work... that suggests that this is different from #756.

**Comment by almarklein** [comment]
I build a new version with pyinstaller pinned to an earlier version. Could you please test it?

https://github.com/pyzo/pyzo/releases/download/v4.11.4/pyzo-4.11.5-macos.dmg

**Comment by jowe19** [comment]
Unfortunately, I still have the same error

**Comment by operade** [comment]
Hi it is the same problem with the new release : 4.11.7

**Comment by almarklein** [comment]
I revamped the whole freezing process. Could the people who are watching this please try the binary here? Result for testing here: https://github.com/almarklein/pyzo/releases/tag/vt201 Please let me know whether it works for you!

**Comment by jowe19** [comment]
> I revamped the whole freezing process. Could the people who are watching this please try the binary here? https://github.com/almarklein/pyzo/releases/tag/vt201 Please let me know whether it works for you!

I have the same problem with this version.

**Comment by almarklein** [comment]
There is now also a .zip for MacOS. Does that work?

**Comment by operade** [comment]
Still the same problem with the .dmg file. I don't see how to use the zip file : sorry

**Comment by almarklein** [comment]
Could you try this zipfile? https://github.com/pyzo/pyzo/releases/download/v4.11.7/pyzo-4.11.7-macos_x86_64.zip

**Comment by jowe19** [comment]
I get the following error message.

**Comment by jowe19** [comment]
I get the following error message. 

<Capture d’écran 2022-01-14 à 00.19.14.png>

**Comment by almarklein** [comment]
Thanks for testing! The error dialog that I put in place is proofing useful :) I think I fixed it. Could you please try the new zip? And maybe also the new dmg?

https://github.com/pyzo/pyzo/releases/download/v4.11.7/pyzo-4.11.7.11-macos_x86_64.zip
https://github.com/pyzo/pyzo/releases/download/v4.11.7/pyzo-4.11.7.11-macos_x86_64.dmg
