### ISSUE TITLE
4.11.4 broken on Windows: side-by-side configuration is incorrect

### ISSUE THREAD

**Issue by YoannUniKS** [pyzo/pyzo#771]
Hi,
I just updated pyzo from 4.11.2 to 4.11.4 on Windows 10 and when I try to open the program, I am getting the "side-by-side configuration is incorrect" error.
I went back to 4.11.2 and everything is working fine again.
Thanks for the very nice tool.
Regards,

**Comment by almarklein** [comment]
Thanks for the report. The 4.11.4 release seems to be broken for Mac as well. Not sure what's going on here ...

**Comment by austin-schick** [comment]
I've had a few students encounter this error as well. Using the 4.11.2 installer worked for them when 4.11.4 didn't.

**Comment by almarklein** [comment]
This is apparently a known issue: https://github.com/pyinstaller/pyinstaller/issues/6371

**Comment by almarklein** [comment]
I was able to reproduce the error. I made a new build with pyinstaller pinned to v4.6, and it works for me again. 

The link on the website has been updated: https://github.com/pyzo/pyzo/releases/download/v4.11.4/pyzo-4.11.5-win64.exe

If someone can please confirm/deny this, that'd be great.

**Comment by YoannUniKS** [comment]
Thanks a lot, it works fine for me as well with 4.11.5.

Cheers
