### ISSUE TITLE
'PySide2.QtWidgets.QApplication' has no attribute 'exec' with Python 3.9.9

### ISSUE THREAD

**Issue by MeisterLLD** [pyzo/pyzo#773]
Since a Pyzo update on my system (Pyzo 4.11.4 on Arch Linux 5.15.6-arch2-1), my shell shows the following : 

> Python 3.9.9 (main, Nov 20 2021, 21:30:06) on linux (64 bits).
This is the Pyzo interpreter with integrated event loop for PYSIDE2.
Type 'help' for help, type '?' for a list of *magic* commands.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pyzo/pyzokernel/start.py", line 159, in <module>
    __pyzo__.run()
  File "/usr/lib/python3.9/site-packages/pyzo/pyzokernel/interpreter.py", line 224, in run
    self.guiApp.run(self.process_commands, self.sleeptime)
  File "/usr/lib/python3.9/site-packages/pyzo/pyzokernel/guiintegration.py", line 578, in run
    exec_ = getattr(self._QtGui.real_QApplication, "exec")
AttributeError: type object 'PySide2.QtWidgets.QApplication' has no attribute 'exec'

>The kernel process exited. (1)

The problem is solved if I use a shell with Python 2.7 instead. This happened on both my laptop and my PC, both having the same Arch Linux version, Python versions, and Pyzo versions.

**Comment by MeisterLLD** [comment]
Replacing line 578 of /usr/lib/python3.9/site-packages/pyzo/pyzokernel/guiintegration.py
from
`        exec_ = getattr(self._QtGui.real_QApplication, "exec")`
to
`        exec_ = getattr(self._QtGui.real_QApplication, "exec_")`

solves the problem

**Comment by almarklein** [comment]
It tries to be smart about this:
https://github.com/pyzo/pyzo/blob/9364915a5e07e16129b84b1dd03682823da2253f/pyzo/pyzokernel/guiintegration.py#L578-L580

But I forgot to add a `None` argument to `getattr` ... woops
