### ISSUE TITLE
MacOS downloads contain version 0.0.0 instead of 4.12.0

### ISSUE THREAD

**Issue by suschizu** [pyzo/pyzo#790]
I've noticed that the version numbers in following downloads are not correct:
https://github.com/pyzo/pyzo/releases/download/v4.12.0/pyzo-4.12.0-macos_x86_64.dmg
https://github.com/pyzo/pyzo/releases/download/v4.12.0/pyzo-4.12.0-macos_x86_64.zip

info.plist contains wrong /  missing version information:
 
CFBundleShortVersionString:
0.0.0
CFBundleVersion:
(empty)

<img width="251" alt="Screenshot 2022-01-21 at 17 48 01" src="https://user-images.githubusercontent.com/16004333/150567230-5034258b-7137-4912-8dda-68b78d3391e8.png">

**Comment by almarklein** [comment]
Thanks for the report!

Searching for "plist" on [this page](https://pyinstaller.readthedocs.io/en/stable/spec-files.html?highlight=plist#spec-file-options-for-a-mac-os-x-bundle) shows how to fix this.
