### ISSUE TITLE
Can't open Pyzo 4.12.0 on MacOS 10.13

### ISSUE THREAD

**Issue by xavier862** [pyzo/pyzo#792]
When I attempt to  launch Pyzo 4.12.0 on MacOS 10.13 (High Sierra), here is the message I get in Console:

> Error loading Python lib '/Applications/Developer/Python/pyzo.app/Contents/MacOS/libpython3.10.dylib': dlopen: dlopen(/Applications/Developer/Python/pyzo.app/Contents/MacOS/libpython3.10.dylib, 10): Symbol not found: ____chkstk_darwin
>   Referenced from: /Applications/Developer/Python/pyzo.app/Contents/MacOS/libintl.8.dylib (which was built for Mac OS X 11.0)
>   Expected in: /usr/lib/libSystem.B.dylib
>  in /Applications/Developer/Python/pyzo.app/Contents/MacOS/libintl.8.dylib

The latest Pyzo version I am currently able to open is 4.10.2.

**Comment by almarklein** [comment]
I first suspected that the machine that builds the binary is newer, though it does say "which was built for Mac OS X 11.0" ... so I'm not sure what's going on at the moment to be honest.

As a workaround, I'd recommend installing Pyzo from source: install pyqt5 or pyside6 and `pip install pyzo`.
