### ISSUE TITLE
'IPython.utils.io' has no attribute 'IOStream'

### ISSUE THREAD

**Issue by UniqASL** [pyzo/pyzo#796]
Hi,

The last version of IPython 8.1.1 is not working anymore in Pyzo (4.12.0, Windows 10), I'm getting the following error:

> IPython could not be loaded: module 'IPython.utils.io' has no attribute 'IOStream'

Downgrading to IPython 7.32.0 solves the problem.

I [have been asking IPython](https://github.com/ipython/ipython/issues/13576) and the problem seem to come from Pyzo and not from their side.

Any idea how this problem can be solved?

**Comment by almarklein** [comment]
It looks like their API has changed and we need to adjust accordingly.

**Comment by almarklein** [comment]
I looked into this, but it looks like the factored that class away, and now I don't know how to fix it. It also looks like IPython integration is broken on MacOS for another reason. 

If anyone wants to look into it, this is the relevant code for this issue:
https://github.com/pyzo/pyzo/blob/ba3d7ebb3953f9cb83c430f467f54ef0f42e6369/pyzo/pyzokernel/interpreter.py#L591-L599

It could be that IPython has changed in a way that this fix-for-Windows is no longer needed. You can try editing this file on your local machine (see "help > about pyzo" for the location of your source directory).

**Comment by UniqASL** [comment]
Hi,

thanks for your help. I slightly changed the code and created a [pull request](https://github.com/pyzo/pyzo/pull/803).

So far it is working without problem, IPython 8.1.1 is loading.

Cheers
