### ISSUE TITLE
PDF export broken on Windows 10 due to No module named 'PySide6.QtPrintSupport'

### ISSUE THREAD

**Issue by ysalmon** [pyzo/pyzo#798]
Hi,

a (non tech-savvy at all) collegue of mine recently installed Pyzo 4.12 on her new Windows computer.

When she tries to export her code to PDF via the adequate menu, nothing happens.

I had her view the logger, and it is telling :
```
Python 3.10. on win32 - This is the Pyzo logger shell.


loading qt French: failed

loading pyzo French: ok

Uncaught Python exception: No module named 'PySide6.QtPrintSupport'

File "C:\Program Files\pyzo\source\pyzo\core\menu.py", line 311, in <lambda>

a.triggered.connect(lambda b=None: callback())

File "C:\Program Files\pyzo\source\pyzo\core\menu.py", line 544, in <lambda>

lambda: PdfExport().exec(),

File "C:\Program Files\pyzo\source\pyzo\core\pdfExport.py", line 18, in __init__

from pyzo.qt import QtPrintSupport

File "C:\Program Files\pyzo\source\pyzo\qt\QtPrintSupport.py", line 23, in <module>

from PySide6.QtPrintSupport import *
```

It looks like an inconsistency between what is shipped and was is imported. Or does she need to install some dependency ?

I have no access to the machine and have not used Windows for 12 years, so I cannot be more precise.

**Comment by almarklein** [comment]
This is because some of the API of QPrinter has changed between qt6 and qt5. Fixing in #801.

**Comment by ysalmon** [comment]
That's no better, presumably because the (faulty ?) import is still there : https://github.com/pyzo/pyzo/blob/072198b8446ee801932b7b5b735980d865c367bd/pyzo/qt/QtPrintSupport.py#L17

**Comment by almarklein** [comment]
Right. I tried to reproduce this issue, and found another bug with PDF export, and assumed that was the same. Could have seen that from the traceback :)

It looks like QtPrintSupport is not marked as an include, when the freezing process was recently refactored.

**Comment by almarklein** [comment]
New release ready. Thanks for the report @ysalmon !

**Comment by ysalmon** [comment]
Credit for spotting this goes to Marie-Liesse Ray !

**Comment by almarklein** [comment]
Thanks Marie-Liesse!
