### ISSUE TITLE
Cannot change theme 

### ISSUE THREAD

**Issue by Myvh** [pyzo/pyzo#805]
When I restart Pyzo (`File > Restart Pyzo`), I get an error message when Pyzo reopens:
![Capture d’écran 2022-06-09 110300](https://user-images.githubusercontent.com/68384832/172809050-e774b598-9400-492a-9de6-721cafdb48f1.png)
I don’t get any error message if I quit Pyzo then manually restart it. However, if I go to `Settings > Edit syntax styles… `, choose a non-default theme and click on `Apply theme`, Pyzo automatically restarts, I get the error message, and the theme is still the default one. As a consequence, I cannot change the theme.

I use Windows 10 64 bits. Here is the `About Pyzo` info:
```
Version info
Pyzo version: 4.12.3 (binary)
Platform: win32
Python version: 3.10.2
Qt version: 6.2.3
PySide6 version: 6.2.3

Pyzo directories
Pyzo source directory: C:\Program Files\pyzo\source\pyzo
Pyzo config directory: C:\Users\Myvh773\AppData\Roaming\pyzo
Pyzo userdata directory: C:\Users\Myvh773\AppData\Roaming\pyzo
```

I uninstalled Pyzo, restarted Windows, reinstalled Pyzo and restarted Windows again, but the bug is still here.

**Comment by almarklein** [comment]
Interesting. Could you try selecting "restart Pyzo" from the File menu?  I'll have a look at my Windows machine later this week.

**Comment by Myvh** [comment]
> Interesting. Could you try selecting "restart Pyzo" from the File menu?
I already tried it, as I said at the beginning.

**Comment by almarklein** [comment]
> I already tried it, as I said at the beginning.

Ah right :)

**Comment by almarklein** [comment]
Ah I think I know what's going on. I can indeed reproduce the error message on Windows. However, this message can safely be ignored and does not (as far as I can tell) affect the saving of any settings.

As for editing the theme: the colors of builtin themes cannot be changed (even though their values can be edited). Someone should probably make these values readonly. To edit individual colors, create a new theme from an existing one, and edit the colors in that.

As for the error message: I made #806 to make it disappear.

**Comment by Myvh** [comment]
I still cannot change Pyzo’s theme. Here is what happens:
- I go to `Settings > Edit syntax styles…`.
- The current theme is `default`, and I choose another builtin theme in the list.
- I click on `Apply theme`, which immediately restart Pyzo.
- When Pyzo reopens, I get the error window and the theme has not changed.

**Comment by almarklein** [comment]
Ok, then there is a problem. When I tried this morning it worked fine. Will have another look.

**Comment by 3RROR-4O4-1** [comment]
i am also on windows and have this exact same problem :/

**Comment by 3RROR-4O4-1** [comment]
man i hate the default theme no offense, but it burns my eyes

**Comment by x151973** [comment]
back to 4.11.2, all fine.

**Comment by jowe19** [comment]
> i am also on windows and have this exact same problem :/

The same on MacOS, but without error message.

**Comment by labviewguru73** [comment]
Not sure if anyone else found this work around but I just got the theme change to work and it was there when I relaunched Pyzo.

This is the following steps I took:

Settings menu button/Advanced Settings/settings/theme
I double clicked the field where default was and entered "dark" (without the quotes) and then closed Pyzo. 

When  relaunched Pyzo my settings worked. I did NOT select the restart pyzo from the menu. I think the bug may be in the restart script for Pyzo because if I choose restart pyzo from the file menu I get the error loading file pop-up.

Enjoy!

**Comment by Myvh** [comment]
> Not sure if anyone else found this work around but I just got the theme change to work and it was there when I relaunched Pyzo.
> …

Nice workaround, it worked for me. Thanks!

**Comment by labviewguru73** [comment]
Glad to help. Hopefully the bug can be located and fixed.

**Comment by 3RROR-4O4-1** [comment]
Thanks ! Do you know if there a way to change the outlining?

**Comment by Myvh** [comment]
> Thanks ! Do you know if there a way to change the outlining?

Are you talking about the areas other than the text editor and the shell?

**Comment by almarklein** [comment]
I was indeed able to reproduce the error on Windows. It looked like Pyzo was closed before the config was stored.
