### ISSUE TITLE
Pyzo don't open/install on Mac 10.14.6

### ISSUE THREAD

**Issue by Drakanoward** [pyzo/pyzo#809]
When I try to open Pyzo from the dmg file to install it, it said Pyzo is an app downloaded from Internet, do you want to open it? 
I click on Open, it shows me 1 of those 2 errors (sometime it's the first, sometime the second, I don't know why):
<img width="532" alt="Capture d’écran 2022-07-17 à 11 35 29" src="https://user-images.githubusercontent.com/109460785/179393157-6ae71c8f-a701-42ee-9872-e657f6bc50d2.png">
<img width="532" alt="Capture d’écran 2022-07-17 à 11 35 47" src="https://user-images.githubusercontent.com/109460785/179393172-2678e15c-3d2c-4ed8-87cd-83ab658b34b0.png">
Then, if I click OK, it closes the window and Pyzo don't open.

I tried to download it a second time, it doesn't change anything.
I need help please, but I am a total novice, this is my first time in that domain.

**Comment by almarklein** [comment]
Hi @Drakanoward , you should not open Pyzo from the dmg, but copy it to your machine (preferably to your applications folder). Please let me know whether this solves the issue or whether it still fails.

**Comment by almarklein** [comment]
Ah, I think I see what the problem is. It looks like the MacOS binary is build for MacOS 10.15 and up. IIRC this is mostly a choice in PyInstaller.

So in your case, the way to use Pyzo would be to install PySide6 or PyQt5 and then pyzo via pip.
