### ISSUE TITLE
Python-3.11 / PyQt6 compatibility ?

### ISSUE THREAD

**Issue by stonebig** [pyzo/pyzo#811]
I can get PyQtGraph and Qtconsole to work on cpython-3.11.0rc1 and PyQt6-6.3.2.dev2207241007-cp37-abi3-win_amd64.whl.
But Pyzo, the next step in complexity for me, fails just before the bis splash screen.

**Comment by m-jishnu** [comment]
the last verson where pyqt worked for me was in ver 3.9.12 afterwards it doesnt install or causes some errors

**Comment by almarklein** [comment]
Not sure if this is the same, but in PySide 6.4, they changed a few things that breaks Pyzo rather hard. For one, enums are no longer present on instances (only on classes). There's a lot of enums, and no way AFAIK to find them accurately except for running Pyzo and see where it breaks :/

**Comment by almarklein** [comment]
Just checked that it works with py3.11 and PySide6.4 on MacOS. I expect that this error was fixed in #824. If you still encounter this problem, let me know, and I'll reopen.
