### ISSUE TITLE
Force a specific python executable declaratively

### ISSUE THREAD

**Issue by SCOTT-HAMILTON** [pyzo/pyzo#814]
Hello, I'm using NixOS and I'm packaging pyzo. The strength of Nix is to make everything declarative, so I'm trying to declaratively configure pyzo through nix to make it use the python executable I want, thus being able to leverage the excellent Nix's python ecosystem.

Therefore I'm asking if it's possible to force pyzo to use a specific python binary. Either with:
 - Environment variable
 - CLI
 - Config (not the best)
Note: If the only way is through a config file, then this file will have to be read-only because if nix produces it, then it's a declarative output which must be immutable.

If this isn't possible yet, I'm happy to try and implement whatever above solutions you like the best and open a PR if I'm successful with it.

**Comment by almarklein** [comment]
>  if it's possible to force pyzo to use a specific python binary

Do you mean for the process that runs Pyzo, or for the shell, as an override for the shell configuration?

**Comment by SCOTT-HAMILTON** [comment]
The use case is to be able force the pyzo IDE to use a specific python executable without having to set it manually via the menu. That would make integration with Nix much easier.

**Comment by almarklein** [comment]
At the moment this does not exist, but I would be open for an ENV var or CLI arg that sets up a default shell when there are none yet.
