### ISSUE TITLE
Shell crash upon indentation error with one space

### ISSUE THREAD

**Issue by RivetBenoit** [pyzo/pyzo#815]
In Pyzo 4.12.3, the shell crashes upon indentation errors with a single space. The following dumb script 
```
a = 1
  a = 2
```
with an indentation error of 2 spaces raises an `IndentationError` (as expected) 
```
>>> (executing file "<tmp 1>")
  File "<tmp 5>", line 2
    a = 2
IndentationError: unexpected indent
```
Howevern, the following dumber script 
```
a = 1
 a = 2
```
with an indentation error of a single space crashes the shell, which may be overreacting to such a stupid error :
```
Exception in yoton.SendingThread.
notifyAll() is deprecated, use notify_all() instead
line 405 of C:\WinPython\python-3.10.5.amd64\lib\threading.py.

The kernel process exited. (0)
```
The culprit seems to be line 572 in pyzo\yoton\misc.py : after changing
```
                condition.notifyAll()  # wait() procedes
```
to :
```
                condition.notify_all()  # wait() procedes
```
the shell doesn't crash anymore and raises the expected `IndentationError`. I guess this closes the issue ;-)

**Comment by almarklein** [comment]
These occurances of `notify_all` have been fixed.
