### ISSUE TITLE
Inability to change the syntax style

### ISSUE THREAD

**Issue by AntoninDegros** [pyzo/pyzo#817]
Hi,

I have an issue with the syntax style setting.
When i want to change the syntax style (from default to another), after restarting Pyzo, an error appears : "embedded null character". No matter what I do, the error still appears, making it impossible to change the syntax style.

Version : 4.12.3 (binary) ; Platform: win32 ; Python Version : 3.10.2 ; Qt version : 6.2.3 ; PySide6 version : 6.2.3.

![image_2022-10-21_150207560](https://user-images.githubusercontent.com/116147687/197202040-317664a0-0bab-4ca4-b5d0-c3c1b185658a.png)

**Comment by almarklein** [comment]
Looks a bit like #805, but with a different error message.

**Comment by AntoninDegros** [comment]
> Looks a bit like #805, but with a different error message.

I looked around a bit and found out how to fix the problem. Thanks a lot !

**Comment by almarklein** [comment]
Out of curiosity, did you use the workaround mentioned in #805?
