### ISSUE TITLE
matplotlib.pyplot.plot() creates a TypeError

### ISSUE THREAD

**Issue by MeisterLLD** [pyzo/pyzo#832]
Hello. Since more or less recently (sorry that I can't be more precise), any call to plot from matplotlib.pyplot in Pyzo gives me the following error, which is repeated ad vitam

`TypeError: notify(self, QObject, QEvent): first argument of unbound method must have type 'QApplication'`

This appears only in Pyzo : I have no problem with manually executing my python files. I have no idea where it comes from.

I am using Pyzo 4.12.4 on a 6.1.1-arch1-1 Linux distribution.

**Comment by almarklein** [comment]
What Qt lib are you using (PySide / PyQt) and what version?

**Comment by MeisterLLD** [comment]
Thanks. Asking myself your question made me solve my problem. Pyzo was set
on "auto". Setting manually PyQt5 solved the problem.

Since it might still be interesting to understand what happened, here is my
output of of pip list.

> PyQt5 5.15.7
>
> PyQt5-sip 12.11.0
>
> PyQt6 6.4.0
>
> PyQt6-sip 13.4.0
>
> PyQt6-WebEngine 6.4.0
>
PySide2 5.15.7
>

Funnily enough,  all of these manual choices (and others like Asyncio,
Tornado, TK...) work, except PyQt6, but PyQt6 does not produce the same
error messages, it just produces an exit from kernel process (-6). So no
manual GUI choice in Pyzo allows to retrieve the same error messages.

Le dim. 8 janv. 2023 à 23:03, Almar Klein ***@***.***> a
écrit :

**Comment by almarklein** [comment]
> So no manual GUI choice in Pyzo allows to retrieve the same error messages.

Interesting. What GUI is selected when you've set it to "auto"? (The kernel tells you in its startup message.)


IIRC PyQt6 is preferred by Pyzo when in "auto" mode, but Matplotlib probably does not support it yet, so it selects PyQt5, and now you are using two different Qt API's in the same process. In my experience this always breaks in bad/mysterious ways.

**Comment by MeisterLLD** [comment]
Weirdly enough, it says "This is the Pyzo interpreter with integrated event
loop for PYSIDE2" but when I manually select PySide 2 from "Edit Shell
Configurations", it works.

Le lun. 9 janv. 2023 à 09:34, Almar Klein ***@***.***> a
écrit :

**Comment by almarklein** [comment]
My guess is that you have a broken installation of another QT lib in your environment. Pyzo tries to load GUI backends one by one. It may have loaded the broken one, and then continued on to pyside2, resulting in a state where 2 Qt libs are loaded.
