### ISSUE TITLE
Directory name filter in the file browser

### ISSUE THREAD

**Issue by clavay** [pyzo/pyzo#848]
Hello,

Is it possible to add directory name filter in the file browser ?
The current filter only use the [basename](https://github.com/pyzo/pyzo/blob/main/pyzo/tools/pyzoFileBrowser/tree.py#L122).

It is useful when searching a word in multiple files to select the subdirs to include or to exclude.

**Comment by almarklein** [comment]
I think what could work is that for elements in the filter that end with a `/`, could match to dirs.
