### ISSUE TITLE
Search in big files other than python files

### ISSUE THREAD

**Issue by clavay** [pyzo/pyzo#849]
Hello,

It could be good to let the user to choose the search file types without limit (not only `.py`) and to change the limit for the other file types (fixed to `100 * 1024 bytes`).

See [here](https://github.com/pyzo/pyzo/blob/102e30877d8235e2e6cec2f485a4ee1cbb721c4c/pyzo/tools/pyzoFileBrowser/tasks.py#L58)

The solution could be a search menu with : 
- filter for files without size check like `*.py *.sh`
- filter for other file size `100KiB`, `1MiB`...

**Comment by almarklein** [comment]
A simple solution could be to allow searching any file types that are explicitly mentioned in the filter. So if you have a bunch of large .txt files, you can add `*.txt` to the filter.
