### ISSUE TITLE
Application aborted while Runnig Pyzo

### ISSUE THREAD

**Issue by cdavailable** [pyzo/pyzo#859]
Hi everyone! I could use your help please.

Before when a file was open on the Pyzo window, and I double clicked on another .py file, it opened directly on the Pyzo editor. I installed the new version of Pyzo and when I do the same operation, I get a cmd window that opens and closes several times before displaying this message "Application aborted while Running Pyzo. SystemExit:" And then, the file opens in the editor.

Do you have any idea how to fix this problem. Thank you very much for your help.

**Comment by bdieterm** [comment]
Hi @cdavailable!
PR #860 will fix this problem.

**Comment by almarklein** [comment]
Closed by #860
