### ISSUE TITLE
Problems with older Mac OSX systems.

### ISSUE THREAD

**Issue by edwilliams16** [pyzo/pyzo#901]
I have an M1 Mac running Ventura 13.4.1 (22F82) - on it pyzo 4.13.2 runs fine.

   On my High Sierra 10.13 Mac, the pyzo.app won't click start.  If I download the zip and run from the command-line
`python3 ~/pyzo/pyzo-main/pyzolauncher.py`
pyzo starts, but there is no shell prompt.  The process is burning up time, but I can't interact with it.

 If I revert to 4.12.7, I still can't click-launch, but I can successfully run from the command-line. 

My 10.15 Mac behaves the same as the 10.13, but I've not tested it as much.

(I've dealt with the unknown developer stuff.)

**Comment by almarklein** [comment]
Thanks for reporting this!

This may be a problem that's hard to reproduce without having a Mac with that specific OS version. Would you mind, if you have the time, to narrow down between what version numbers it breaks exactly? We could then investigate the corresponding changes in that particular release to see if anything suspicious comes up ...

**Comment by edwilliams16** [comment]
I've now found with 4.13.3 that I can successfully launch from the command line, so a little shell script is a work-around.
None of the .app versions I tried (4.12.3, 4.12.7, 4.12.8, 4.13.2 or 4.13.3) will click-launch.

**Comment by edwilliams16** [comment]
I tried pyzo-4.14.3 on my Mac OSX 10.13 system. The source code is launching correctly, I believe, with
`/Applications/FreeCAD.app/Contents/Resources/bin/python ~/pyzo-4.14.3/pyzolauncher.py
Started our command server`
using FreeCAD's python which has PySide2 installed

But when I now try to click-launch the pyzo.app, I get
`ModuleNotFoundError: No module named ‘PyQt5‘`
before nothing would happen, so progress has been made.
I tried
`pip3 install PyQt5`
installing it in the Mac's python3 environment (I assume), but I still get the not found error.  I'm not sure how to get PyQt5 in the _pyzo.app'_s environment,
With
`python3 ~/pyzo-4.14.3/pyzolauncher.py
Our command server is *not* running`

I don't know if that is a problem

**Comment by almarklein** [comment]
> But when I now try to click-launch the pyzo.app, I get
> `ModuleNotFoundError: No module named ‘PyQt5‘`

Aha! The binary is shipped with Pyside6, but this message suggests that it is unable to load it. My guess is that PySide6 is incompatible with older Mac versions, causing Pyzo to try to load PyQt5 instead, but that's not part of the binary (you cannot install additional libs into the binary distribution).

My suggestion would be to load Pyzo from source. Just install Python and a Qt lib (PySide2 or PyQt5 probably) and `pip install pyzo`.

**Comment by edwilliams16** [comment]
> My suggestion would be to load Pyzo from source. Just install Python and a Qt lib (PySide2 or PyQt5 probably) and pip install pyzo

That works fine.  Perhaps you might put a pointer to that for those for whom the binary fails. Thanks.

**Comment by almarklein** [comment]
Good point. I updated the installation instructions on the website.
