### ISSUE TITLE
Dark Mode on Windows 10 results in inconsistent theme

### ISSUE THREAD

**Issue by TeunBartelds** [pyzo/pyzo#914]
Great to see some active development on Pyzo again! We use it as a default editor within our company and recently updated to the latest version (after several years).

After installation the theme looks like this, making me think the installation was broken / corrupt:
![image](https://github.com/pyzo/pyzo/assets/11867578/0b7d4e54-4ebe-4ea8-aaf9-a519fa859ab7)

However, after reading #841 and applying the 'Dark Syntax Styles' things became more consistent:
![image](https://github.com/pyzo/pyzo/assets/11867578/e0fa223b-71dd-4bdb-bdd8-564d895eb185)

It seems that switching light/dark themes is not very robust (at least under windows 10). So several general questions / issues I found:
- After installation the theme seems inconsistent (combining both light and dark appearances)
- Switching system wide colour mode from light to dark or vice versa results in the same inconsistencies
- Why is applying a syntax theme changing the general appearance of most widgets?
- Is it currently possible to override the windows system wide settings for light / dark colour themes?

I know this is quite a broad issue and is potentially not super easy to resolve. However, I'm afraid it might scare of users from updating and enjoying other improvements made. Is this a point of attention for current development activities?

**Comment by bdieterm** [comment]
> ... 
> It seems that switching light/dark themes is not very robust (at least under windows 10). So several general questions / issues I found:
> 
>     * After installation the theme seems inconsistent (combining both light and dark appearances)

The Qt 6.5 dark mode is automatically set by MS Windows depending on user preferences (at least when using the "fusion" Qt theme).
see https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5
This setting can also be changed via the registry editor:
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize
AppsUseLightTheme"=dword:00000001

I will add code to check if Qt has the dark mode activated and to then select the dark syntax style when starting Pyzo the first time.

>     * Switching system wide colour mode from light to dark or vice versa results in the same inconsistencies
What do you mean? Can you give examples with screenshots?

>     * Why is applying a syntax theme changing the general appearance of most widgets?
What do you mean? Syntax themes (Pyzo -> Settings -> Edit syntax styles...) do not do that, but Qt >= 6.5 itself,
see https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5

>     * Is it currently possible to override the windows system wide settings for light / dark colour themes?
The window frame color is determined by Qt and MS Windows. Maybe future versions of Qt might make it possible to override the color mode, see "Beyond Qt 6.5" in https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5
If you want to run Pyzo in light mode, either change MS Windows settings to light mode for all applications, or run Pyzo with Qt <= 6.4 .

> I know this is quite a broad issue and is potentially not super easy to resolve. However, I'm afraid it might scare of users from updating and enjoying other improvements made. Is this a point of attention for current development activities?

I actually always use light mode for all applications. But I can add some fixes and features if you want.
It would be great to have feedback from people who use Pyzo with dark mode enabled.
Can you write down a detailled list of what colors/elements have to be changed together with the new color code?
And can you also choose colors for a better syntax style "dark"?

**Comment by TeunBartelds** [comment]
Thanks for the quick and elaborate reply. Very informative to read the background article from the Qt blog.

> > ```
> > * Switching system wide colour mode from light to dark or vice versa results in the same inconsistencies
> > ```
> 
> What do you mean? Can you give examples with screenshots?

Both windows and syntax styles set to dark mode:
![image](https://github.com/pyzo/pyzo/assets/11867578/2ba713dd-6568-4212-afff-13c11e0b1419)

Changing windows style to light mode:
![image](https://github.com/pyzo/pyzo/assets/11867578/45d43fcd-eb5e-4c11-969e-427a1b943ec8)

Most widgets are updated correctly (after several seconds, not everything seems to be refreshed at once), however:
- The button that displays the current shell configuration name still has white text
- The titles of the dock widgets are still white
- The workspace widget has dark mode buttons, but a light background and white text
- The file browser is still shown in dark mode, except for the dock widget background
- Possibly several more similar inconsistencies, but you'll get the idea :)

If I now apply another theme, Pyzo seems to restart and all inconsistencies seem to be resolved:
![image](https://github.com/pyzo/pyzo/assets/11867578/ab131047-1998-4368-8862-c4b671c16791)

For this example I chose the other dark theme to rule out the option that the syntax theme directly affects the widget style. So my conclusion would be that the restart caused by applying a syntax style resolves the widget style inconsistencies. In that case, you can ignore my other question:
> > ```
> > * Why is applying a syntax theme changing the general appearance of most widgets?
> > ```

Is there a way for you to detect the change of windows style and force all widgets to be updated? Maybe you could ask the user whether he would like to update the syntax styles accordingly?

**Comment by bdieterm** [comment]
Hi @TeunBartelds!

> Is there a way for you to detect the change of windows style and force all widgets to be updated? Maybe you could ask the user whether he would like to update the syntax styles accordingly?

According to [this article](https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5)), at least for Qt >= 6.5 with on MS Windows 10, there is a signal to detect if the system-wide dark mode setting was changed. But is is not that easy if you consider the following points:
- This feature would not work with older Qt versions (without a work-around).
- Even when detecting the dark mode, Pyzo will have to switch the syntax theme and restart itself afterwards.
- There is not only one light and only one dark syntax theme. It would be necessary to ask the user anyways to switch the theme.
- In the Pyzo menu "View -> Qt theme", the user can select other Qt themes than the "Fusion" theme, and not all of them have proper dark mode support.

With my "improve dark mode" PR, Pyzo will detect dark-mode during Pyzo start-up and set variable `pyzo.darkQt` accordingly. So it would be possible to ask the user during start-up to switch the syntax theme if it does not match the Qt dark mode. But I don't think that this would be a good idea currently.
Instead, I added a function to automatically select a dark or light syntax theme when Pyzo is started the very first time (when there are no saved user settings yet).

Can you please test the new "default_dark" syntax theme? Is there anything that should be improved?

**Comment by TeunBartelds** [comment]
Okay. Personally I found the default_dark theme a little too bright on the various syntax colors. I made a personalized dark theme in which I colour-picked the background colours to match the background and border colours from the other widgets. Then I used the syntax colours from a [onedark.vim](https://github.com/joshdick/onedark.vim) theme I found.

default_dark (left) VS dark_teun (right):
![image](https://github.com/pyzo/pyzo/assets/11867578/242e5040-4896-4f46-8465-1f899193b6a1)

What do you think?

**Comment by bdieterm** [comment]
Thanks for the feedback. I actually never use dark mode, so I am the wrong person to ask. I am wondering if it is because of my screen settings, but for me it is hard to read the line numbers in your "dark_teun" syntax theme (and also in Pyzo's "dark" theme). By the way: When you double click a line number, you can enter a new target line number.

In your opinion, should we choose the existing "dark" theme as the default syntax theme instead? If you want to submit your "dark_teun.theme" file, we could incorporate this as the new "default_dark.theme" in the PR.

**Comment by almarklein** [comment]
Thanks @TeunBartelds for bringing up the bad implementation of the dark theme. And thanks for @bdieterm for the awesome fixes!

I'm not a darkmode user myself either, but I feel similar about class- and methodnames standing out. If the line numbers can be crancked up a wee bit, I think Teun's syntax is a nice improvement, and I think we should make *that* the default dark theme.

**Comment by almarklein** [comment]
Leaving this PR open to track that.

**Comment by TeunBartelds** [comment]
Ok, thanks for the feedback. I updated the line numbers to match the keyword colour (a lighter shade of grey).

I attemted to push the changed theme to the fix-darkmode branch, however I got an 'unabled to access error'. No experience with working on public repos, but does that mean I should create a branch such that you can merge it?

I attached it here as well (as .txt because .theme was not allowed): [default_dark.theme.txt](https://github.com/pyzo/pyzo/files/13473890/default_dark.theme.txt)

**Comment by almarklein** [comment]
I'm not sure if one can push to a branch of someone else. But I also merged the PR already, since it covered most ground.

Easiest would be for you pull the latest `main` and create a new PR with your theme.

**Comment by TeunBartelds** [comment]
I attempted to fork the repo and made a pull request. Let me know if anything is not right.

**Comment by almarklein** [comment]
Closed by #934 

> I attempted to fork the repo and made a pull request. Let me know if anything is not right.

Perfect!
