### ISSUE TITLE
Shortcut to Search in files (file browser) selected text in editor

### ISSUE THREAD

**Issue by clavay** [pyzo/pyzo#935]
Hello,

Is there a shortcut allowing to copy the selected text from the editor to the file browser `Search in files` ?

Like the Ctrl+F to search the selected text in the editor.

Thank you.

**Comment by almarklein** [comment]
No, there is no shortcut for that. We could add one, perhaps Ctrl+Shift+F?

**Comment by clavay** [comment]
Yes good idea.

**Comment by bdieterm** [comment]
I also sometimes missed such a shortcut. I added a PR to fix that: #936
