### ISSUE TITLE
Lauching Notebook from the current shell doesn't work...

### ISSUE THREAD

**Issue by chris5962** [pyzo/pyzo#940]
Hi,
I use Pyzo 4.13.3 with a Miconda install. I've installed and verified that Jupyter and Notebook packages.
But when I try to execute the 'notebook" command in the current shell, the resulting error is : 

Python 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:47:18) on Windows (64 bits).
This is the Pyzo interpreter with integrated event loop for PYQT5.
Type 'help' for help, type '?' for a list of *magic* commands.

>>> notebook
Error in notebook command:
No module named 'notebook.notebookapp'

Why is it not possible ti launch Jupyter notebook here please ?
Thanks.

**Comment by almarklein** [comment]
I completely forgot we had this command 😅 

I just tried. It works fine. Then I updated the notebook package (`pip install -U notebook`). Now I get the same error. 

So it looks like in a newer version of the notebook they changed the `notebookapp` subpackage.

**Comment by almarklein** [comment]
It's now `notebook.app`, and this is the case since the (recent) 7.0 release.

**Comment by almarklein** [comment]
Thanks for the report!

**Comment by chris5962** [comment]
Thanks Almar for your support.

 

Shall I wait to download the next version of Pyzo for bug fixing please ?

 

De : Almar Klein ***@***.***> 
Envoyé : mardi 12 décembre 2023 09:14
À : pyzo/pyzo ***@***.***>
Cc : chris5962 ***@***.***>; Author ***@***.***>
Objet : Re: [pyzo/pyzo] Lauching Notebook from the current shell doesn't work... (Issue #940)

 

I completely forgot we had this command 😅

I just tried. It works fine. Then I updated the notebook package (pip install -U notebook). Now I get the same error.

So it looks like in a newer version of the notebook they changed the notebookapp subpackage.

**Comment by almarklein** [comment]
Yes, you can wait for the next version. Or you can `conda install notebook==6.5.6` for now.

**Comment by chris5962** [comment]
I’ve already tried the downgrade to 6.5.5 and it doesn’t work for we (new error message). When is the updated version of Pyzo planned please ?

 

De : Almar Klein ***@***.***> 
Envoyé : mardi 12 décembre 2023 10:23
À : pyzo/pyzo ***@***.***>
Cc : chris5962 ***@***.***>; Author ***@***.***>
Objet : Re: [pyzo/pyzo] Lauching Notebook from the current shell doesn't work... (Issue #940)

 

Yes, you can wait for the next version. Or you can conda install notebook==6.5.6 for now.

**Comment by almarklein** [comment]
> it doesn’t work for we (new error message). 

What error does it give?

> When is the updated version of Pyzo planned please ?

Might be today, might be next week. We're doing this in our spare time, so cannot make promises.

**Comment by chris5962** [comment]
Error wad kind as ‘LIB path…’ In fact I’ve uninstalled ans reinstalle Pyzo 4.14.3 and last version of Miniconda many times so that I’d rather to wait the next update of Pyzo with Notebook bug fixed…Do you understand me ? 

 

De : Almar Klein ***@***.***> 
Envoyé : mardi 12 décembre 2023 10:42
À : pyzo/pyzo ***@***.***>
Cc : chris5962 ***@***.***>; Author ***@***.***>
Objet : Re: [pyzo/pyzo] Lauching Notebook from the current shell doesn't work... (Issue #940)

 

it doesn’t work for we (new error message).

What error does it give?

When is the updated version of Pyzo planned please ?

Might be today, might be next week. We're doing this in our spare time, so cannot make promises.

**Comment by almarklein** [comment]
Pyzo 4.14.4 was just released.

**Comment by chris5962** [comment]
Thank you very much for your annoucement Almar !

 

Can I only uninstall the previous version of Pyzo and install the new one, leaving the latest Miniconda package installed please ?

 

Regards,

 

Christophe

 

De : Almar Klein ***@***.***> 
Envoyé : mercredi 13 décembre 2023 09:07
À : pyzo/pyzo ***@***.***>
Cc : chris5962 ***@***.***>; Author ***@***.***>
Objet : Re: [pyzo/pyzo] Lauching Notebook from the current shell doesn't work... (Issue #940)

 

Pyzo 4.14.4 was just released.

**Comment by almarklein** [comment]
You can simply install the new one. It should replace the old version.

Pyzo is completely independent from your conda env.

**Comment by chris5962** [comment]
Thank you very much. It works fine now ! Regards, Christophe

 

De : Almar Klein ***@***.***> 
Envoyé : mercredi 13 décembre 2023 09:44
À : pyzo/pyzo ***@***.***>
Cc : chris5962 ***@***.***>; Author ***@***.***>
Objet : Re: [pyzo/pyzo] Lauching Notebook from the current shell doesn't work... (Issue #940)

 

You can simply install the new one. It should replace the old version.

Pyzo is completely independent from your conda env.
