### ISSUE TITLE
Pyzo don't open Mac OS 14.2.1

### ISSUE THREAD

**Issue by AureMadzo** [pyzo/pyzo#950]
Hello to everyone,
I try to instal and run Pyzo.app but the app doesn't launch and I have a report message.
I verify on the terminal that I have the latest version of python 3 (3.9)

My mac has a 1.1GHz intel core 5 and it's a retina from 2020.

Can you please help me to run pyzo ?

Thanks a lot.

<img width="899" alt="Capture d’écran 2024-01-19 à 12 04 26" src="https://github.com/pyzo/pyzo/assets/157116592/1bc57992-7470-4b61-a352-c9825fa70402">

**Comment by jowe19** [comment]
The same here. I can't wait for macOS 14.3 to be released this week.

**Comment by AureMadzo** [comment]
> Wow, it crashes with a segfault 😕 It works fine on my Mac (an M1 with MacOS 14.3).
> 
> You could try running it from source: Install PySide or Pyqt and `pip install pyzo`, then just run `pyzo` or `python -m pyzo`.

Thanks a lot for this Tips, now I can run a Python script with pyzo and the app runs.
Regards

**Comment by almarklein** [comment]
>  now I can run a Python script with pyzo and the app runs.

Great!  Can you please tell what version of PyQt5/PySide you are using (you can see in "about Pyzo" in the help menu)?
