### ISSUE TITLE
Pyzo has a generic Wayland icon

### ISSUE THREAD

**Issue by new-penguin** [pyzo/pyzo#951]
![pyzo](https://github.com/pyzo/pyzo/assets/139792946/24ec7eed-4154-4748-afaa-0640c92b2564)

OS: EndeavorOS with KDE and Wayland compositor. [This](https://nicolasfella.de/posts/fixing-wayland-taskbar-icons) fix works but I thought it was worth mentioning from an aesthetic perspective.

**Comment by almarklein** [comment]
Thanks for the heads-up!

> [This](https://nicolasfella.de/posts/fixing-wayland-taskbar-icons) fix works

What did you do exactly, and can we change something in the Pyzo source to fix this, e.g. call 
`QGuiApplication::setDesktopFileName("org.??.??")`

**Comment by bdieterm** [comment]
I just tested this on a Ubuntu 22.04 with Wayland.
When running Pyzo from source and using the provided .desktop template, then the icon is correct.
And the template also registers Pyzo as an application so that it can be run via the desktop environment's starter.
