### ISSUE TITLE
Can't open Pyzo on my Mac

### ISSUE THREAD

**Issue by mygarec** [pyzo/pyzo#952]
Hello!

I tried to install Pyzo on my MacMini 2014 (with 2,6GHz Intel Core i5 CPU) but when I start the program, he doesn't open and showed an error message :
![error-msg](https://github.com/pyzo/pyzo/assets/57267087/951597ed-fbf1-4b01-89bc-2851cc8ac93c)
(translate: pyzo has left unexpectedly ; Click on Relancer to reopen the application / Click Signaler to get more detalls
and send a report to Apple.)

I also tried to install with the .zip file but he said that the file is damaged : 
![zipfile-msg](https://github.com/pyzo/pyzo/assets/57267087/13a17c72-939c-4732-8a08-841c496d92a5)
(translate: "pyzo" is damaged and cannot be opened. You should move this item in the Recycle Bin. ; Chrome downloaded this file today at 14:55.)

I'm on MacOS Monterey (12.7.3 (21H1015)).

Thank you in advance for your help! Have a nice day!

**Comment by almarklein** [comment]
Hi, thanks for reporting this! Reading [this](https://github.com/orgs/pyinstaller/discussions/6316) it could be related to the minimal os version required by Python or PySide. Although MacOS 12.7 is not *that* old ...

Another possibility is a bug in PySide. We had a somewhat similar report in #950.

My recommendation for now is to install Pyzo from source:
* Install Python3 with PySide6, PySide2, PyQt6 or PyQt5.
* `pip install pyzo`.
* Run pyzo using just `pyzo` or `python -m pyzo`.

**Comment by mygarec** [comment]
I've just installed Pyzo from source and it works really well!
Thanks for your help!
