### ISSUE TITLE
pyzo on termux

### ISSUE THREAD

**Issue by risky777** [pyzo/pyzo#968]
I managed to get pyzo working under android-aarch64-termux-xfce4. Standard termux setup with python and xfce4-vnc, added pyqt5.

Difference to archlinux is:
1. When I wanted to open any file, in terminal I got error: "...[Errno 13] Permission denied: '/'...". I fixed that by modification of "pyzo / core / baseTextCtrl.py", I replaced function normalizePath with "return path".
2. Python scripts didn't run until I set "Pyzo / Run / Change directory when executing file".

Can something be done about modification 1 (function normalizePath)?

**Comment by bdieterm** [comment]
I had a look at `normalizePath` and implemented it in a different way, see #969.
Does this solve your problem?
If not, can you check which part of the `normalizePath` function caused the problem (e.g. `os.listdir()`)?

Regarding your second problem:
This is strange. The only difference with that option enabled is the following code in the interpreter: https://github.com/pyzo/pyzo/blob/d96556622c8332a00ec799861bdbca189da1d382/pyzo/pyzokernel/interpreter.py#L839-L843

**Comment by risky777** [comment]
Problem 1: Solution seem to work.

Problem 2: Problem doesn't seem to appear anymore.

Thanks.
